core-runner/src/runner.rs
core/src/message.rs
core/src/program.rs
core/src/storage.rs
core/src/util.rs

Fixes #97.
- Program memory interactions return results.
- Add program memory test.
- Reset static pages in Program::set_code().
- encode_hex() return result.
@gear-tech/dev

Avoid expect in gear-core

---

core-backend/src/funcs.rs
core-runner/src/runner.rs
core/src/env.rs

I got tired of solving conflicts. So I push this small change separately.
- Tune refs vs. mut refs.
- Use `Result` in a more functional way.
- Don't Repeat Yourself (DRY).
@gear-tech/dev

Refactor syscalls wrappers by removing repeating pieces

---

core-runner/src/builder.rs
core-runner/src/lib.rs
core-runner/src/runner.rs

Fixes #128.
```rust
let mut runner = RunnerBuilder::new()
.program(parse_wat(wat))
.init_message(ExtMessage {
id: 1000001.into(),
payload: "init".as_bytes().to_vec(),
gas_limit: u64::MAX,
value: 0,
})
.build()
.program(parse_wat(wat))
.build()
.build();
```
@gear-tech/dev

Runner builder

---

Cargo.lock
Makefile
common/src/lib.rs
gtest/spec/test_condensator.yaml
gtest/spec/test_mem.yaml
gtest/spec/test_vec.yaml
gtest/src/check.rs
gtest/src/runner.rs
gtest/src/sample.rs
node-rti/Cargo.toml
node-rti/src/ext.rs
utils/gear-test-cli/src/command.rs

Required for correct testing of (#80)
Allows to test allocation page count and compare exact allocated page indexes.
@shamilsan

Add different allocation checks to gtest

---

core-backend/src/funcs.rs
core-backend/src/wasmi/env.rs
core-backend/src/wasmtime/env.rs
core-runner/src/runner.rs
core/src/env.rs
core/src/gas.rs
gstd/src/msg.rs
gstd/tests/smoke.rs
node-rti/src/lib.rs
pallets/gear/src/lib.rs
pallets/gear/src/tests.rs

1. Gas is not counted as burned and validator does not claim it (yet) when one message creates another message
2. Gas reservation is removed because now you can just send message to yourself to do basically the same

Refactor gas charges when accounting further messages

---

.github/workflows/master.yml

At the moment RPC tests works randomly and cannot act as a good test yet.
They might be fixed later, so there is no need to delete it now, just comment it in CI check.
@gear-tech/dev

Remove rpc tests from CI

---

core-backend/src/funcs.rs
core-backend/src/wasmi/env.rs
core-backend/src/wasmtime/env.rs
core-runner/src/runner.rs
core/src/env.rs
core/src/message.rs
examples/Cargo.toml
examples/multiping/Cargo.toml
examples/multiping/src/lib.rs
gstd/src/general.rs
gstd/src/msg.rs
gtest/spec/test_multiping.yaml

- Message meta data about destination, gas limit and value moved to `send_commit` from `send_init`
- `MessageId` now generates only when message are sent or committed
- Removed `FormationStatus` flag: now `MessageState`'s `outgoing` has type `Vec<(Option<Payload>, Option<OutgoingMessage>)>`. When `Option<Payload>` is `None` it means that `OutgoingMessage` was formed
- API updated
- Tests updated
@gear-tech/dev

Move meta data to send_commit

---

core-backend/src/funcs.rs
examples/async/src/lib.rs
gstd-async/src/lib.rs
gstd-async/src/msg.rs
gstd-async/tests/send_reply.rs
gtest/spec/test_async.yaml
gtest/src/main.rs
gtest/src/runner.rs

Another step to deal with #11.
- Use `wait`/`wake` functions.
- The solution is quite ugly and not optimal at the moment, need to find a better one.
TODO:

Rework gstd-async to be based on wait/wake

---

examples/Cargo.toml
examples/capacitor/Cargo.toml
examples/capacitor/src/lib.rs
gtest/spec/test_capacitor.yaml

According to changes in the whitepaper: https://github.com/gear-tech/gear-wp/blob/main/TECHNICAL.md

Rename `condensator` example to `capacitor`

---

examples/fib/src/lib.rs
examples/panicker/Cargo.toml
examples/panicker/src/lib.rs
examples/sum/src/lib.rs
examples/vec/src/lib.rs
scripts/build-wasm.sh

- Rewrite build-tests script to build each example separately
- Fix dependency features in examples
Unfortunately, the only way to separate dependency feature flags for workspace members is to build them separately
@NikVolf @shamilsan

Build examples separately to prevent feature join

---

Cargo.toml
examples/Cargo.toml

Cargo issue that might lead to some strange crate conflicts:
https://github.com/rust-lang/cargo/issues/5730
Rust patch note with new `resolver` version, which fixes the issue:
https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html
@gear-tech/dev

Specify resolver version for each workspace

---

Cargo.lock
node/Cargo.toml
node/src/chain_spec.rs
node/src/command.rs

Fixes #163 .
- Staging testnet configuration has 4 initial authority accounts and a root_key account who would hold the whole initial token supply.

Add staging testnet chain spec

---

common/src/lib.rs
common/src/native.rs
node-rti/src/ext.rs
rpc-tests/index.js
utils/gear-test-cli/src/command.rs

- `Program.persistent_pages: BTreeSet<u32>` instead of `BTreeMap<u32, Vec<u8>>`
- each page is stored with prefix `g::prog::<program_id>::pages::<page_num>`
@gear-tech/dev

Store program pages in storage

---

.github/workflows/CI.yaml
Makefile
core-runner/src/builder.rs
core-runner/src/ext.rs
core-runner/src/runner.rs
core-runner/src/util.rs
core/src/message.rs
examples/capacitor/src/lib.rs
examples/collector/src/lib.rs
examples/decoder/src/lib.rs
examples/multiping/src/lib.rs
examples/ping/src/lib.rs
node-rti/src/ext.rs
node/src/service.rs
pallets/gear/src/lib.rs
rustfmt.toml
scripts/pre-commit.sh
tests/btree/build.rs
tests/btree/src/lib.rs
tests/common/src/lib.rs
tests/distributor/build.rs
tests/distributor/src/lib.rs
tests/node/build.rs
tests/node/src/lib.rs

- Add `rustfmt.toml` with specific settings.
- Use rustfmt v2.
- Add some useful settings.
- Update CI to conform.

Configure rustfmt to be more useful

---

.github/workflows/docs.yml
gstd-async/src/lib.rs
gstd/src/lib.rs

- Revert CI config that generates docs for gear-core.
- Add docs generation for `gstd` and `gstd-async`.
- Deploy docs to `gh-pages` branch.
- GH Pages will be configured after merge.

Add CI config for documentation deployment

---

pallets/gear/src/lib.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs
runtime/src/lib.rs

Fixes #173.
- The expected block time is set to 1 sec;
- The call of `process_queue` is placed in the `on_idle` hook which is executed after all normal extrinsics (those with `DispatchClass::Normal`) have been processed, as opposed to having it as an inherent extrinsic which would have to be run before normal dispatchables;
- The normal extrinsics max weight is set to 25% of the total block weight which guarantees the `on_idle` hook will be executed in every block.

Reduce block time and process queue at the end of a block

---

scripts/build-wasm.sh

Fixes build issue on Mac, where `\n` character is not recognized and `n` is inserted instead.

Fix build-wasm script for mac

---

pallets/gear/src/lib.rs
pallets/gear/src/tests.rs

Since it was required for rpc-tests that are now being redesigned

Remove message processed thing also

---

.github/workflows/CI.yaml
Cargo.lock
Makefile
core/src/message.rs
gstd-meta/tests/json.rs
node-rti/src/ext.rs
rustfmt.toml
scripts/pre-commit.sh
tests/btree/Cargo.toml
tests/btree/src/lib.rs
tests/common/Cargo.toml
tests/distributor/Cargo.toml
tests/distributor/src/lib.rs
tests/node/Cargo.toml
tests/node/src/lib.rs

Fixes #258.
- Move to the local fork of `substrate-wasm-builder`.
- Fix the rustic flags applying in `substrate-wasm-builder`.
- Replace `WASM_BINARY` with `WASM_BINARY_BLOATY`

Fix standalone tests after upgrading rustc to v1.55

---

Cargo.lock

- Need to build gear-node against Windows.

Bump parity-db from 0.3.1 to 0.3.2

---

pallets/gear/src/lib.rs
pallets/gear/src/tests.rs

Fixes #246.
- added a storage value that holds the flag indicating whether the runtime "debug" mode is on;
- added an extrinsic callable by the root origin that can modify this storage value thus switching the debug mode on and off in runtime (without a need for restarting a node or storage migration);
- the message queue and programs storage contents are wrapped as runtime events.
The following information is currently being logged:

Enable runtime 'debug' mode

---

pallets/gear/src/lib.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs

Newly added tests revealed that `send_message` and `send_reply` extrinsics, having failed, can in some cases still modify the state.
The suggested fix wraps the two calls in the `transactional` macro thereby forcing all changes to be rolled back if anything but `Ok(())` has been returned.

Roll back changes in state if extrinsic throws

---

Cargo.lock
Cargo.toml
common/src/lib.rs
common/src/native.rs
core-runner/src/runner.rs
core/src/storage.rs
node-runner/src/ext.rs
tests/wait_wake/Cargo.toml
tests/wait_wake/build.rs
tests/wait_wake/src/lib.rs

Fixes #129.
- wait-list cache now has `(ProgramId, MessageId)` tuple as a key;
- wait-list is stored with prefix `g::wait::<ProgramId>::<MessageId>`;
- Acessing wait-list message now also requires ProgramId. Current ProgramId is used, so program can only access own wait-list messages;
- wait-list standalone tests were added.
@NikVolf @shamilsan

Make wait-list scoped to corresponding program (#129)

---

examples/vec/src/lib.rs
gtest/spec/test_vec.yaml

Skip vector destruction in vec example, so that two pages stay allocated

---

gtest/src/check.rs

Sometimes we want to send message with custom payload from some external source (user imitation) in gtest. And it fails, because gtest tries to find it's metadata. This PR allows to find not only Output, but also Input types.
@gear-tech/dev

Refactor finding program's meta for custom payload

---

Cargo.lock
core-backend/common/src/funcs.rs
core-backend/sandbox/src/env.rs
core-backend/wasmtime/src/env.rs
core-runner/src/builder.rs
core-runner/src/ext.rs
core-runner/src/lib.rs
core-runner/src/runner.rs
core/src/env.rs
examples/Cargo.lock
examples/Cargo.toml
examples/block-info/Cargo.toml
examples/block-info/src/lib.rs
examples/block-info/test_block_info.yaml
gcore/src/exec.rs
gtest/src/runner.rs
node-runner/src/lib.rs
pallets/gear/Cargo.toml
pallets/gear/src/lib.rs
pallets/gear/src/mock.rs
tests/common/src/lib.rs

Fixes #301.
- Add `gr_block_timestamp` syscall that returns `u64` timestamp in milliseconds since the Unix epoch.
- Rename `blolck-height` example to `block-info`.
@gear-tech/dev

Add a syscall to get the block timestamp in programs

---

.gitignore
core-runner/src/builder.rs
core-runner/src/runner.rs
core/src/storage.rs
gtest/src/check.rs
gtest/src/main.rs
gtest/src/runner.rs
node-runner/src/lib.rs
tests/common/src/lib.rs
utils/gear-test-cli/src/command.rs

Close #386 .
- Make `core_runner::Runner` and other types definitions more readable with covering `storage::{MessageQueue, ProgramState, WaitList}` traits unders one trait (i.e., `StorageCarrier`).
@gear-tech/dev

Refactor `Runner` to depend on a single Storage trait

---

Cargo.lock
gcore/src/general.rs
gstd/src/msg.rs
tests/btree/src/lib.rs
tests/distributor/src/lib.rs
tests/gas_limit/src/lib.rs
tests/messages/Cargo.toml
tests/messages/build.rs
tests/messages/src/lib.rs
tests/node/src/lib.rs

Fixes messaging tests #141.
Breaks `gcore` API compatibility to prevent invalid operations on message handle.

Add messaging negative tests

---

core-runner/src/runner.rs
gtest/src/check.rs
gtest/src/js/mod.rs
gtest/src/lib.rs
gtest/src/runner.rs
gtest/src/sample.rs

In order to close #347, some research on how program initialization works was done. For the purpose of research `gtest` and underlying crates were discovered and (partly) documented in the context of program initialization. I didn't intend to document everything, but do that just in some bounded scope while understanding program submit process.
No issues were resolved here, actually.
Please merge asap.

Add docs to program initialization related code

---

Cargo.lock
core-runner/src/runner.rs
examples/Cargo.lock
examples/async/src/lib.rs
examples/chat/bot/src/lib.rs
examples/chat/room/src/lib.rs
examples/fungible-token/Cargo.toml
examples/incomplete_async_payloads/src/lib.rs
examples/mutex/src/lib.rs
examples/ping/src/lib.rs
examples/rwlock_write/src/lib.rs
examples/sync_duplicate/src/lib.rs
examples/token-vendor/Cargo.toml
examples/token-vendor/src/lib.rs
examples/token-vendor/workshop-example/Cargo.toml
examples/token-vendor/workshop-example/src/lib.rs
galloc/Cargo.toml
gcore/Cargo.toml
gstd/Cargo.toml
gtest/spec/test_capacitor.yaml
gtest/spec/test_chat.yaml
gtest/spec/test_vec.yaml
gtest/src/js/package-lock.json
gtest/src/js/package.json
tests/distributor/src/lib.rs

Issues #432 
- Fix gas in demos - reduce gas_limit values.
- Change allocator version to new, where implemented:
- Static buffer allocation for small requests
- Fix problem with small chunks which restrict to free page sometimes
- Add free in realloc and sys_alloc
- Optimize allocator algorithms
**Release notes**: Improves our user-space custom allocator

Fix demo gas and switch to new version allocator

---

common/src/lib.rs
node-runner/src/lib.rs
pallets/gear/src/lib.rs

Collect all the results of processing a message into the `ExecutionReport` (including outgoing messages, wait list and awakened messages) and do all necessary actions upon the execution in the pallet, as opposed to doing part of the work in the node-runner, which has previously been the case.

Move queue and wait list processing to gear pallet

---

core-runner/src/builder.rs
core-runner/src/runner.rs
gtest/spec/test_chat.yaml
node-runner/src/lib.rs

Resolves #464 .
`Runner::message_queue` removed so messages don't get duplicated after `init`. Code is adjusted to the change
@gear-tech/dev

Remove `Runner::message_queue` field 

---

node/Cargo.toml

- Add the minimum required Rust compiler version: 1.56 at the moment.

Add minimum Rust compiler version to gear-node

---

gtest/src/check.rs
gtest/src/main.rs
utils/gear-test-cli/src/command.rs

`-v` to print logs from fixture runs.
@gear-tech/dev

`gtest`: add verbose mode

---

examples/Cargo.lock
examples/Cargo.toml
examples/init-wait/Cargo.toml
examples/init-wait/src/lib.rs

Resolves #489.
Currently without test_spec.yaml since there is no support in node/gtest at the moment.
@gear-tech/dev

Add example program that calls `wait` in `init`

---

gstd/src/macros/export.rs

Otherwise allocator will corrupt memory which was returned

Add mem::forget for returned strings

---

.github/workflows/CI.yaml

Resolves #399.
Upload to the [Releases section](https://github.com/gear-tech/gear/releases):
- `gear-node` (Linux x86_64)
- `gtest` (Linux x86_64)
- `wasm-proc` (Linux x86_64)
- `examples.tar.gz` (gzipped WASMs)
- `gear-runtime.wasm` (WASM)

Upload build artifacts to Releases

---

gtest/src/check.rs

Resolves #511.
- add more targets
- print target name with record
@gear-tech/dev

`gtest`: show logs from backend common and print target with record

---

core-backend/common/src/funcs.rs
core-backend/sandbox/src/env.rs
core-backend/wasmtime/src/env.rs
core-runner/src/ext.rs
core/src/env.rs
examples/Cargo.lock
examples/Cargo.toml
examples/program-id/Cargo.toml
examples/program-id/src/lib.rs
gcore/src/exec.rs
gstd/src/exec.rs
gtest/spec/test_program_id.yaml

**Release Notes:** `program_id()` function is added to `gstd` which returns program_id of the program in execution. This can be used where the program wants to store funds like fungible-tokens to for itself.

Provide `program_id()` syscall

---

rpc-tests/src/index.ts

Wait for 2-3 blocks before sending new messages. This fixes failures looking like this:
```
Fixture rwlock-write
MSG ERR: Message not found (expected: {
"destination": 6,
"payload": {
"kind": "utf-8",
"value": "START"
}
})
Encountered an error: broken pipe
Enable a logger to see more information.
Error: Process completed with exit code 1.
```
for example: https://github.com/gear-tech/gear/runs/4671100387?check_suite_focus=true
https://github.com/gear-tech/gear/runs/4719226629?check_suite_focus=true

Add workaround to rpc-tests

---

pallets/gear/src/lib.rs
pallets/gear/src/manager.rs
pallets/gear/src/tests.rs

Resolves #556.
This change creates a distinction between messages in queue or those being processed and messages in some user's mailbox: getting into a mailbox is the end of a message life cycle, where no further processing can take place. Therefore, messages in the mailbox should not bring along any gas: no new node should be `split_off` from the gas tree associated with the parent message - all gas must remain in the parent tree.
This allows to unblock gas tree consumption if the only unconsumed message in a chain is that ended up in someone's mailbox.
If a reply follows, the author of the reply message must create a separate gas tree and pay for it by reserving their currency.
This allows to avoid a potentially buggy situation with offsetting gas/value of a mailboxed message against …

Keep all gas in parent's tree when sending message to mailbox

---

utils/wasm-proc/metadata-js/index.js
utils/wasm-proc/metadata-js/test.js

Resolves #500.
- Make calling functions exports optional: if provided in wasm.
- For each binary, which contains `meta_registry` function, check if it's valid hex.
@gear-tech/dev

Validate `Registry` for each `.meta.wasm`

---

gear-test/src/js/package-lock.json
rpc-tests/package-lock.json
utils/wasm-proc/metadata-js/package-lock.json

- Update `node-fetch` to v2.6.7 for addressing [CVE-2022-0235](https://github.com/advisories/GHSA-r683-j2x4-v87g).
@gear-tech/dev

Update `node-fetch` to fix Dependabot alerts

---

ansible/README.md
ansible/tasks/docker/docker-compose.yaml.j2

Rectify documentation and the command that runs the node in the old template file which is still useful as an example of how to run a validator.

[skip ci] Fix error in documentation and command example

---

node/README.md

Rendered: https://github.com/gear-tech/gear/blob/sy-fix-link/node/README.md

[skip ci] Fix link to chain spec in README

---

Cargo.lock
core-backend/common/src/lib.rs
core-backend/sandbox/Cargo.toml
core-backend/sandbox/src/env.rs
core-backend/wasmtime/src/env.rs
examples/block-info/src/lib.rs
examples/bot/src/lib.rs
examples/collector/src/lib.rs
examples/decoder/src/lib.rs
examples/exit-code/src/lib.rs
examples/fib/src/lib.rs
examples/guestbook/src/lib.rs
examples/mem/src/lib.rs
examples/minimal/src/lib.rs
examples/multiping/src/lib.rs
examples/panicker/src/lib.rs
examples/ping/src/lib.rs
examples/program-id/src/lib.rs
examples/state_rollback/src/lib.rs
examples/sync_duplicate/src/lib.rs
examples/vec/src/lib.rs
examples/wait/src/lib.rs

Resolves #640.
@gear-tech/dev 
**Release Notes**: If some of entry point (`init`, `handle` or `handle_reply`) isn't provided, it means now that this function is an empty function.
This code ⬇️ 
```rust
#![no_std]
use gstd::msg;
#[no_mangle]
pub unsafe extern "C" fn handle() {
msg::reply_bytes("Handle", 0, 0);
}
```
now equals this one ⬇️ 
```rust
#![no_std]
use gstd::msg;
#[no_mangle]
pub unsafe extern "C" fn init() { }
#[no_mangle]
pub unsafe extern "C" fn handle() {
msg::reply_bytes("Handle", 0, 0);
}
#[no_mangle]
pub unsafe extern "C" fn handle_reply() { }
```
It used to cause panic.

Normalize missing entry case

---

Cargo.lock
utils/wasm-builder/Cargo.toml
utils/wasm-builder/README.md
utils/wasm-builder/src/cargo_command.rs
utils/wasm-builder/src/wasm_project.rs
utils/wasm-builder/test-program/Cargo.lock
utils/wasm-builder/test-program/src/lib.rs

Minor fixes in `gear-wasm-builder`.
- Build WASM in release mode regardless of the selected profile.
- Beautify `wasm_binary.rs` a little bit. 
@gear-tech/dev

gear-wasm-builder: Always build WASM in release mode

---

pallets/gear/src/lib.rs
runtime/src/lib.rs

Sometimes the value of `gas_limit` field of a `Message` can diverge from the value locked in the `GasHandler` (f.k.a. value tree or gas tree). This can happen, for instance, when a message sends out another message sharing with it some of its gas and after the other message has been processed and the gas tree node consumed, the leftover returns to the original message node. This is not reflected in the `gas_limit` field of the `Message` struct.
This PR fixes this situation and eliminates a basis for discrepancies.

Align gas_limit in a message with the value locked in gas handler

---

examples/meta/src/lib.rs
gstd/src/lib.rs
gstd/src/macros/mod.rs

By request from @AndrePanin.
- Add docs for utility functions in `gstd`.
- Make `utils` importable directly from `gstd` as more intuitive (e.g. `gstd::util::to_leak_ptr()` instead of `gstd::macros::util::to_leak_ptr()`).
@gear-tech/dev

Add docs to `gstd` utility functions

---

utils/gear-runtime-test-cli/src/command.rs

- use gear_common::set_program to store empty program
- log::debug -> log::trace
@gear-tech/dev

use gear_common::set_program to store empty program

---

Cargo.lock
core-backend/common/src/funcs.rs
core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/wasmtime/src/env.rs
core-processor/src/ext.rs
core/Cargo.toml
core/src/env.rs
core/src/message.rs
core/src/program.rs
gcore/Cargo.toml
gcore/src/general.rs
gcore/src/msg.rs
gcore/src/prog.rs
gstd/src/common/primitives.rs
gstd/src/lib.rs
gstd/src/msg/basic.rs
gstd/src/prog/mod.rs
pallets/gear/src/ext.rs
runtime/src/lib.rs
utils/wasm-builder/test-program/Cargo.lock

Creating program from program implementation is on `st-create-program-from-program-iter1` branch and quite big. To make it easy for review, I decided to divide it to separate PRs.
This is the first one.
**Release notes**: a new sys-call for sending init messages in program is introduced.
@gear-tech/dev

Patch 1 for program from program creation

---

core-backend/common/src/funcs.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/wasmtime/src/env.rs
core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core-processor/src/processor.rs
core/src/env.rs
gcore/src/exec.rs
gear-test/src/proc.rs
gstd/src/exec.rs
gtest/src/manager.rs
pallets/gear/src/ext.rs
pallets/gear/src/lib.rs
runtime/src/lib.rs
scripts/check-spec.sh
tests/common/src/lib.rs

By @LouiseMedova's request:
Provides an ability to get the id of original user who initiated communication with blockchain, during which, currently processing message was created.
Integration for `gear-test` won't be realized, until we hadn't done with #649 
@gear-tech/dev

Getter for initial user of messaging

---

core/src/gas.rs
lazy-pages/src/unix.rs
pallets/gear/src/manager.rs
pallets/usage/src/lib.rs
runtime/src/lib.rs

In order not to flood users logs with irrelevant messages (while sync'ing the node) use the `error` or `warn` log levels sparingly.
Instead, it is recommended to use `log::debug!` and direct the messages to the `essential` target which will be enabled on validators' nodes by default via a CLI flag (the latter feature will be implemented in a separate PR).

Replace log::error! and warn! with debug! to a specific target

---

common/src/lib.rs
common/src/native.rs
core/src/program.rs
gear-test/src/manager.rs
pallets/gear-debug/src/tests.rs
pallets/gear/src/benchmarking.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager.rs
pallets/gear/src/tests.rs
runtime/src/lib.rs
utils/gear-runtime-test-cli/src/command.rs

As @breathx proposed, later we will introduce traits to compute ids/hashes and such things (because hash function can be changed). It will be easier to do that if id/hash computations are performed in one place - as associated function of corresponding types. Also need these changes to resolve cleaner other issue I'm working on.
@gear-tech/dev

Unify code hash generation

---

ansible/tasks/docker/docker-compose.yaml.j2
pallets/usage/src/mock.rs
pallets/usage/src/tests.rs
runtime/src/lib.rs

Having decreased the default log level for some messages we still need them to be visible on validators nodes. Enabling `RUST_LOG` environment variable in docker-compose template for that.
On a separate note, added test for the case that originally resurfaced the issue (removing "dust" destination accounts upon currency transfer in `pallet-balances`) in `pallet-usage`.

Modify node startup scripts to enable essential debug logging

---

gear-test/spec/test_create_program.yaml
gear-test/src/check.rs
gear-test/src/sample.rs

This hot fix is introduced until we decide finally on having salt in `create_program_with_gas` function. If salt remains, then the solution in #739 will be merged. Otherwise, we take salt management responsibility and introduce it in https://github.com/gear-tech/gear/issues/703

Skip fixtures feature introduced

---

.github/workflows/docs.yml
gcore/src/msg.rs
gstd/src/msg/async.rs
gstd/src/msg/basic.rs
gstd/src/msg/encoded.rs
lazy-pages/src/lib.rs

Added crates to be shown on https://docs.gear.rs:
- `gear-backend-common`
- `gear-backend-sandbox`
- `gear-core-processor` 
- `gear-lazy-pages` 
- `gtest`
- `gear-wasm-builder`
Also, minor fixes in doc generating have been made.
Please tell me if we want to add something else.
@gear-tech/dev

Add more Gear crates to docs generating

---

ansible/tasks/docker/docker-compose.yaml.j2

Setting `RUST_LOG` variable in docker-compose template the correct way (without quotes). This time round nodes should be able to start and not cause testnet stall - tested locally.

[skip ci] Fix setting of env vars in docker-compose template

---

Cargo.lock
utils/wasm-builder/Cargo.toml
utils/wasm-builder/README.md
utils/wasm-builder/src/wasm_project.rs
utils/wasm-builder/test-program/Cargo.lock

- Write output WASM files to the workspace target directory instead of the package one when using in the workspace.
@gear-tech/dev

gear-wasm-builder: Fix target WASM path when using in workspace

---

Cargo.lock
core-processor/src/ext.rs
core-processor/src/lib.rs
core-processor/src/processor.rs
runtime/src/lib.rs
tests/common/Cargo.toml
tests/common/src/lib.rs

Resolves #768 
- eliminate `expect` in `process`
- remove `unwrap` in `EnvExt::alloc`
- remove `unreachable` in `process_success`
- move `process_many` to `tests/common` (it's not called by other modules)
@gear-tech/dev

Handle possible errors in `core-processor`

---

Cargo.lock
gtest/src/program.rs
utils/wasm-builder/Cargo.toml
utils/wasm-builder/src/wasm_project.rs
utils/wasm-builder/test-program/.gitignore
utils/wasm-builder/test-program/Cargo.lock

By @SabaunT request.
First motivation: `Program::current` wasn't working out of common `cargo test` command due to absence of `OUT_DIR` env var, what made `cargo nextest` incompatible with this feature. 
- Path to opt binary now writes in `crate_root/.binpath`
- Path in `.binpath` now not absolute - it's relative, what allows to avoid username appearing in it. 
@gear-tech/dev

Avoid env vars in `gtest::Program::current()`

---

.gitattributes

Git usually automatically converts line endings to CRLF on Windows. It is useful to keep them according to EditorConfig. Also, it can break bash scripts

Add `.gitattributes` configuration file

---

common/src/lib.rs
pallets/gas/src/lib.rs
pallets/gas/src/tests.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager.rs
pallets/usage/src/lib.rs
pallets/usage/src/mock.rs
pallets/usage/src/offchain.rs
pallets/usage/src/tests.rs
runtime/src/lib.rs

Following the introduction of messages with unspecified concrete gas limit (that is, derived from some upstream message), the `GasHandler` API has been changed:
- the `get_limit(key)` function now returns the pair of the available gas for a message and the id of the tree node that sets this limit (previously returned the external origin as the second item in the pair);
- to get the external origin, the `get_origin(key)` method has been introduced.
Apart from the API change, a possibility to actually process the mock transaction pool has been added to the tests in `pallet-usage`.

Small amendment of GasHandler API

---

Cargo.lock
Cargo.toml

Fixes Windows builds failures after #795

Use branch with pregenerated files for patched ring

---

Cargo.lock
Cargo.toml

This reverts commit 47d84922f72aab829d5ee0c48039b0cee20e4a43.
@gear-tech/dev

Revert "use patched ring to fix CI (#795)"

---

pallets/usage/src/lib.rs
pallets/usage/src/mock.rs
pallets/usage/src/tests.rs
runtime/src/lib.rs

When a message is removed from the wait list due to inability to pay rent (run out of free gas), a trap reply is generated with a new gas node split from the one corresponding to the expelled message. This must be followed by explicit consumption of that node.

Bugfix: gas nodes are not properly consumed in some circumstances

---

.github/workflows/CI.yaml

With this change, the cache will always be up to date and we won't have to clean it manually after a while.
@gear-tech/dev

CI: drop old cache when merged to master

---

examples/binaries/btree/src/lib.rs
examples/binaries/distributor/src/lib.rs

There are no building problems when compiling on macOS and Ubuntu 20.04 LTS (as well as CI based on it). But the build fails on Ubuntu 21.10.
The problem seems to be in the linker (`ld`) version (`v2.34` on 20.04 LTS vs `v2.37` on 21.10). The newer version seems to be more strict resulting in linker error due to `handle`/`init` symbols doubling.
The fix hides `init`/`handle`/`handle_reply` functions when building with the `std` feature.

Fix build on Linux

---

core-processor/src/common.rs
gear-test/spec/test_create_program.yaml
gear-test/spec/test_failed_program_msg_handling.yaml
gear-test/src/check.rs
gear-test/src/manager.rs
gear-test/src/proc.rs
gear-test/src/sample.rs
pallets/gear-debug/src/lib.rs
pallets/gear-debug/src/tests.rs
pallets/gear/src/manager.rs
runtime/src/lib.rs
utils/gear-runtime-test-cli/src/command.rs

Resolves #661.
I added track of terminated programs into state. 
Rewrite active programs checking in gear-test, that way it also checks terminated programs.
It should work without rewriting existing .yaml files.
Issue seem to be resolved, but I have technical issues with tests, so can't be sure yet.
@gear-tech/dev

Provide active and terminated program checks

---

.github/workflows/CI.yaml
Makefile

These checks seems unused nowadays, so deleting them a bit decreases test time.
@gear-tech/dev

Remove redundant testing from `CI` and `pre-commit`

---

core-processor/src/ext.rs
gstd/src/common/handlers.rs
gstd/src/lib.rs
gstd/src/macros/debug.rs
runtime/src/lib.rs

- Refactor the panic handler for programs compiled with the `debug` feature to have fewer allocations.
- Propagate `Panic occurred` as an error explanation.
@gear-tech/dev

Improve programs' panic handling

---

Cargo.lock
common/src/storage/deque.rs
core-backend/sandbox/src/funcs.rs
gear-test/src/proc.rs
pallets/payment/Cargo.toml
pallets/payment/README.md
pallets/payment/src/lib.rs
pallets/payment/src/mock.rs
pallets/payment/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs

Implements one of the measures in order to resolve [this issue](https://github.com/gear-tech/core-audit/issues/2).
Briefly, a solution is to increase transaction fees if the message queue inflates and reduce them back once it's shrunk down. This would raise a barrier for transactions to enter the system and relieve the pressure on the processing engine.
This is a modification of the standard approach taken in Substrate to adjust fees based on the overall network congestion level.
Generally, it is reasonable to charge transactions that affect the Message Queue based on the gas_limit they declare:
`Fee = base_fee + P⋅tx.len +  𝛂⋅F(tx.weight) + 𝛃⋅G(tx.gas_limit)`, 
where `P` - per byte cost, `F(.)` - weight to fee conversion function, `G(.)` - gas-to-fee conversion function (`gas_price`),`𝛂 …

Introduce gear payment pallet

---

examples/Cargo.lock
examples/Cargo.toml
examples/ping-gas/Cargo.toml
examples/ping-gas/src/lib.rs
examples/ping/src/lib.rs
gcore/Cargo.toml
gear-test/spec/test_ping.yaml

Resolves #884.
- Ping demos split
- Old and minimal demo ping bases on `gcore` and `galloc` now
@grishasobol, Your fashionable ping, sir.

Return old minimal ping

---

Cargo.lock
examples/binaries/compose/Cargo.toml
examples/binaries/compose/build.rs
examples/binaries/compose/src/lib.rs
examples/binaries/mul-by-const/Cargo.toml
examples/binaries/mul-by-const/build.rs
examples/binaries/mul-by-const/src/lib.rs
pallets/gas/src/lib.rs
pallets/gear/Cargo.toml
pallets/gear/src/tests.rs
runtime/src/lib.rs

A node wouldn't be marked as "consumed" unless it had no unspecified refs.

Bugfix in gas pallet

---

lazy-pages/src/unix.rs
runtime/src/lib.rs

forget to remove assert which checks that lazy page cannot be removed twice

fix small bug in lazy pages

---

common/src/lib.rs
core/src/env.rs
core/src/gas.rs
examples/binaries/btree/src/lib.rs
examples/binaries/distributor/src/lib.rs
examples/binaries/node/src/lib.rs
examples/binaries/wait_wake/src/lib.rs
examples/meta/src/lib.rs
examples/token-vendor/src/lib.rs
gear-test/src/address.rs
gear-test/src/js/mod.rs
gear-test/src/sample.rs
gstd/src/common/primitives.rs
pallets/gear-debug/src/lib.rs
pallets/gear-program/src/pause.rs
pallets/gear/src/lib.rs
pallets/usage/src/offchain.rs
runtime/src/lib.rs

The new Rust compiler version introduced new clippy warnings.
- https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
- https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_to_owned
@gear-tech/dev

Address new clippy warnings

---

common/src/lib.rs
runtime/src/lib.rs

Closes #871 
We had runtime upgrade recently, so we could remove outdated clears of `sp_io` storages.

Remove legacy clears

---

Makefile
common/src/lazy_pages.rs
core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/memory.rs
core-backend/wasmtime/src/env.rs
core-backend/wasmtime/src/memory.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core/src/memory.rs
examples/ping-gas/src/lib.rs
pallets/gear/src/ext.rs
runtime/src/lib.rs
scripts/gear.sh
scripts/src/init.sh

fix wasmtime backend:
Later we unprotect pages after memory deallocation (memory move causes memory deallocation and we cannot touch pages after that)
Add dependency from memory in lazy-pages to avoid this types of bugs in future

fix wasmtime backend

---

core-processor/src/handler.rs
examples/binaries/mul-by-const/Cargo.toml
examples/binaries/mul-by-const/src/lib.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs
runtime/src/lib.rs

- Checkouted from #975 so fixes #977 and contains refactored and right calculation in `get_gas_spent`.
- Provided similar to `get_gas_spent` function `get_gas_burned` which adds up only gas which will never returned.
- Cascade test now depend on this functions return values, not on constants.
@gear-tech/dev

Fix get gas spent and update cascade test

---

.gitignore
examples/binaries/init-wait/Cargo.toml
utils/wasm-builder/src/builder_error.rs
utils/wasm-builder/src/crate_info.rs

Resolves #985 
- check `[lib.crate-type]` in `wasm-builder`
-
-

feat(wasm-builder): check crate-type while parsing manifest

---

Cargo.lock
common/src/lazy_pages.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/memory.rs
core-backend/wasmtime/src/memory.rs
core-processor/src/executor.rs
core-processor/src/processor.rs
core/Cargo.toml
core/src/memory.rs
lazy-pages/src/lib.rs
lazy-pages/src/unix.rs
runtime-interface/Cargo.toml
runtime-interface/src/deprecated.rs
runtime-interface/src/lib.rs
runtime/src/lib.rs

1) Solve problem, that if memory size == 0 then wasm executors  can have garbage in pointer to memory buffer.
2) Some refactoring in lazy pages errors

add checks for wasm memory buffer begin addr

---

utils/economic-checks/Cargo.toml
utils/economic-checks/src/targets.rs

Hid writing to files the output of wasm-mutate under a feature. Dy default this won't be happening on CI during pre-commit

Clean up economic-checks unit tests

---

core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/wasmtime/src/env.rs
core-backend/wasmtime/src/funcs.rs
core-processor/src/configs.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core-processor/src/processor.rs
core/src/env.rs
examples/binaries/mul-by-const/src/lib.rs
gear-test/src/proc.rs
gtest/src/manager.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/ext.rs
pallets/gear/src/lib.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs
runtime/src/lib.rs

Finally resolves #587.
- Add functions (aka syscalls) blacklist.
- Generate a trap when trying to call a forbidden function in a program.
- Forbid to call `gr_gas_available` when executing WASM from `get_gas_spent` function.
TODO:
Now it is possible to pass a list of forbidden syscalls when calling the `gear_core_processor::process()` function. If the WASM program contains a call to that forbidden function, the execution will return a correspondent error.
For example when we calculate the amount of gas needed for processing messages in the `get_gas_spent()` function, we forbid calling the `gr_gas_available` syscall in the program. `get_gas_spent()` will return `Program terminated with a trap: Unable to call a forbidden function` error if the program calls `exec:gas_available()` function …

Add list of forbidden syscalls to WASM executor

---

Cargo.lock
examples/binaries/gas-burned/Cargo.toml
examples/binaries/gas-burned/build.rs
examples/binaries/gas-burned/src/lib.rs
gtest/Cargo.toml
gtest/src/lib.rs
gtest/src/log.rs
gtest/src/manager.rs
gtest/src/program.rs

- Add `main_gas_burned` and `others_gas_burned` counters to the `gtest`'s `RunResult`.
- Actual weights for the `wasmtime` backend will be applied in a separate PR.
@gear-tech/dev 
**Release Notes**: ...

Add gas burned counter to `gtest`

---

core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/wasmtime/src/env.rs
core-processor/src/executor.rs
core/src/code.rs
examples/exit-code/src/lib.rs
gtest/src/program.rs
pallets/gear-program/Cargo.toml
pallets/gear-program/src/lib.rs
pallets/gear-program/src/migration.rs
pallets/gear-program/src/tests.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/lib.rs
pallets/usage/src/migration.rs
pallets/usage/src/mock.rs
runtime/src/lib.rs

Store the exports of the wasm module in `gear_core::code::Code` so that they can be reused.
On each execution we deserialize the binary code into a `parity_wasm::Module` which affects the performance in a bad way.
I will perform a storage migration for this change.
@gear-tech/dev

Store module exports in `gear_core::code::Code`

---

gtest/src/program.rs
utils/wasm-builder/src/wasm_project.rs

One should have the possibility to use `.wasm` instead of `.opt.wasm` in `gtest` to be able to test meta functions too.
- `Program::current/current_with_id` now loads `.wasm` binary instead of `.opt.wasm`.
- Added `Program::current_opt/current_opt_with_id` to load `.opt.wasm` binary.
- Updated `gear-wasm-builder` to write the only base path to the `.binpath` file.
@gear-tech/dev

gtest: Add possibility to load both `.wasm` and `.opt.wasm`

---

common/src/lib.rs
pallets/gas/src/lib.rs
pallets/gas/src/tests.rs
runtime/src/lib.rs

feat(gas): introduce `ValueType::ReservedLocal`

---

utils/gear-runtime-test-cli/src/command.rs
utils/gear-runtime-test-cli/src/util.rs

Resolves #1105 .
Do not process the queue if not all fixture messages have been sent.
Now all messages can be sent with the maximum gas_limit.

rtest: Don't process queue if not all messages have been sent

---

utils/wasm-builder/src/cargo_command.rs
utils/wasm-builder/src/lib.rs
utils/wasm-builder/src/wasm_project.rs
utils/wasm-builder/test-program/src/lib.rs

I expect it will reduce build size and compilation time during iterative development (e.g. branch switches, demo changes and so on)

Build WASM projects in their own unified directory

---

pallets/gear/src/tests.rs
pallets/payment/src/lib.rs

Found during working on another task: the test depends on a trap happening when the gas is charged for loading memory pages. Make the trap reason more stable.
@gear-tech/dev

refactor the test unused_gas_released_back_works

---

common/src/lazy_pages.rs
core-backend/common/src/funcs.rs
core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/wasmtime/src/env.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core-processor/src/handler.rs
core/src/env.rs
core/src/memory.rs
pallets/gear/src/ext.rs
runtime/src/lib.rs

In theory, `dyn` usage in affected by this PR code should has runtime overhead, but benchmarks show that this part got optimised by the compiler and there are no performance increase, but code become a bit more canonical. 
@gear-tech/dev

Avoid dynamic dispatching

---

examples/Cargo.lock
examples/Cargo.toml
examples/piggy-bank/Cargo.toml
examples/piggy-bank/src/lib.rs
gtest/src/log.rs
gtest/src/mailbox.rs
gtest/src/manager.rs
gtest/src/program.rs
gtest/src/system.rs

- Added methods to `gtest::Program` and `gtest::System` for adding value and getting balance.
- Fixed value processing in `gtest`.
- Added a `piggy-bank` example to test the value movement.
- Minor refactoring.
Using example: https://github.com/gear-tech/gear/pull/1125/files#diff-ff8da23646ffba628a78b81a75f0ebdf5c1cb5489ad431aee84613408e0ea8a4R505
**Release Notes:** ...
@gear-tech/dev

gtest: Add capability to check actors balances

---

common/src/lib.rs
examples/binaries/calc-hash/over-blocks/src/lib.rs
runtime/src/lib.rs
utils/wasm-builder/src/wasm_project.rs
utils/wasm-builder/test-program/src/lib.rs

The output WASM binary path has been accidentally changed in #1126.
- Reverted the WASM binary path to keep compatibility with building without a build script.
- Minor cleanup.
@gear-tech/dev

Revert previous WASM path in `gear-wasm-builder` + minor cleanup

---

common/src/lazy_pages.rs
common/src/lib.rs
core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
lazy-pages/src/lib.rs
lazy-pages/src/sys.rs
pallets/gear/src/ext.rs
pallets/gear/src/tests.rs
runtime-interface/src/deprecated.rs
runtime-interface/src/lib.rs
runtime-interface/src/tests.rs
runtime/src/lib.rs
scripts/src/test.sh

in order to  optimise lazy pages work - move logic which calc keys for pages in signal handler.
Also completely remove lazy_pages set because it can be very costly to support it when memory size is big
I have run gr_read benchmarks to test perf increase:
```
perf record --all-user --call-graph=dwarf --freq 997 ./target/release/gear-node benchmark pallet --chain=dev --steps=50 --repeat=100 --pallet=pallet_gear --execution=native --extrinsic="gr_read"
``` 
gear_core_processor::executor::prepare_memory  (where lazy pages init info is called) takes
```
master       :    24.9% from all samples
this branch  :    0.01% from all samples
```
time for gr_read:
```
master       :    42.93 µs
this branch  :    32.65 µs
```
time for gr_reply_commit:
```
master       :    68.2 µs
this branch  : …
```

lazy pages optimization

---

gtest/src/log.rs
gtest/src/program.rs

Before was allowed usage of only similar generics (as `id_1` and `id_2`) for `(id_1, id_2, payload) into Log` conversion. Now different types can be used.
New `From` impls appended for `ProgramIdWrapper`.
@gear-tech/dev

Expand `From` implementations for `gtest::Log`

---

gtest/src/mailbox.rs
gtest/src/manager.rs
gtest/src/program.rs
gtest/src/system.rs

By request of @LouiseMedova.
Things to lead gtest closer to real runtime behaviour:
- Panic occurs while trying to mint value less than ED 
- Panic occurs while trying to send value, greater than users balance
- If after sending value your balance is less than ED, it becomes 0
@gear-tech/dev

Value sendings and ED fixes for `gtest`

---

.github/workflows/docs.yml
Makefile
common/src/gas_provider/mod.rs
gcore/src/msg.rs
gstd/codegen/src/lib.rs
gstd/codegen/src/utils.rs
gstd/src/msg/basic.rs
gstd/src/msg/encoded.rs
gtest/src/error.rs

Correct many minor mistakes in docs.
- Fixed broken links.
- Added `make doc` command.
- Make PRs docs be deployed to `https://docs.gear.rs/pr-#/`.
Rendered: https://docs.gear.rs/pr-1186/

Correct most obvious mistakes in docs

---

gtest/src/manager.rs
gtest/src/program.rs

The panic message in the log had been encoded by the SCALE codec. Now it is decoded to be a plain string.
@gear-tech/dev

gtest: Fix panic message decoding in log

---

examples/block-info/src/lib.rs
gear-test/spec_no_runtime/test_block_info.yaml
gtest/src/manager.rs
gtest/src/system.rs
gtest/src/wasm_executor.rs

Sometimes it is needed to get the current block's height and timestamp while debugging `meta_state` function. Now when calling `exec::block_height` and `exec::block_timestamp` functions in `meta_state`, they provide actual data according to the `gtest` runtime.
@gear-tech/dev

gtest: Provide block height and timestamp to `meta_state` function

---

.github/workflows/CI.yaml
Cargo.lock
pallets/gear/Cargo.toml
pallets/gear/src/benchmarking/mod.rs
runtime/src/lib.rs

Resolves #1230.
- Authority and proper block initialisation added into benchmarks.
- Journal processing removed from benchmarks.
- Simple no-op run of benchmarks added to CI.

Add authority into benches

---

.github/workflows/CI.yaml

Resolves #1237 
Don't hardcode paths since GitHub runners images are updated and jobs aren't executed as root anymore - https://github.com/myoung34/docker-github-actions-runner/issues/225
@gear-tech/dev

Set RUSTUP_HOME

---

common/src/gas_provider/internal.rs
runtime/src/lib.rs

Resolves #1212 .
- Makes optional run of `catch_value` procedure depending on the result of the child's run (in `try_remove_consumed_ancestors`).
- Describes all the optimization details in the doc comments.
@gear-tech/dev

Optimize gas nodes consumption

---

Cargo.toml
core-backend/wasmi/src/funcs.rs
docker/Dockerfile
docker/build.sh

`wasmi 0.14.0` API has been changed to match the `wasmtime` style. I think we can switch to this later.
These params speed up execution time of benchmarks by 20-30%.
After this PR, we need to publish our production profile builds and also run them on our nodes.
```
./target/production/gear-node benchmark pallet --chain=dev --steps=50 --repeat=40 --pallet=pallet_gear --execution=wasm --wasm-execution=compiled --heap-pages=4096 --extrinsic="gr_reply_commit"
100.9 µs
./target/release/gear-node benchmark pallet --chain=dev --steps=50 --repeat=40 --pallet=pallet_gear --execution=wasm --wasm-execution=compiled --heap-pages=4096 --extrinsic="gr_reply_commit"
163.9 µs
```
Create production profile:
```
[profile.production]
inherits = "release"
lto = "fat"
codegen-units = 1
```
See …

production profile w\ fat lto

---

gcore/src/msg.rs
pallets/gear/src/benchmarking/code.rs
pallets/gear/src/benchmarking/mod.rs
runtime/src/lib.rs

Resolves #1244 
- add optional reply_body field to ModuleDefinition
- fix gr_exit_code & gr_reply_to benchmarks by calling the function in `handle_reply`
- fix docs for `gr_exit_code`
@gear-tech/dev

Add feature to generate `handle_reply` in bechmarks generator

---

docker/Dockerfile

This reverts commit a4ddad081b191aeedf5ac51aa22c0cb6ed702e6f.

[skip ci] Revert "Deploy node binary with `runtime-benchmaks`"

---

Makefile
examples/wat-examples/read_access.wat
examples/wat-examples/read_write_access.wat
gear-test/src/check.rs
gear-test/src/proc.rs
gear-test/src/sample.rs
gear-test/wat-spec/read_access.yaml
gear-test/wat-spec/read_write_access.yaml
runtime/src/lib.rs
scripts/gear.sh
scripts/src/build.sh
utils/gear-runtime-test-cli/src/command.rs

1) Add read access and r/w access wat examples.
2) Allow to skip `expected` and `messages` fields in fixtures.
3) A little refactoring in gear-test

add wat examples and specs to run them

---

Cargo.lock

update wasmtime to version `0.39.1`  in substrate sc-executor, in order to be able avoid `sse4.1(2)` mistakes on CPU without this  sse versions support.

update wasmtime to version 0.39.1 

---

utils/wasm-builder/src/cargo_command.rs

May help in case of regressions (for example, rust-lang/rustup#3036)

Run nightly cargo through rustup in WASM builder

---

Cargo.lock
README.md
common/src/lazy_pages.rs
common/src/lib.rs
core-processor/src/executor.rs
core/src/memory.rs
lazy-pages/Cargo.toml
lazy-pages/src/deprecated.rs
lazy-pages/src/lib.rs
lazy-pages/src/sys.rs
lazy-pages/src/sys/unix.rs
lazy-pages/src/sys/windows.rs
pallets/gear-debug/Cargo.toml
pallets/gear-debug/src/tests.rs
pallets/gear/Cargo.toml
pallets/gear/src/ext.rs
pallets/gear/src/tests.rs
runtime-interface/src/deprecated.rs
runtime-interface/src/lib.rs
runtime-interface/src/tests.rs

Resolves #1123
1) In lazy pages mode we upload page data to the storage in case it has been `write` accessed. Old logic is to compare pages data before and after execution and upload data if it has been changed. So, now in lazy pages mode comparing is removed. In executor I leave logic with comparing in case we works without lazy-pages: gtest/gear-test.
Removing pages comparing brings some performance changes. I've measured how execution time for function `gear_core_processor::execute_wasm` is changed for wat examples:
```
read_access.wat T(master)/T(patch) = 1.63
read_write_access.wat T(master)/T(patch) = 1
```
As you can see `read_write` access has no performance changes - this is because we must handle signal twice: one for read and second for write. This lead to 3 times more …

remove pages compare after execution

---

common/src/lazy_pages.rs
core-backend/common/src/lib.rs
core-backend/common/src/utils.rs
core-backend/sandbox/src/env.rs
core-backend/wasmi/src/env.rs
core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core/src/ids.rs
gear-test/src/check.rs
lazy-pages/src/lib.rs
lazy-pages/src/sys.rs
pallets/gear-debug/src/tests.rs
pallets/gear/src/ext.rs
pallets/gear/src/tests.rs
runtime-interface/src/deprecated.rs
runtime-interface/src/lib.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Resolves #1253.
- Now virtual stack pages will be skipped in lazy pages: they won't be protected and handled as lazy.

add stack pages support for lazy pages in runtime

---

Cargo.lock
node/cli/Cargo.toml
node/cli/src/benchmarking.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Apparently, one of the recent upgrades of Substrate has led to these changes having been reverted so that the default `pallet_transaction_payment` was used to calculate fees. Restoring our custom way of modifying fees that was introduced together with the `gear-payment` pallet

Restore custom transaction fees

---

node/cli/src/benchmarking.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

In stage 1 in `Vara` network balance transfers (or, for that matter, any manipulations with balances) are prohibited.
We create an additional signed extension, whose `validate` function checks if the call is one of the extrinsics from `pallet_balances`. If so, the call is rejected.

Prohibit calling extrinsics from Balances pallet in Vara PoA network

---

lazy-pages/src/lib.rs
lazy-pages/src/sys.rs
runtime-interface/src/lib.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs
scripts/check-spec.sh

See issue #1317 
Run test net sync for mac and for linux, all goes OK.
Removes `lazy-pages` from list of crates to update runtime spec version, because lazy-pages crate code is restricted to be in runtime.

fix wrong block panic in node

---

node/cli/src/benchmarking.rs
pallets/gear/src/lib.rs
runtime/vara/src/lib.rs

Reverts [this commit](https://github.com/gear-tech/gear/commit/c40e76860fd0c2515c78f2adade3081c1a85e437) and expands our custom signed extension in order to use the unified mechanic of denying calling extrinsics, that cause balances, instead of somewhere invalidate extrinsics, somewhere return errors.

Deny calls with value for `vara-stage-1`

---

Cargo.lock
runtime/common/src/apis.rs
utils/economic-checks/Cargo.toml

This will allow unpinning rust compiler version

Bump wasm-mutate version to 0.2.7

---

core-processor/src/ext.rs
core/src/env.rs
examples/wat-examples/read_write_access.wat
pallets/gear/src/ext.rs
pallets/gear/src/tests.rs

Found a bug, which is caused by `u32` saturating when makes `saturating_mul`, which cause very cheap big number of pages allocation.

fix bug gas charge for allocated pages

---

.github/workflows/CI.yaml
Cargo.lock
utils/wasm-proc/Cargo.toml
utils/wasm-proc/src/main.rs

- Added to `wasm-proc` a functionality for checking runtime imports against the whitelist.
- Added a correspondent stage to CI.
@gear-tech/dev

Check runtime WASM imports for being allowed

---

core-processor/src/processor.rs
core/src/message/common.rs
core/src/message/incoming.rs
core/src/message/stored.rs
pallets/gear/src/internal.rs
pallets/gear/src/tests.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

There is no need to store error replies in mailbox, so this PR removed this possibility.

Correct error replies lifecycle

---

core/src/ids.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

- Excluded possibility to fail formatting, except `write!` result
- Precision works with both sides at the same time
- Added alternate `:#` formatter
For details, see test:
https://github.com/gear-tech/gear/blob/5f47966c6624ae72e3102e3dddab11992da0490f/core/src/ids.rs#L219-L242

Make formatters smarter

---

.github/workflows/CI.yaml
core-processor/src/executor.rs
examples/wat-examples/wrong_load.wat
lazy-pages/src/sys/unix.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs
scripts/src/test.sh
scripts/test-utils/processingMessageWithRuntimeUpgrade.js

`wasmer` uses signals to identify wrong memory operation that try to access memory outside of memory bounds. To support it we call old sighandler (which has been set before we set our sig handler for lazy pages) if signal came from unknown address.
Without patch node will panic in the case contract would like to access wrong memory. 
This patch do not fix problem for `windows` OS. #1377 
Add also small test which checks that node does not panic in the case. Currently add it inside `runtime-update` test. #1378

fix signal handler for `wasmer`

---

core-backend/sandbox/src/funcs.rs
core-backend/sandbox/src/runtime.rs
core-backend/wasmi/src/funcs.rs
core-backend/wasmi/src/runtime.rs
core-errors/src/lib.rs
core-processor/src/ext.rs
core/src/env.rs
pallets/gear/src/ext.rs
pallets/gear/src/weights.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Resolves #1359.
Also fixed bug, that we were allocating vector and copying elements every time we call `gr_read` (line 316):
https://github.com/gear-tech/gear/blob/d51697ce38daadf85942f1d11d8a9c95670f62f1/core-backend/sandbox/src/funcs.rs#L315-L326
Benchmark result of fixing mentioned above bug:
`gr_read_per_kb: 30_106_000 -> 15_007_000`
Resolving initial feature a bit increased `gr_read` + `gr_size` but its like 2-5%

Bugfix: `gr_read`, `gr_size` economic and memory

---

pallets/gear/src/benchmarking/mod.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Resolves #1402 
- make explicit imports in benchmakring/mod.rs
- use corresponding externalities for core_processor
@gear-tech/dev

Make pallet gear benchmarking able to run without lazy-pages

---

lazy-pages/src/lib.rs

Use volatile operations in read-write flag test 

---

Cargo.lock
lazy-pages/Cargo.toml
lazy-pages/src/lib.rs
lazy-pages/src/sys.rs
lazy-pages/src/sys/unix.rs
lazy-pages/src/sys/windows.rs

Rust on linux allocates only 0x2000 bytes for signal alternative stack (equal to libc::SIGSTKSZ). This is not enough for debug build, because in debug code use too much of stack. So, we create our own alternative signal stack if existed stack is not big enough for lazy pages signal handler (suppose that signal stack size for macos M1 0x20000 is big enough).

make big signal alt stack to be able run lazy pages in debug mode

---

Cargo.lock
gear-test/src/check.rs
utils/node-loader/Cargo.toml
utils/node-loader/src/args.rs
utils/node-loader/src/main.rs
utils/node-loader/src/reporter.rs
utils/node-loader/src/task.rs
utils/node-loader/src/task/generators.rs
utils/node-loader/src/task/upload_program.rs
utils/node-loader/src/utils.rs

Resolves #1502 .
- Separate models and logic into corresponding types and modules
- Implement in-memory logger which avoids logs jumbling

Refactor `node-loader` to make it ready for multiple tasks

---

core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/wasmi/src/env.rs
core-backend/wasmi/src/funcs.rs
core-processor/src/ext.rs
core/src/costs.rs
core/src/env.rs
examples/Cargo.lock
examples/binaries/waiter/src/code.rs
examples/binaries/waiter/src/lib.rs
examples/light_sr25519/Cargo.toml
gcore/src/exec.rs
gstd/src/async_runtime/futures.rs
gstd/src/exec.rs
gstd/src/msg/async.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/ext.rs
pallets/gear/src/schedule.rs
pallets/gear/src/tests.rs
pallets/gear/src/weights.rs
runtime/gear/src/lib.rs
runtime/gear/src/weights/pallet_gear.rs
runtime/vara/src/lib.rs
runtime/vara/src/weights/pallet_gear.rs
utils/regression-analysis/src/main.rs
utils/wasm-proc/metadata-js/index.js

Part of #1528.
- Removed deprecated `gstd::send_and_wait_for_reply` and `gstd::send_bytes_and_wait_for_reply`.
- Renamed `wait_no_more` (I know it is an allusion to "Faith No More" but ...) to `wait_up_to`.
@gear-tech/dev

Remove deprecated functions from `gstd` and rename syscall

---

core-backend/sandbox/Cargo.toml
core-backend/sandbox/src/funcs.rs
core-backend/sandbox/src/runtime.rs
core/src/code.rs
core/src/lib.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

1) Add restriction for max allocation in gear runtime, currently check it only in gear_backend_sandbox.
2) Add tracing of sys-calls. To avoid performance decrease  disable them using log feature: max_level_debug

fix panic on big allocations in wasm runtime

---

.github/workflows/test-measurements.yaml

I forgot we use `cargo nextest` (not `cargo test`) in test measurements so flags were correct

Revert "Run perf check tests in 1 thread (#1509)"

---

runtime/common/src/lib.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

It turned out, that with increase of block production time by twice, block gas limit and weight at all hasn't changed.
This PR fixes this bug defining ration between MILLISECONDS_PER_BLOCK and BlockWeights & BlockGasLimit
ATTENTION: Such changes may be not allowed for runtime upgrade, so we need to restart vara network.

Add block weight dependency from block time

---

core/src/message/mod.rs
gclient/src/api/listener/mod.rs
program/scripts/generate-api.sh
program/src/api/generated/metadata.rs
program/src/api/generated/mod.rs
program/src/cmd/info.rs
program/tests/cmd/reply.rs
program/tests/cmd/send.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

No update occurred after merging #1587 , which caused some problems in `gear-node-loader`

Update metadata after introducing `LimitedVec`

---

examples/Cargo.lock
examples/async-init/Cargo.toml
examples/async-init/src/lib.rs
examples/async-multisig/Cargo.toml
examples/async/Cargo.toml
gstd/src/lib.rs
gstd/src/prelude.rs

Use reexported `scale_info` and `parity-scale-codec` from `gstd`

---

pallets/gear/src/lib.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

before:
```sh
runtime::gear: ⚙️Initialization of block #1
runtime::gear: ⚙️Queue and tasks processing of block #1 with weight='<wasm:stripped>'
runtime::gear: ⚙️Weight '<wasm:stripped>' burned in block #1
runtime::gear: ⚙️Finalization of block #1
```
after:
```sh
runtime::gear: ⚙️ Initialization of block #1
runtime::gear: ⚙️ Queue and tasks processing of block #1 with Weight(ref_time: 327333086333)
runtime::gear: ⚙️ Weight(ref_time: 25000000) burned in block #1
runtime::gear: ⚙️ Finalization of block #1
```

beautify runtime logs

---

core-backend/sandbox/Cargo.toml
core-backend/sandbox/src/funcs.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Using feature = max_level_debug for log dep cause that trace logs disables in all runtime. So, made a macros which enables tracing in sys-calls when self made feature is set.

make macros to print sys-calls

---

Cargo.lock
core-backend/wasmi/Cargo.toml
pallets/gear/Cargo.toml
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/lib.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Resolves #1604 
- Enable the backend instead of sp-sandbox embedded executor which is also a wrapper around wasmi. This step allows us to update wasmi independently later.
@gear-tech/dev

Use wasmi backend for std builds of pallet gear

---

common/lazy-pages/src/lib.rs
core-backend/sandbox/src/memory.rs
core-backend/wasmi/src/memory.rs
core-errors/src/lib.rs
core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core/src/memory.rs
pallets/gear/src/ext.rs
pallets/gear/src/tests.rs
program/src/api/generated/metadata.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Resolves #1390  #1395 #1391.
remove lazy pages errors
improve lazy pages handling in allocation
reuse alloc and into_ext_info in both externalities struct

lazy pages runtime refactoring

---

.github/workflows/docs.yml
Makefile
README.md
core/src/message/common.rs
gstd/src/msg/encoded.rs
pallets/gear/rpc/src/lib.rs
pallets/gear/src/manager/mod.rs

- Added to https://docs.gear.rs: `gclient`, `pallet-gear`, `pallet-gear-gas`, `pallet-gear-messenger`, `pallet-gear-payment`, `pallet-gear-program`, `pallet-gear-rpc`, `pallet-gear-scheduler`.
- Fixed links from `builds.gear.rs` to `get.gear.rs` in `README.md`.
- Fixed links in doc-comments.
Rendered: https://docs.gear.rs/pr-1636/
@gear-tech/dev

Add pallets to docs and fix links

---

.github/workflows/CI.yaml
Makefile
examples/gui-test/src/lib.rs
gear-test/spec/test_gui.yaml
node/cli/Cargo.toml
program/src/api/generated/metadata.rs
scripts/test-utils/package-lock.json

- Remove superfluous "cli" feature from `gear-cli` crate which is always on anyway - building the node without it doesn't make much sense.
- Fix failing rtest on vara by making sure the value passed to and from a program would surpass the existential deposit.

Remove redundant feature

---

Cargo.lock
core-backend/common/Cargo.toml
core-backend/common/src/utils.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Partially #1496 .
Crate mostly consists of traits and type definitions without clear view on their usage.
@gear-tech/dev

Test `core-backend/common` crate

---

Cargo.lock
core-backend/common/src/mock.rs
core-backend/sandbox/Cargo.toml
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/sandbox/src/runtime.rs
core-backend/wasmi/Cargo.toml
core-backend/wasmi/src/env.rs
core-backend/wasmi/src/funcs/internal.rs
core-backend/wasmi/src/funcs/mod.rs
core-backend/wasmi/src/funcs_tree.rs
core-processor/src/ext.rs
core/src/code.rs
core/src/env.rs
core/src/gas.rs
gtest/src/error.rs
gtest/src/manager.rs
gtest/src/wasm_executor.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/ext.rs
pallets/gear/src/lib.rs
pallets/gear/src/tests.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs
utils/wasm-gen/src/syscalls.rs
utils/wasm-proc/src/main.rs

Resolves #1468 
Blocked by #1689 , https://github.com/gear-tech/substrate/pull/23
- refactor syscalls `create_program*` in wasmi backend
- fix regression in `exit` syscall for wasmi backend
- extend `Ext` trait: getters/setters for counters, `out_of_...` methods
- remove old `gas` handler
- use new injection method
- add `ext_sandbox_set_global_val_version_1` to the list of allowed imports in `wasm-proc`
- adjust other source code base to the changes
**Release notes**: Previous implementation of gas metering calls into the supervisor for every basic block in order to report some consumption from the gas meter. This is slow because calling imported functions is a heavy operation.
This PR contains implementation of gas metering in programs' userspace for both wasmer and wasmi execution …

Implement gas counting without system call

---

common/src/lib.rs
pallets/gear-debug/src/mock.rs
pallets/gear-scheduler/src/mock.rs
pallets/gear-scheduler/src/tests.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs
pallets/payment/src/mock.rs
program/tests/cmd/claim.rs
runtime/common/src/lib.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs
utils/gear-runtime-test-cli/src/util.rs

Resolves #1511.
That's temporary solution, written in most efficient and easy way for the moment.
Should be replaced with more complicated one in order to support changing gas price multiplicator with runtime upgrade in future.

Set proper gas to value conversion

---

gcore/src/lib.rs
gcore/src/utils.rs
gstd/src/common/handlers.rs
gstd/src/lib.rs
gstd/src/macros/bail.rs
gstd/src/macros/debug.rs
utils/wasm-builder/src/crate_info.rs
utils/wasm-builder/src/wasm_project.rs

- Resolves #1739
- Enable `debug!/bail!` macros automatically for the debug profile and disable them for the release profile.
- Propagate features from smart contracts.
@gear-tech/dev
1. If you use `gstd` in the program with no any feature.
```toml
gstd = { git = "https://github.com/gear-tech/gear.git" }
```
`debug!/bail!` macros will work in the debug build profile and will be replaced by blanks on the release build profile.
```shell
cargo build # `debug!` will show the debug message
cargo build --release # `debug!` will do nothing
```
2. If you add a debug feature to the program.
```toml
gstd = { git = "https://github.com/gear-tech/gear.git" }
[features]
debug = ["gstd/debug"]
```
`debug!/bail!` macros will work in release profiles if you add the `debug` feature during the build. …

gstd: Enable `debug` feature only for debug profile or propagate it from contract features

---

Cargo.lock
node/cli/Cargo.toml
pallets/gear/src/benchmarking/code.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/benchmarking/syscalls.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs
utils/wasm-gen/Cargo.toml
utils/wasm-gen/src/syscalls.rs
utils/wasm-instrument/Cargo.toml
utils/wasm-instrument/src/lib.rs
utils/wasm-instrument/src/syscalls.rs
utils/wasm-instrument/src/tests.rs

Resolves #1726 .
1) Move syscalls table to `gear-wasm-instruments` in order to use it both in `gear-wasm-gen` and in `runtime-benchmarks`.
2) Make very simple refactoring in syscalls benches and wasm-gen syscalls, in order to simplify code.

add syscalls table in gear-wasm-instruments

---

node/README.md

```
error: failed to run custom build command for sc-network-sync v0.10.0-dev (https://github.com/gear-tech/substrate.git?branch+gear-stable#988411fe)
```
```
$ apt install -y protobuf-compiler
$ protoc --version
```
>## Ensure compiler version is 3+

Update README (add  Protocol Buffer Compiler)

---

gclient/src/api/listener/iterator.rs
program/src/api/events.rs
program/src/api/mod.rs
program/src/api/signer/calls.rs
utils/node-loader/Cargo.toml
utils/node-loader/src/batch_pool.rs
utils/node-loader/src/utils.rs

Off-chain applications are unaware of forks, so they need a better block headers handling. That's because getting events of some block by, say, block header (as a key) can be a fallible action due to state of the block with that block hash being discarded. Solution here can be getting only finalized blocks and reading data from them.
That's the purpose of that fix - subscribe on finalized blocks only,
@gear-tech/dev

Fix events handling

---

utils/node-loader/src/batch_pool.rs
utils/node-loader/src/batch_pool/api/mod.rs
utils/node-loader/src/batch_pool/report.rs
utils/node-loader/src/utils.rs

On blocks reorg loader can stop if extrinsics were newly submitted to the discarded block. In this case we will wait for 512 blocks (see: https://github.com/paritytech/subxt/blob/33a9ec91afd16c459871e24ae18576f7afbb87c1/subxt/src/tx/tx_progress.rs#L266-L268) until task with processing tx status yields  `FinalityTimeout`.
This PR fixes `gear-node-loader`'s crashes in such situations.

Fix tx-status waiting

---

gclient/tests/upload.rs
utils/test-runtime/Cargo.toml
utils/test-runtime/src/lib.rs

- Fix tests in one of the dependencies (test-runtime);
- Add test of the newly added gear `runtime-api` call.

Add features to fix tests in a dependency

---

node/cli/Cargo.toml
pallets/gear/src/benchmarking/code.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/benchmarking/syscalls.rs
pallets/gear/src/weights.rs
runtime/gear/src/lib.rs
runtime/gear/src/weights/pallet_gear.rs
runtime/vara/src/lib.rs
runtime/vara/src/weights/pallet_gear.rs

Resolves #1728.
Make random access overall 512 wasm pages memory. Which makes load and stores much more expensive, because of L1 and L2 caches misses (see also #1817 ). To reduce `lazy mmap` factor, make all memory pages access before.
Add also `lazy-pages` read/write access benchmarks and weights for future using.

tune load and store weights

---

node/cli/src/command.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Resolves #1776
- Rename the `gear-node` base directory to `gear` if the first exists and the latter doesn't.
- Default base directory now depends on the executable name as it was before the executable binary renaming.
@gear-tech/dev

Rename `gear-node` base dir to `gear` instead of changing base path

---

examples/binaries/meta/src/lib.rs
program/tests/cmd/program.rs

test(program): test program state with real types

---

utils/wasm-builder/src/wasm_project.rs

Fixes this https://github.com/gear-tech/gear/actions/runs/3592342346/jobs/6047937784
Test with `cargo build -p gear-cli --profile production`

Add production profile to demos built with `wasm-builder`

---

scripts/src/clippy.sh

Resolves #1956 
@gear-tech/dev

chore(clippy): remove `-A clippy::uninlined-format-args` in scripts

---

gclient/src/api/calls.rs
gclient/src/api/mod.rs
gclient/src/api/storage/mod.rs

- Part of #1962
- `get_from_mailbox` method has been split into `get_from_mailbox` (to get the message from the tester's mailbox) and `get_from_account_mailbox`(to get the message from any other account mailbox).
- Added the `GearApi::account_id` method to get the signer's address.
@gear-tech/dev

gclient: Split mailbox getters and add `account_id` method

---

gclient/src/api/error.rs
gclient/src/api/storage/block.rs

- Part of #1962 
- Added `last_block_timestamp` function to API that returns timestamp in milliseconds since Unix epoch.
@gear-tech/dev

gclient: Add `last_block_timestamp` function to API

---

utils/wasm-gen/src/lib.rs
utils/wasm-gen/src/test.rs

Resolves #2050 
Add gear stack end to wasm-gen to test all cases depending on this
~1% of cases with invalid stack size not a multiple of the page size
~1% of cases with invalid stack size that is bigger than import memory
~1% of cases stack size is not generated at all
all other cases should be valid

Implement Gear stack end in `wasm-gen`

---

Cargo.lock
gclient/Cargo.toml
gclient/src/api/error.rs
gclient/src/api/rpc.rs
gclient/src/api/storage/block.rs
gclient/tests/state.rs

- Part of #1962
- Added wrappers around three RPC calls: `gear_readState`, `gear_readStateUsingWasm`, `gear_readStateUsingWasm` 
@gear-tech/dev

gclient: Add functions for state reading

---

Cargo.lock
gclient/Cargo.toml
program/Cargo.toml
program/src/api/client.rs
program/src/metadata/funcs.rs
utils/node-loader/src/utils.rs

Latest crashes have errors that can't be investigated without the newest `subxt` version.

Bump subxt to a version with rpc errors being displayed

---

gclient/src/api/listener/iterator.rs
gclient/src/api/storage/block.rs
gclient/tests/keyhasher.rs
gclient/tests/loop.rs
gclient/tests/upload.rs
node/authorship/src/authorship.rs
node/service/src/chain_spec/gear.rs
node/service/src/chain_spec/vara.rs
pallets/gear-debug/src/mock.rs
pallets/gear-scheduler/src/mock.rs
pallets/gear/rpc/runtime-api/src/lib.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/benchmarking/tests/utils.rs
pallets/gear/src/lib.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs
pallets/payment/src/mock.rs
utils/test-runtime/client/src/block_builder_ext.rs
utils/test-runtime/client/src/trait_tests.rs
utils/test-runtime/src/inner.rs
utils/test-runtime/src/lib.rs

Resolves the issue with a flaky machinery of deciding wether the message queue should be processed in the end of each block depending on the outcome of previous runs.
The old mechanism relied on the inherent-like extrinsic signalling a successful completion of the message queue processing by setting some storage value to a specific status. If not set, this was deemed as a panic having occurred during one of the previous runs so that a new attempt wouldn't (by default) take place. This creates an attack vector of a malicious validator opting for deliberately not including this inherent into a block thereby blocking the queue processing in all the blocks thereafter, until the issue would have been investigated and fixed via a runtime upgrade which would render the network useless in the …

Rework block authorship

---

Cargo.lock
Cargo.toml
core-backend/common/src/lib.rs
core-backend/common/src/memory.rs
core-backend/sandbox/src/funcs.rs
core-backend/sandbox/src/runtime.rs
core-backend/wasmi/src/funcs/internal.rs
core-backend/wasmi/src/funcs/mod.rs
examples/binaries/backend-error/Cargo.toml
examples/binaries/backend-error/build.rs
examples/binaries/backend-error/src/lib.rs
gclient/Cargo.toml
gclient/tests/backend.rs
gsys/src/lib.rs
pallets/gear/Cargo.toml
pallets/gear/src/tests.rs

For example let's take fallible `gr_unreserve_gas` syscall.
https://github.com/gear-tech/gear/blob/9d96bec693b34db229598d0e638502228dc1a43d/core-backend/sandbox/src/funcs.rs#L856-L871
For case if we failed to read read reservation id, atm we are leaving backend with wasm trap, while it should try write ext error about incorrect `reservation_id_ptr` to `write_err_unreserved`, because syscall supposed to be fallible and dance around results.
For case when fails write to `err_<something>` ptr, we already cannot parse error in user space so we should leave with a trap.

Fix backend errors handling for fallible syscalls

---

Cargo.lock
utils/wasm-gen/Cargo.toml
utils/wasm-gen/src/lib.rs
utils/wasm-gen/src/tests.rs
utils/wasm-gen/src/utils.rs

Resolves #2170.
Bug was basically with using `HashMap`/`HashSet` as during the iteration these types do not give guarantee on the order, so for the same input seed we will receive different iteration order of the same data.

Fix fuzzing tests being non-reproducible

---

utils/wasm-builder/src/cargo_command.rs
utils/wasm-builder/src/lib.rs
utils/wasm-builder/src/wasm_project.rs
utils/wasm-builder/test-program/.gitignore
utils/wasm-builder/test-program/build.rs
utils/wasm-builder/tests/smoke.rs

This reverts commit e772a04bcf12e7c6b06148680e7cc674dfd66037.

Revert "Take `SKIP_WASM_BUILD` env var into account (#2179)"

---

gsdk/src/metadata/impls.rs
gsdk/src/signer/calls.rs
utils/node-loader/Cargo.toml
utils/node-loader/src/batch_pool.rs

Balance update task on loader was failing due to invalid encoding of the dynamic tx. Fixed that by introducing conversion to `scale_value::Value` for related runtime calls.

Fix sudo call encoding

---

pallets/staking-rewards/src/mock.rs
pallets/staking-rewards/src/tests.rs
runtime/vara/src/lib.rs

Since `Treasury` is not yet being used on Vara, stashing funds on its account is useless. This change can be reverted any time when having a Treasury starts making sense.

Burn rewards minted in excess instead of sending them to Treasury

---

gcli/scripts/update-readme.sh
gcli/src/metadata/result.rs
gcli/src/result.rs
gcli/tests/common/result.rs
gclient/src/node/result.rs
gclient/tests/node.rs
gsdk/src/result.rs
gstd/src/common/errors.rs
utils/validator-checks/src/result.rs

- Fixed custom `Result` type aliases that allow using one `Result` type with both custom error and default one.
- Fixed some typos.
This PR allows avoiding such types of two `Result`s using:
https://github.com/gear-dapps/app/blob/master/src/contract.rs#L4

Fix `Result` aliases and typos

---

gstd/src/async_runtime/futures.rs
gstd/src/async_runtime/locks.rs
gstd/src/async_runtime/mod.rs
gstd/src/lib.rs

without this patch locks map will grows forever for any contract with asyncs 
Change internal map for locks back to BTreeMap, because I think is more probably, that internal map for messages is small, so it's more effective to use BTreeMap than HashMap for small data

prune locks map in gstd

---

scripts/src/test.sh
utils/runtime-fuzzer/src/lib.rs

1. Removing `call_indirect` gives us less congestion due to undesired recursions. So it increases the speed.
2. Introducing `rss_limit_mb` gives fuzzer more RAM for storing all the needed data for fuzzing, i.e. increases fuzzing duration.

Increase `runtime-fuzzer` performance

---

Cargo.lock
utils/runtime-fuzzer/fuzz/Cargo.toml
utils/runtime-fuzzer/fuzz/fuzz_targets/main.rs
utils/runtime-fuzzer/src/bin/reproduce_fuzz.rs

There was a demand for putting seeds file into the separate dir to make it easy to mount that dir to host machine from docker.

Simplify fuzzer crash reproducing

---

gclient/src/api/calls.rs

`gclient` returns error on a legit case, when zero value is transferred.

Fix zero value send handling

---

gclient/src/api/error.rs
gclient/src/api/mod.rs
gclient/src/lib.rs
gclient/src/node/mod.rs
gclient/tests/backend.rs
gclient/tests/keyhasher.rs
gclient/tests/loop.rs
gclient/tests/node.rs
gclient/tests/perf.rs
gclient/tests/state.rs
gclient/tests/upload.rs

Resolves #2397  .
`Node` has been moved insied `GearApi` as an option

[gclient] Get rid of GearApiWithNode

---

Cargo.lock
runtime/vara/Cargo.toml
runtime/vara/src/integration_tests.rs
runtime/vara/src/lib.rs

Added some integration tests to Vara runtime crate ("integration" in terms of the tests transcending scopes of individual pallets). This current edition includes tests of:
- signed extension to filter balances transfers in stage 1;
- integrity of tokens locking machinery in context of Gear specific calls, specifically to state that locked tokens can't be passed to programs in messages.
More intricate test cases can (and should) be added for bullet-proof guarantees of this mechanism.

Add tokens locking integrity tests to vara runtime

---

Cargo.lock
runtime/vara/Cargo.toml
runtime/vara/src/governance/fellowship.rs
runtime/vara/src/governance/origins.rs

Fellowship members can have their rank as origin now (`Fellowship1Dan`, `Fellowship2Dan`, `Fellowship3Dan` .. up to 9 Dan).
To add a new member or promote existing submit proposal with origin FellowshipDan with the rank above the new rank.
For example new members rank would be 0 - submit proposal with `1 / Candidates / Origin / Fellowship1Dan` Origin.
To promote user from 1 to 2 rank - submit proposal with `3 / Fellows / Origin / Fellowship3Dan` Origin.
To demote user proposal origin should be 2 rank above the current rank.
@gear-tech/dev

[vara] Make the fellowship self-governed collective

---

core-backend/sandbox/src/memory.rs
core-backend/wasmi/src/memory.rs
core-processor/src/ext.rs
core/src/memory.rs

Make `Memory::grow` unreachable

---

gmeta/codegen/src/lib.rs

- Fixed a deprecation warning due to the update `scale-info` to v2.5 in `gmeta`
```
error: use of deprecated method `gstd::scale_info::interner::UntrackedSymbol::<T>::id`: Prefer to access the fields directly; this getter will be removed in the next major version
--> state/src/lib.rs:10:1
|
10 | #[metawasm]
| ^^^^^^^^^^^
|
= note: `-D deprecated` implied by `-D warnings`
= note: this error originates in the attribute macro `metawasm` (in Nightly builds, run with -Z macro-backtrace for more info)
```
@gear-tech/dev

gmeta: Fix deprecation warning when using `metawasm` attribute

---

docker/runtime-fuzzer/Dockerfile
utils/runtime-fuzzer/src/lib.rs

After each run the events store grows bigger, so iterating on it becomes very expensive. Optimize that by removing events after processing them.

Increase fuzzer performance

---

.github/workflows/CI.yaml

Resolves #2341.
- check compact WASMs for both runtimes Gear & Vara

ci: Add check for runtime imports to CI

---

Cargo.lock
Cargo.toml
node/authorship/Cargo.toml
utils/wasm-builder/test-program/Cargo.toml
utils/wasm-builder/test-program/src/lib.rs

- Changed substrate source on branch with patched `wasmi` crate
- Moved `gear-authorship` dep into unified `Cargo.toml`
- Added `gclient` compilation test into `utils/wasm-builder/test-program` as for external dependency

Change source branch of substrate and add compilation test

---

Cargo.lock
utils/node-loader/Cargo.toml
utils/node-loader/src/args.rs
utils/runtime-fuzzer/Cargo.toml
utils/runtime-fuzzer/src/bin/reproduce_fuzz.rs
utils/wasm-info/Cargo.toml
utils/wasm-info/src/main.rs

Resolves #2442.
Changes made due to the transition:
- In `wasm-info`, the shorthand for `--hex` has been changed to `-H` from `-h`. This has been done because it conflicts with the shorthand for help in current version of clap. Another option is to disable both `--help` and `-h`, but this requires further discussion.
Rework of PR #2510

feat(utils): switch to `clap` arg parser instead of `structopt`

---

common/src/lib.rs
pallets/airdrop/src/weights.rs
pallets/gear-debug/src/mock.rs
pallets/gear-debug/src/weights.rs
pallets/gear-scheduler/src/mock.rs
pallets/gear/src/benchmarking/tests/utils.rs
pallets/gear/src/lib.rs
pallets/gear/src/mock.rs
pallets/gear/src/schedule.rs
pallets/gear/src/weights.rs
pallets/payment/src/lib.rs
pallets/payment/src/tests.rs
pallets/staking-rewards/src/weights.rs
runtime/gear/src/weights/frame_system.rs
runtime/gear/src/weights/mod.rs
runtime/gear/src/weights/pallet_gear.rs
runtime/gear/src/weights/pallet_timestamp.rs
runtime/gear/src/weights/pallet_utility.rs
runtime/vara/src/weights/frame_system.rs
runtime/vara/src/weights/mod.rs
runtime/vara/src/weights/pallet_gear.rs
runtime/vara/src/weights/pallet_timestamp.rs
runtime/vara/src/weights/pallet_utility.rs

Resolves #2531
Changes:
- `Weight::from_ref_time(ref_time)` -> `Weight::from_parts(ref_time, 0)` 
- `Weight::from_proof_size(proof_size)` -> `Weight::from_parts(0, proof_size)`
- removed `#![allow(deprecated)]`

Migrate to `Weight::from_parts` (closes #2531)

---

Cargo.lock
Cargo.toml
node/service/src/chain_spec/gear.rs
node/service/src/chain_spec/vara.rs
node/testing/src/genesis.rs
runtime/gear/Cargo.toml
runtime/gear/src/lib.rs
runtime/gear/src/migrations.rs
runtime/vara/Cargo.toml
runtime/vara/src/lib.rs
runtime/vara/src/migrations.rs

Adds the ability to add/remove validators to `pallet_session`.
~~Cannot be used with new network because pallet id comes after pallet_session. So no `local` and `dev` etc.
Session can't be initialized -`Empty validator set for session 0 in genesis block.`~~
fixed in https://github.com/gear-tech/substrate-validator-set/commit/fc0fbd5bb8b3af40fe078b26097fe7f1186f7daf (Fallback to Session if empty validators list)

Use `validator_set` pallet to manage authorities.

---

.github/workflows/CI.yaml

ref #2322
exuection failed by network or temp env is acceptable for command line tools tbh...bcz those are uncertain stuffs, testing if all commands still work after updating is the goal for testing them in CI, so go retrying the failed tests first but not hack or force them to pass
@gear-tech/dev

ci(gcli): add retries for tests

---

examples/binaries/reserve-gas/src/lib.rs
gclient/tests/upload.rs
node/service/src/lib.rs
pallets/gear/src/tests.rs

Resolves # .
Slower grandpa finality to reduce CPU usage.
@gear-tech/dev

fix(node): slow down grandpa finality.

---

Cargo.lock
core-backend/common/Cargo.toml
core-backend/common/src/memory.rs
core-backend/common/src/mock.rs
core-backend/common/src/tests.rs
lazy-pages/src/host_func.rs

Partially resolves #2095.
- do not access memory on zero size reads
It is not quite clear what needs to be changed/optimised in [lazy-pages](https://github.com/gear-tech/gear/blob/master/lazy-pages/src/host_func.rs#L112) with regards to it. @grishasobol can you please clarify?

refactor(backend-common): Avoid memory accesses on zero size reads

---

common/Cargo.toml
utils/wasm-builder/src/builder_error.rs
utils/wasm-builder/src/cargo_command.rs
utils/wasm-builder/src/cargo_toolchain.rs
utils/wasm-builder/src/crate_info.rs
utils/wasm-builder/src/lib.rs

Resolves #2623.
Original toolchain passed to cargo using one of the [options](https://rust-lang.github.io/rustup/overrides.html#overrides) transformed and propagated down to the build script (wasm-builder).
The transformation rule replaces any channel by the `nightly` one, e.g.
`stable[-date]` -> `nightly[-date]`
`beta[-date]` -> `nightly[-date]`
`major.minor[-date]` -> `nightly[-date]`
@gear-tech/dev

build(wasm-builder): Propagate toolchain to wasm-builder

---

Cargo.lock
Cargo.toml
runtime/gear/Cargo.toml
runtime/gear/src/constants.rs
runtime/gear/src/lib.rs
runtime/vara/Cargo.toml
runtime/vara/src/constants.rs
runtime/vara/src/extensions/mod.rs
runtime/vara/src/lib.rs

Add two pallets to both runtimes:
- pallet-proxy
- pallet-multisig.
The `pallet-proxy` in `Gear` runtime lacks proxy types for governance, staking etc. On the other hand, it has the `SudoBalances` instance filter for the `ProxyType` there that doesn't make much sense in `Vara` (hence not included).
The runtime constants are still subject to review and can be changed at later time if necessary.

feat(gear,vara): Add proxy and multisig pallets to both vara and gear runtimes

---

.github/workflows/CI.yaml

Fixed `grcov` execution on master CI. Also, removed unused steps in `build-win-cross` job.

fix(ci): Update `grcov` to musl-based binary

---

common/src/lib.rs
pallets/airdrop/src/mock.rs
pallets/gear-debug/src/mock.rs
pallets/gear-scheduler/src/mock.rs
pallets/gear/src/lib.rs
pallets/gear/src/mock.rs
pallets/payment/src/mock.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Use `#[pallet::constant]` attribute to add program rent parameters to metadata so frontends are able to get them.
@gear-tech/dev

refactor(node): Add program rent parameters to metadata

---

core-backend/common/src/lazy_pages.rs
core-backend/common/src/lib.rs
core-backend/common/src/utils.rs
core-backend/wasmi/src/env.rs
lazy-pages/src/globals.rs

refactor(lazy-pages): use `LimitedStr` for global names

---

Cargo.lock
runtime/common/Cargo.toml
runtime/common/src/lib.rs
runtime/common/src/weights.rs
runtime/gear/src/tests.rs
runtime/vara/src/tests.rs

Resolves #2664.
@gear-tech/dev

refactor(runtime): move heuristics from `gear` & `vara` runtimes to `runtime-common`

---

scripts/unpack-weights.sh

This script is useful when regenerating weights for branches like `cl/issue-2523`. See PR #2563 for more details (there was a problem with it).

feat(script): add weight unpacking tool

---

.github/workflows/CI.yaml

Resolves #2665 
Previously, this problem may not have been noticed due to the lack of pinning of the toolchain.
The reason we use a symbolic link instead of a move is because the `gear.sh` script runs `cargo build` and for some reason `cargo` decided to reinstall the toolchain without `wasm32-unknown-unknown` target.
The problem appears here:
https://github.com/gear-tech/gear/actions/runs/4729497517/jobs/8963897937#step:15:17

ci(build-win-native): use symbolic link for pinning toolchain

---

.github/workflows/CI.yaml

>  Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: codecov/codecov-action@v1
this PR fixes deprecated dependency
link to successful build: https://github.com/gear-tech/gear/actions/runs/5098563452/jobs/9166327352#step:38:1

ci: bump `codecov/codecov-action` to `v3`

---

gsdk/api-gen/src/main.rs
gsdk/build.rs
gsdk/src/metadata/generated.rs

This PR improves panic messages in gsdk build script and ignores documentation errors in output that is generated by subxt-codegen.
Now, if you're using `GSDK_API_GEN=1 cargo build -p gsdk --release` command to update gsdk generated code it will be more interactive (I got few incorrect suggestions from this script)

fix(gsdk): improve error messages and ignore incorrect docs

---

utils/runtime-fuzzer/src/lib.rs

refactor(runtime-fuzzer): Make gas limit variable in runtime-fuzzer

---

examples/binaries/fungible-token/tests/benchmarks.rs

ignore benchmark because it's too long and also require built release node.

ignore ft benchmark

---

Cargo.lock
gtest/src/program.rs
scripts/src/clippy.sh
utils/wasm-builder/Cargo.toml
utils/wasm-builder/src/lib.rs
utils/wasm-builder/src/optimize.rs
utils/wasm-builder/src/stack_end.rs
utils/wasm-builder/src/wasm_project.rs
utils/wasm-proc/src/main.rs

To support assembly-script in gear, make mod for wasm-proc where `_start` function calls in each export function and all mutable globals except stack_end are moved to programs data section.
This command will create `code.opt.wasm`, which can be successfully using as gear program.
```
./wasm-proc --assembly-script code.wasm
```

feat: add assembler-script support in wasm-proc

---

gclient/src/api/calls.rs

Since awaiting inside into_iter() loop can't be `Send` we can fetch mailbox messages before and filter.
@gear-tech/dev

refactor(gclient): avoid async calls inside into_iter() loop

---

core/src/code.rs
pallets/gear-program/src/mock.rs
pallets/gear/src/lib.rs
pallets/gear/src/schedule.rs
pallets/gear/src/tests.rs

restrict mutable globals to be export in gear on instrumentation. Exception is GEAR_STACK_END but only temporary.  In nearest feature GEAR_STACK_END will point to self const export.

feat: restrict mutable globals to be export in gear

---

Cargo.lock
gcli/Cargo.toml
node/cli/Cargo.toml
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

- Version bumped to distinguish the node and runtime from the released version.

chore: bump version to v0.2.0

---

Cargo.lock
gsdk/Cargo.toml
gsdk/src/signer/calls.rs

Awaiting result inside of async recursion can't be `Send`.
Think about how we can match the error outside of recursion.
@gear-tech/dev

refactor(gsdk): Make sign_and_submit_then_watch `Send`

---

core-backend/common/src/lib.rs
core-backend/common/src/mock.rs
core-processor/src/ext.rs
core/src/gas.rs
pallets/gear/src/ext.rs

`SystemTerminationReason` error variants were completely unused, but removing it completely seems a hasty decision.

refactor(core): remove unused `CountersOwner::refund_gas`

---

core-backend/common/src/funcs.rs
core-backend/common/src/lib.rs
core-backend/common/src/memory.rs
core-backend/common/src/mock.rs
core-backend/common/src/runtime.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/runtime.rs
core-backend/wasmi/src/env.rs
core-backend/wasmi/src/funcs_tree.rs
core-backend/wasmi/src/memory.rs
core-backend/wasmi/src/runtime.rs
core-backend/wasmi/src/state.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core-processor/src/lib.rs
core-processor/src/processing.rs
core/src/code.rs
core/src/env.rs
core/src/message/mod.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/ext.rs

Resolves #2654 
This PR actually **renames** only several traits/types:
- `EnvironmentExecutionError` -> `EnvironmentError` (as environment actually doesn't execute, errors aren't much related to execution).
- `ProcessorError` -> `ExtError` (`ProcessorExt` trait can have `ProcessorExt` error, but there's no such associated type in this trait. What's more there's no additional helping context with "Processor*" prefix to the error, especially if we look at the type definition). Same for `ProcessorAllocError` -> `ExtAllocError`.
All other changes are **name extensions** (instead of short names or one-letter generic names, which made it hard to understand the code and definitions of some types):
- generic `EP` -> EntryPoint
- generic `A` in some functions of `core_processor::execute` -> …

refactor(core-backend): rename generics `core-backend` & `core-processor` so they emphasize their essence

---

utils/wasm-instrument/src/lib.rs

```rust
fn gas_charge(gas_to_charge: u32) {}
```
This function compiles to
```wasm
i32.const $gas_to_charge ; <--- not charged now
call $gas_charge
```
There should be gas charge for this instruction too

fix(gear-wasm-instrument): correctly calculate cost of `gas_charge` itself

---

Cargo.lock
utils/call-gen/src/rand_utils.rs
utils/node-loader/CHANGELOG.md
utils/node-loader/Cargo.toml
utils/node-loader/src/batch_pool.rs
utils/node-loader/src/main.rs
utils/node-loader/src/utils.rs

Resolves #1876 .
- Use `EventsReciever` to process events.
- Use tokio timeout to catch stopped node.
- Spawn `BatchPool` in new thread.
@gear-tech/dev

feat(node-loader): Spawn batch pool in new thread

---

core-backend/common/src/funcs.rs
core-backend/common/src/lib.rs
core-backend/common/src/mock.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core/src/buffer.rs
core/src/env.rs
core/src/memory.rs
core/src/message/common.rs
core/src/message/context.rs
core/src/message/handle.rs
core/src/message/incoming.rs
core/src/message/init.rs
core/src/message/mod.rs
core/src/message/reply.rs
core/src/message/stored.rs
gclient/tests/memory_dump.rs
gclient/tests/upload.rs
gear-test/src/check.rs
gtest/src/log.rs
gtest/src/mailbox.rs
gtest/src/manager.rs
pallets/gear-debug/src/lib.rs
pallets/gear-debug/src/tests.rs
pallets/gear-scheduler/src/tests.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
pallets/gear/src/ext.rs
pallets/gear/src/tests.rs
utils/gear-runtime-test-cli/src/command.rs

Resolves #2380
Introduced changes:

refactoring(core): remove gas counter from `read`

---

scripts/src/test.sh

This should speed up the corresponding ci step a bit
@gear-tech/dev

refactor(test): Don't build runtimes in doc-tests

---

examples/binaries/new-meta/io/src/lib.rs
gcli/src/meta/mod.rs
gcli/src/meta/tests.rs
gcli/src/result.rs
gcli/tests/cmd/program.rs
gmeta/src/lib.rs

Resolves: #2809
- As we can't send a reply from a reply, the outgoing type in `Metedata::Reply` becomes senseless.
- Also, two new fields have been added to the metadata: language ID (0 for Rust, 1 for AssemblyScript), and metadata version (starting from 1).
This is a breaking change for smart contracts and IDEA.
@gear-tech/dev

refactor(gmeta)!: change `Reply` type to input only and add new fields

---

examples/binaries/btree/src/lib.rs
examples/binaries/compose/src/lib.rs
examples/binaries/constructor/src/call.rs
examples/binaries/distributor/src/lib.rs
examples/binaries/fungible-token/src/contract.rs
examples/binaries/mul-by-const/src/lib.rs
examples/binaries/ncompose/src/lib.rs
examples/binaries/node/src/lib.rs
examples/binaries/piggy-bank/src/lib.rs
examples/binaries/vec/src/lib.rs
examples/capacitor/src/lib.rs
examples/wait/src/lib.rs
gstd/src/macros/debug.rs

Resolves #2813
Unfortunately this change causes backwards compatibility break. 
```rust
debug!("String literal"); //($arg:literal)
let value = 42;
debug!(value); //($arg:expr)
```
This code will not work because we cannot distinguish at the macro level `debug!("String literal")` and `debug!("fmt {var1}")`. That's why it will probably break backwards compatibility.

feat(gstd)!: expand `gstd::debug!` behaviour

---

utils/wasm-builder/src/lib.rs

Path remapping makes compilation under WSL terrible. Cold rebuild, i.e. when there were no changes in any examples, takes 9 min compared to 45 sec without that remapping

feat(wasm-builder): Introduce switch for disabling path remapping

---

pallets/gear/src/schedule.rs
utils/wasm-instrument/src/lib.rs

Resolves #1706
Changes:
- bump version in schedule to force re-instrumentation
- make it easier to read the code that determines the cost of successful execution
- optimize the `gas_charge` function by using the `local.tee` instruction to store `total_gas_to_charge` in a local variable
```wasm
i32.const 10
local.tee 1 ;; <--- sets 10 to local variable with index 1 & pushes 10 onto the stack
;; for example 10 can be used as an argument
call $func ;; func(10)
```
The performance of the `gas_charge` function has increased by ~14%. (cost of calling this function: 47133 -> 40992, tested on gear-runtime).
@gear-tech/dev

refactor(gear-wasm-instrument): optimize `gas_charge` function

---

utils/wasm-builder/src/smart_fs.rs

- Removed a limit to files generated by `gear-wasm-builder` as a 4kb limit for `wasm_binary.rs` is too restrictive.
@gear-tech/dev 
- **Removed a 4kb limit for files generated by `gear-wasm-builder`**
- This limit caused a failure when building large Gear programs due to big `wasm_binary.rs` auto-generated file. Now there are no limits to making great dApps.

fix(wasm-builder): remove limit on generated files

---

Cargo.lock
examples/binaries/waiter/Cargo.toml
examples/binaries/waiter/src/code.rs
examples/binaries/waiter/src/lib.rs
examples/binaries/waiter/tests/mx_lock_access.rs
examples/binaries/waiter/tests/rw_lock_access.rs
examples/binaries/waiter/tests/utils.rs
gstd/src/lock/mutex.rs
gstd/src/lock/rwlock.rs
gtest/src/system.rs
pallets/gear/src/tests.rs

At the moment it is allowed to obtain mx/read/write lock guard in the context of one message and use it in the context of another which is wrong. This PR fixes this issue.

fix(gstd): Allow mutex/read/write lock guard access by holder only

---

common/src/gas_provider/internal.rs
common/src/gas_provider/mod.rs
pallets/gas/src/tests.rs
pallets/gear/src/runtime_api.rs
pallets/gear/src/tests.rs

While calculating gas there is getter for current gas limit of the main node, that will be none if some error occurs in gas tree (e.g. node not found). Same should be for query of its balance (even in other functionality).
That affected calculating that way: we check balance of already consumed node that has 0 balance, so calculator means that execution burned all gas from the node, which initially equals block gas limit.

fix(rpc-fns): Fix bug with `calculate_gas` returning block gas limit

---

.github/workflows/test-measurements.yaml
utils/wasm-builder/src/lib.rs

The ecosystem team can use the "production" profile to remove the username from the wasm binary.

perf(wasm-builder): invert path remapping logic

---

examples/fungible-token/src/contract.rs
utils/wasm-builder/src/optimize.rs
utils/wasm-builder/src/wasm_project.rs

Resolves # .
- update `fungible-token` changes from https://github.com/gear-foundation/dapps-fungible-token/pull/52.
- set `opt-level = z` in toml
- set `wasm-opt` level to 4 and shrink 2
- set `codegen-units = 1`
- set `lto = "fat"`, which is the same as `true`
These changes reduce the size of wasm artifacts and speed up programs.
`stress_transfer` benchmark (updated):
```
before: Gas burned for one transfer operation = 0.9770345439034853 * 10^9. Calculated as geometric mean from 100 transfer operations.
after:  Gas burned for one transfer operation = 0.9441607030742862 * 10^9. Calculated as geometric mean from 100 transfer operations.
```
Artifact size:
```
fungible-token upload fees
before:
4.254320105 unit
after:
3.609106373 unit
```
Before | After | program |
---|---|---
| 54 Ki|  46 …

feat(wasm-builder): Set optimisation params

---

Cargo.lock
common/src/gas_provider/lockable.rs
core/Cargo.toml
core/src/gas.rs
gclient/Cargo.toml
gclient/src/api/calls.rs

Resolves #2965 
@gear-tech/dev

refactor(common): move LockId to gear-core

---

gsdk/src/signer/calls.rs
gsdk/src/signer/mod.rs

Resolves #2962 
As the context provided in #2962, it is possible to reach the retracted event of the transactions. here in this PR we just allow `Retracted` in our processor, it is safe because the watch logic will keep working on listening the events in futures blocks unless we drop it
for the `TxProcess::wait_for_finliazed` implementation in `subxt`:
https://github.com/paritytech/subxt/blob/master/subxt/src/tx/tx_progress.rs#L106
```bash
git clone https://github.com/gear-foundation/dapps-dex.git
cd dapps-dex
git checkout cl/retracted-txs
cargo nextest run -Fbinary-vendor state_consistency  --release --no-capture 
```
```
START             dex-pair::state_consistency state_consistency
running 1 test
Uploaded `../target/wasm32-unknown-unknown/debug/ft_storage.opt.wasm`.
Uploaded …
```

feat(gsdk): allow transaction retracted

---

examples/fungible-token/tests/benchmarks.rs

Because the examples have been moved, this test has stopped working. I also added seed for the number generator so that the test will always show the same result.

chore(ft-benchmarks): fix wrong path and set PRNG seed

---

Cargo.lock
Cargo.toml

I recently made some improvements affecting memory allocation in `parity-scale-codec`. Version 3.6.4 was released today which solves this problem: https://github.com/paritytech/parity-scale-codec/issues/471

chore(deps): bump parity-scale-codec to 3.6.4

---

core-processor/src/ext.rs
core/src/message/context.rs

- Added a test for the limit of message `send_init` calls.
- Also checks that the `send_commit`, `send_push` and `send_push_input` functions do not error.
- Added helper methods on `ProcessorContextBuilder` for message config.

test(core-processor): Add tests for send message limit

---

utils/wasm-builder/src/optimize.rs

By the way using wasm-opt from lib gives wasm an even smaller size and speeds it up a bit.
@gear-tech/dev

feat(wasm-builder,wasm-opt): use only mvp features, enable sign-ext

---

gcli/tests/cmd/program.rs
gcli/tests/common/env.rs
gcli/tests/gear.rs
utils/wasm-builder/src/wasm_project.rs

The current location of `*.meta.txt`s is inconvenient. It's not a problem in a workspace with a single contract but becomes cumbersome in a workspace with a large number of contracts as a developer needs to open each contract folder to access multiple `*.meta.txt`s. Also this makes a CI setup more complicated since we distribute contract binaries paired with their `*.meta.txt` file and have to find the latter across all the workspace.

Put `*.meta.txt`s in the `target` directory along with WASMs

---

.github/workflows/CI.yaml

Resolves #2970 .
Apparently, `cachepot` does not follow environment variables set via build scripts and prefers the ones it cached

ci(win-native): Remove cachepot as rustc_wrapper for build-win-native

---

pallets/airdrop/Cargo.toml
pallets/airdrop/src/benchmarking.rs
pallets/airdrop/src/lib.rs
pallets/airdrop/src/mock.rs
pallets/airdrop/src/tests.rs
runtime/vara/src/lib.rs
runtime/vara/src/weights/mod.rs
runtime/vara/src/weights/pallet_airdrop.rs

Resolves #2949  .
- Add tests for `Notvesting` and `ScheduleIndexOutOfBounds` errors
- Fix `transfer` benchmark
- Add `transfer_vested` benchmark
- Add benchmarks to runtime
- Update pallet weights
But no fee will be paid anyway as these calls are only allowed for sudo
@gear-tech/dev

refactor(pallet-airdrop): Add tests and benchmarks

---

scripts/weight-diff.sh
utils/weight-diff/src/main.rs

Add comparison for memory weights.
```bash
cargo run --package gear-weight-diff --release -- diff ./weight-dumps/master.json  ./weight-dumps/vs-refine-runtime-interface.json "gear" "memory" --display-units
```
For example:
Comparison table for Gear runtime
| name                                  | master   | vs/refine-runtime-interface | diff    |
|---------------------------------------|----------|-----------------------------|---------|
| lazy_pages_signal_read                | 28.1 µs  | 28.1 µs                     | -0.17%  |
| lazy_pages_signal_write               | 33.9 µs  | 34.9 µs                     | -2.75%  |
| lazy_pages_signal_write_after_read    | 9.1 µs   | 9.7 µs                      | -5.54%  |
| lazy_pages_host_func_read             | 29.1 µs  | 29.0 µs …

feat(weights-diff): Add memory weights

---

examples/constructor/src/builder.rs
pallets/gear/src/queue.rs
pallets/gear/src/tests.rs

We don't allow sending message to terminated program from extrinsic (by user). But checking destination "activeness" is quite hard from the wasm execution level, i.e. when program sends message to some other terminated program.
Here we test this do not cause a panic and returns expected errors.
@gear-tech/dev

Test sending message to terminated program from program

---

utils/wasm-gen/src/tests.rs

Will be fixed after introducing entry points generator and sys-calls generator - the third PR from set of refactoring wasm-gen PRs (#2980 , #2982).
@gear-tech/dev

test(wasm-gen): Comment `test_gen_reproduction` until upcoming fix

---

node/cli/src/command.rs

Currently we can't override log filter if `--validator` flag is enabled.

feat(node): don't set logger hook if custom log is present

---

gtest/src/log.rs

Resolves #3023 
@gear-tech/dev 
- **Fixed bug related to missing panic replies when using the `RunResult::contains` function in `gtest`**
- There was a bug when dealing with the [`RunResult`](https://docs.gear.rs/gtest/struct.RunResult.html) containing a panic reply. Calling the [`RunResult::contains`](https://docs.gear.rs/gtest/struct.RunResult.html#method.contains) function with any payload returned `true` in case of panic result inside it.

fix(gtest): catch panic reply in RunResult

---

gstd/src/common/handlers.rs

#2200 broke the the printing of panic messages in `gtest` tests due to removing a log function to do so. This PR adds it back for debug builds just before calling `gr_panic`.

fix(gstd): log the panic message for the debugging convenience

---

.github/workflows/combined-dependabot.yml

We no longer have the E1-forcewindows label. This throws an error in the workflow: https://github.com/gear-tech/gear/actions/runs/5840328530/job/15839453525#step:2:208

chore(ci): remove missing label in `combined-dependabot.yml`

---

gcli/tests/gear.rs

chore(gcli): change the timeout ms from 10 to 1 in tests

---

Cargo.lock
gsdk/src/metadata/generated.rs
node/authorship/Cargo.toml
node/authorship/src/authorship.rs
node/authorship/src/block_builder.rs
node/authorship/src/tests.rs
node/cli/src/cli.rs
node/cli/src/command.rs
node/service/src/lib.rs
pallets/gear-debug/src/mock.rs
pallets/gear-scheduler/src/mock.rs
pallets/gear/rpc/runtime-api/src/lib.rs
pallets/gear/src/benchmarking/tests/utils.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager/journal.rs
pallets/gear/src/mock.rs
runtime/common/src/apis.rs
runtime/vara/src/integration_tests.rs

Enables `--max-gas` command line argument to set a hard limit for the amount of gas a validator can spend in one block for the message queue processing.
Useful to reduce pressure on validators in case of the network congestion (DDoS attack or whatnot) to keep producing blocks at constant rate and not disable the queue processing completely.
Implementation wise, this value, if set, is propagated to the block authorship module in the client and then passed as a parameter to the `Gear::run()` extrinsic through a `runtime-api`, which will from now on take an `Option<u64>` as an argument.

feat(cli): Add node CLI arg to set max block gas value

---

Cargo.lock
node/authorship/Cargo.toml
node/authorship/src/tests.rs

The `pallet-bank` that is about to be merged introduces the bank account and requires the latter exists at the time an `init_package` is created. This would make one of the tests fail.
The current PR forward-fixes that.

fix(authorship): Forward-fix a test that will require the gear-bank account to exist

---

gstd/codegen/src/lib.rs
gstd/codegen/src/utils.rs
gstd/src/msg/async.rs
gstd/src/msg/basic.rs
gstd/src/msg/encoded.rs
gstd/src/prog/basic.rs
gstd/src/prog/encoded.rs
gstd/src/prog/generator.rs

Resolves #3051
Changes:
@gear-tech/dev

refactor(gstd-codegen): use fully qualified paths

---

Makefile

This PR makes the documentation more user friendly because you can jump to any func, struct, enum variant, etc. Also we can enable the same for gear-foundation.
Running `make doc` on the local machine:
- before: `1 m 57 s`
- after: `2 m 9 s`
@gear-tech/dev

feat(docs): generate link to definition

---

runtime/vara/src/lib.rs

3 sec block was introduced in https://github.com/gear-tech/gear/pull/2436 but MAXIMUM_BLOCK_WEIGHT wasn't changed.
This PR updates MAXIMUM_BLOCK_WEIGHT calculation using block time from constants.

fix(vara): Update MAXIMUM_BLOCK_WEIGHT to 1 sec

---

gsdk/src/client.rs

Pretty frequently we receive an RPC error, which tell us that RPC payload is too big. This fixes the client side of that error.
Server side is "fixed" with running the node (loaded by `gear-node-loader`) with  `--rpc-max-response-size 100` cli param.
@gear-tech/dev

fix(node-loader): Fix anoying error with too large RPC data

---

Cargo.lock
utils/gear-replay-cli/Cargo.toml
utils/gear-replay-cli/README.md
utils/gear-replay-cli/src/cmd/gear_run.rs
utils/gear-replay-cli/src/cmd/mod.rs
utils/gear-replay-cli/src/cmd/replay_block.rs
utils/gear-replay-cli/src/lib.rs
utils/gear-replay-cli/src/parse.rs
utils/gear-replay-cli/src/util.rs

Existing CLI replays blocks that have already been finalized. However, if an extrinsic panicked at the time of block creation, it would have been dropped and not included in a block, thereby destroying the whole purpose of attempting to get some meaningful information about the root cause of the panic.
To circumvent that, a subcommand is being introduced that would mimic the steps of a block producer (not validator): initialize a block and apply extrinsic through calling the `BlockBuilder_apply_extrinsic` runtime api. Current implementation only supports the `Gear::run()` extrinsic, mainly because it is where the message queue is processed, but also because it doesn't have any arguments, therefore the known encoded version of it can be supplied to the runtime api call (without a need of …

feat(tests, cli): Add subcommand to `gear-replay-cli` tool

---

pallets/payment/src/lib.rs
pallets/payment/src/tests.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

- Change transaction cost multipler from `2^(QUEUE_LEN/10)` to `QUEUE_LEN/1000 + 1`.
@gear-tech/dev

feat(runtime): make transaction cost multiplier smoother

---

pallets/gear/rpc/src/lib.rs

By this call rpc users can avoid network bottleneck by reading states in one iteration.
This is useful for indexers or for example to fetch all nft contracts.
Usage:
```bash
❯ curl -s -H "Content-Type: application/json" -d '{
"id":1,
"jsonrpc":"2.0",
"method":"gear_readStateBatch",
"params":[
[
[
"0x6f3abd2d1c8d71812eefdda68228bdf80053ca6549d8b13897a671a8580e9d64",
"0x00"
],
[
"0x93ad566cbf9c10f33a0f63026379177b983bbab86e8a0529dfa38837d8f42487",
"0x00"
]
]
]
} http://127.0.0.1:9944
{
"jsonrpc":"2.0",
"result":[
"0x0026c7026331ed7e90eb5a6fad656c910839182d8fabd77a4bcd6a62b7b0fb967a00000c616161107777777700000000000000000000000000000000000000000000000000000000000000000426c7026331ed7e90eb5a6fad656c910839182d8fabd77a4bcd6a62b7b0fb967a000000", …
```

feat(pallet-gear-rpc): read states in batch

---

docker/runtime-fuzzer/Dockerfile
docker/runtime-fuzzer/scripts/fuzzer.sh
utils/runtime-fuzzer/README.md

When installing `cargo-fuzz` from github it requires additional params used when fuzzing for creating a proper coverage report
@gear-tech/dev

fix(runtime-fuzzer): Fix fuzzer coverage script

---

core/src/buffer.rs

Changes the Display and Debug implementations for `LimitedVec`, reusing the code from `declare_id` macro. This allows the formatting of the Payload to be formatted without printing the entire payload, which can be up to 8MiB. This applies to Messages and Packets aswell.
@gear-tech/dev

refactor(core): Change Debug/Display implementation for Payload

---

Cargo.lock
Cargo.toml
node/service/Cargo.toml
node/service/src/client.rs
node/service/src/rpc/mod.rs
pallets/staking-rewards/rpc/Cargo.toml
pallets/staking-rewards/rpc/runtime-api/Cargo.toml
pallets/staking-rewards/rpc/runtime-api/src/lib.rs
pallets/staking-rewards/rpc/src/lib.rs
pallets/staking-rewards/src/lib.rs
runtime/gear/Cargo.toml
runtime/gear/src/lib.rs
runtime/vara/Cargo.toml
runtime/vara/src/lib.rs

New RPC call in `pallet-gear-staking-rewards` (and respective `runtime-api` call) to query current inflation and ROI values (either at current best block or any block hash in the past).
This is needed to be able to correctly display staking-related numbers in UI.
Note: even though technically inflation is 0 (any newly minted tokens at the end of an era are offset against the inflation pool), the value returned from the call is still relevant as an indicator of how close/far we are from the ideal staking ratio.

feat(rpc): Add RPC call to query inflation and ROI

---

pallets/gear/src/runtime_api.rs
pallets/gear/src/tests.rs

refactor(pallet-gear): Allow `calculate_gas_info` on terminated program.

---

Cargo.lock
node/authorship/Cargo.toml
node/authorship/src/tests.rs

Recently the debug feature of `demo-waiter` crate in pallet-gear has been enabled for specific reasons. However this leads to propagation of `debug` feature for `gstd` to all crates when the workspace are being built. It is the reason of `block_max_gas_works` test failure in `make pre-commit` locally since the required gas limit changed.
@gear-tech/dev

chore(tests): Adjust `block_max_gas_works` test of gear-authorship

---

Cargo.lock
Cargo.toml
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

To avoid nightly builds running in native, for example 
(should also be a rule)

chore(versioning): Update runtime version

---

Cargo.lock
utils/node-loader/src/utils.rs
utils/runtime-fuzzer/src/arbitrary_call.rs
utils/wasm-gen/src/config.rs
utils/wasm-gen/src/config/module.rs
utils/wasm-gen/src/tests.rs

Picks up these changes https://github.com/gear-tech/wasm-tools/commit/9942645b3891607e13f11f6444ca320ba36a6a1f by introducing `unreachable_enabled` selectable option for module generation config in `wasm-gen`.
Also this PR disables the intruction in fuzzer and loader, because in accordance to coverage data reports most of executions end up reaching `unreachable`, testing which isn't the main priority.

feat(wasm-gen): Introduce `unreachable_enabled` in `wasm-gen`

---

.github/actions/label/skip.js
.github/workflows/PR.yml
.github/workflows/docs.yml
.github/workflows/typos.yml
DEVELOPMENT.md

Resolves #3309 
we can not process this hack with `[skip ci]` because [it will skip everything][skip-ci]..., so here in this PR we check the title of PRs, if contains `[skip-ci]`, we simply skip heavy CIs
Leaving one `typos` is that the [create checks API][create-checks] of github requires one more workflow excepting the workflow it belongs to most of the time ( this API is originally designed for github APPs, so it could be buggy we calling it from github actions directly), for example, see the CI of [de52c97](https://github.com/gear-tech/gear/pull/3324/commits/de52c97b9aecfda22953ced1e350b8a26e543f6e), this may also related to #3316 
[create-checks]: https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run
[skip-ci]: …

[skip-ci] ci(skip): skip CI with green spot

---

runtime/vara/src/lib.rs

fix(vara): nomination pools - set MaxUnbonding eq to staking

---

scripts/src/test.sh
utils/node-loader/src/utils.rs
utils/runtime-fuzzer/README.md
utils/runtime-fuzzer/src/gear_calls.rs
utils/wasm-gen/src/config/module.rs

This task was a hot one from the beginning of `runtime-fuzzer` launch when first production coverages were available. The issue was that there were too many traps, which caused a very weak coverage for messaging logic in the `pallet_gear`.
After researching it thoroughly, I have found out that there were 2 many trap reasons: `Possibly 'unreachable' instruction reached` and `Not enough gas to continue execution`. 
The former trap reason was caused not only by `unreachable` instruction occurrences, but there were some other internal wasmi errors causing that termination reason. I have turned off `unreachable` instructions here https://github.com/gear-tech/gear/pull/3307.
The latter one was mainly due to large loops in wasm - each function body consisted of about 100_000 instructions and …

refactor(wasm-gen, runtime-fuzzer): Increase successful messages execution rate in `runtime-fuzzer`.

---

runtime/vara/src/lib.rs

feat(vara): add TransactionPaymentCallApi

---

gsdk/src/metadata/generated.rs
pallets/staking-rewards/src/lib.rs
runtime/vara/src/integration_tests.rs
runtime/vara/src/lib.rs

- Dust and slashes handlers to pallets configs to keep the total issuance consistent
- Tests

feat(runtime): Adding dust and slash handlers

---

gsdk/src/metadata/generated.rs
pallets/staking-rewards/src/lib.rs
pallets/staking-rewards/src/tests.rs
pallets/staking-rewards/src/weights.rs

This PR brings new extrinsic supposed to be called only once by governance voting on minting/burning some tokens from offset pool in order to align total issuance to 10kkk tokens, because network ran into imbalance here due to previous runtime bugs (see PRs related to dust removal and staking rewards)

feat!(runtime): Add ability to align total supply

---

gsdk/src/lib.rs
gsdk/src/signer/mod.rs

If we want to use subxt in external crates with gsdk we need access to subxt Signer and Config
@gear-tech/dev

feat(gsdk): Expose `GearConfig` and `PairSigner`

---

scripts/install.sh

Resolves #3336
This PR fixes the `install.sh` script to work with `/bin/sh`. I also checked the script using [shellcheck](https://www.shellcheck.net) and in the ubuntu docker container.

fix(scripts): rewrite `install.sh` in POSIX way 

---

.github/workflows/release.yml

Release job are aimed to run checks on compressed wasm, while must run on just compact

chore(workflows): Fix release job

---

pallets/gear/src/schedule.rs
scripts/src/test.sh

refactor(pallet-gear, wasm-gen): Remove stack limiter to decrease unnecessary errors from wasmi

---

utils/wasm-gen/src/generator/syscalls/invocator.rs
utils/wasm-instrument/src/syscalls.rs

Resolves #3375
Instead of skipping the parameter, we will first push the parameter with `value=0` and then mutate it by `length_param_idx`.

refactor(wasm-gen): add new approach of processing syscall parameters

---

examples/constructor/src/builder.rs
rust-toolchain.toml
scripts/src/clippy.sh

it should fix fuzzer & CI
disadvantages: `needless_pass_by_ref_mut` warnings (#3452)

chore: downgrade rust version to nightly-2023-09-18

---

gclient/src/api/mod.rs
gsdk/src/api.rs
gsdk/tests/rpc.rs
utils/node-loader/src/main.rs
utils/validator-checks/src/listener.rs

refactor(gsdk): Remove abiguity in `Api::blocks()` functions

---

gtest/src/manager.rs

Solves the issue of panicking:
```shell
thread 'auto_change_success' panicked at /Users/breathx/.cargo/git/checkouts/substrate-e6594450811c5caa/27779e0/primitives/io/src/lib.rs:157:5:
`exists_version_1` called outside of an Externalities-provided environment.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

fix(gtest): Run delayed dispatches in `externalities` context

---

utils/wasm-gen/src/generator/syscalls.rs
utils/wasm-gen/src/generator/syscalls/invocator.rs

Loose and precise syscalls with destination param received only destination (`gsys::Hash`) instead of destination with value (`gsys::HashWithValue`) when their invocation instructions were generated in `wasm-gen`.

fix(wasm-gen): Include value into argument of invocable syscalls with destination param

---

Cargo.lock
core-backend/src/tests.rs
utils/wasm-instrument/Cargo.toml
utils/wasm-instrument/src/lib.rs
utils/wasm-instrument/src/tests.rs

Resolves # .
- `core-backend` already has dependency `gear-wasm-instrument`
- `core-backend` as dependency of `gear-wasm-instrument` makes it bigger and blocks uploading it to `crates-io`
blocks #3103 
@gear-tech/dev

chore(wasm-instrument): move syscall table test to core-backend

---

core-processor/src/ext.rs
examples/delayed-sender/src/lib.rs
examples/delayed-sender/src/wasm.rs
pallets/gear/src/internal.rs
pallets/gear/src/tests.rs

This one is pretty similar to #2211 in way of solving the panic, but appeared after #2053.

bugfix(runtime): Correctly distribute resources for gasless delayed sending

---

gtest/src/lib.rs
gtest/src/system.rs

Resolves #3514 
- Fixed block duration when incrementing in `System::spend_blocks`.
@gear-tech/dev

fix(gtest): make block duration 3 secs

---

Cargo.lock
core/src/ids.rs
core/src/memory.rs
examples/calc-hash/Cargo.toml
examples/new-meta/io/Cargo.toml
gcore/src/errors.rs
gcore/src/lib.rs
gstd/codegen/src/lib.rs
gstd/src/common/errors.rs
utils/wasm-builder/src/wasm_project.rs

dapp-template throws some additional warnings during build: https://github.com/gear-foundation/dapp-template/blob/master/.cargo/config.toml#L5
pr also fixes `cargo build -p {demo-calc-hash, demo-meta-io}`
@gear-tech/dev

chore(workspace): fix warnings from dapp template, add gstd as dep

---

Cargo.lock
Cargo.toml
gstd/Cargo.toml
gstd/src/common/handlers.rs
gstd/src/common/mod.rs
gstd/src/lib.rs

- `default` now compiles on stable
- `alloc_error_handler` is behind `oom-handler`
- `panic_info_message` is behind `panic-messages`
- Both can be activated with `nightly`

fix(backport)!: Move nightly features behind feature gates

---

rust-toolchain.toml

Resolves #3533 (see details about regression)
fixes `cargo fuzz coverage`

chore: downgrade rust version to nightly-2023-09-05

---

.github/actions/label/build.js
.github/workflows/PR.yml
.github/workflows/label.yml

Resolves #3577 
skip label dispatching on PRs of dependabot, because dependabot doesn't have accesses for dispatching workflows
@gear-tech/dev

ci(dispatch): skip label dispatching on PRs of dependabot

---

gstd/src/macros/debug.rs
gstd/src/prelude.rs
gstd/tests/debug.rs

- Added `dbg!` macro to `gstd` prelude similar to the standard library's one (https://doc.rust-lang.org/std/macro.dbg.html).
@gear-tech/dev

feat(gstd): add the missing `dbg!` macro

---

examples/custom/src/lib.rs
examples/custom/src/simple_waiter.rs
gtest/src/manager.rs
gtest/src/program.rs
gtest/src/system.rs

Now it is possible to test time-limited wait messages ([`gstd::exec::wait_for`](https://docs.gear.rs/gstd/exec/fn.wait_for.html) / [`gstd::exec::wait_up_to`](https://docs.gear.rs/gstd/exec/fn.wait_up_to.html)) using `gtest`. These messages are processed after calling [`gtest::System::spend_blocks`](https://docs.gear.rs/gtest/struct.System.html#method.spend_blocks).
@gear-tech/dev

feat(gtest): process time-limited wait messages

---

.github/workflows/build.yml
Cargo.lock
Cargo.toml
sandbox/env/Cargo.toml
sandbox/env/src/lib.rs
sandbox/host/Cargo.toml
sandbox/host/src/sandbox.rs
sandbox/host/src/sandbox/wasmer_backend.rs
sandbox/host/src/sandbox/wasmi_backend.rs
sandbox/host/src/util.rs
scripts/src/test.sh

we have `sp-wasm-interface-common` as the dependency of `sp-wasm-interface`, in the implementation of sandbox-host and sandbox-env, we are actually just using the modules from `sp-wasm-interface-common`, so use `-common` instead of `sp-wasm-interface`.
@gear-tech/dev

chore(sandbox): use sp-wasm-interface-common instead of sp-wasm-interface

---

pallets/gear/src/runtime_api.rs
pallets/gear/src/tests.rs

`gr_wait` syscall greedily  consumes all available gas. So when the gas value can be divided by waitlist cost without remainder `calculate_gas_info` will return incorrect info.
Test case - https://github.com/gear-tech/gear/actions/runs/7274019037
@gear-tech/dev

fix(node): Take 'wait' syscall into account in calculate_gas_info

---

utils/wasm-gen/src/generator/syscalls/imports.rs

We currently have a problem passing the same pointers as mutable and immutable.

fix(wasm-gen): copy data from `HashWithValue` before writing to `err`

---

Cargo.lock
Cargo.toml

Bump allocator to version that uses new `free_range` call.
@gear-tech/dev

chore: bump gear-dlmalloc for free_range support

---

Cargo.lock
Cargo.toml
lazy-pages/Cargo.toml
lazy-pages/src/globals.rs
sandbox/env/Cargo.toml
sandbox/env/src/lib.rs
sandbox/sandbox/Cargo.toml
sandbox/sandbox/src/embedded_executor.rs
sandbox/sandbox/src/host_executor.rs
sandbox/sandbox/src/lib.rs

This PR is part of #3594 
@gear-tech/dev

chore(sandbox): inherit manifest from workspace

---

utils/node-loader/src/batch_pool/generators/batch.rs
utils/node-loader/src/utils.rs
utils/runtime-fuzzer/src/gear_calls.rs
utils/wasm-gen/src/config.rs
utils/wasm-gen/src/config/syscalls.rs
utils/wasm-gen/src/config/syscalls/param.rs
utils/wasm-gen/src/generator/syscalls.rs
utils/wasm-gen/src/generator/syscalls/additional_data.rs
utils/wasm-gen/src/generator/syscalls/invocator.rs
utils/wasm-gen/src/lib.rs
utils/wasm-gen/src/tests.rs
utils/wasm-gen/src/utils.rs
utils/wasm-instrument/src/syscalls.rs

This PR introduces value fuzzing to the `wasm-gen` and partially resolves #3269 and #3296.
Changes:
- Config for syscall destination arguments is moved to syscalls params config.
- Syscalls params config is now more complexed config type, it includes two separate config maps: one for regular params and the other one for pointers. Pointers config is focused on `Value`, `Hash` and `HashWithValue` pointer types. The two latter pointers include syscall destination config, which gives more control over type of destination for different syscalls. Before these changes if you defined syscalls destination config, it will be reused for every syscall.
- There's no separation for syscalls `with destionation`/`without destionation`. Destination value is generated in the common syscalls params …

feat(wasm-gen): Introduce value fuzzing abilities to `wasm-gen`

---

Cargo.lock
Cargo.toml
runtime-interface/Cargo.toml

Resolves #3622 
`sp-io` is missed in `gear-runtime-interface`
- `gear-sandbox`
- `core-backend` 
can not be built with feature `std` directly
@gear-tech/dev

chore(runtime-interface): handle std for sp-io

---

gsdk/tests/rpc.rs
pallets/gear/rpc/src/lib.rs
pallets/gear/src/runtime_api.rs
pallets/gear/src/tests.rs

These changes formalise error output of calculate gas calls:
* Internal errors (that are supposed to be unreachable) if occur will be thrown as "Internal error: entered unreachable code '`{ERROR EXPLANATION}`'" 
* 🥳 Rpc calls no longer return `<wasm:stripped>`, that happened to be in case of underlying extrinsic failure. Instead, it returns name of the error occurred.
* In case of non pallet-gear error returned it will contain pallet/module index within the runtime of the chain to resolve name collision.
```shell
curl http://testnet.vara.network:9944 -H "Content-Type:application/json;charset=utf-8" -d "{
\"jsonrpc\":\"2.0\",
\"id\":1,
\"method\":\"gear_calculateInitCreateGas\",
\"params\": [
\"0x0000000000000000000000000000000000000000000000000000000000000000\", …
```

refactor(rpc-call): Never return `<wasm:stripped>` from rpc calls

---

pallets/gear/src/runtime_api.rs
pallets/gear/src/tests.rs

Sometimes it happened that user couldn't calculate if his balance is zero. Especially it caused vouchers consumers.
This was happening despite the fact that the balance is mocked to suit the requirements of the call.
In order to increase accuracy of required gas measurement, the measurement is done twice:
* First time we run message with maximum gas limit, receiving some minimal limit
* Second time we run message with minimal limit from previous step to receive even smaller gas amount in case of gas-dependency of the message execution.
**It happened that minimal limit (in gas) can has value equivalent less than existential deposit, so our balance mocking using deposit_creating occurred no-op.**
Always add up existential deposit in calculate gas rpc call balance mock.

fix(rpc-calls): Calculate gas for empty accounts

---

pallets/gear/src/lib.rs
runtime/vara/src/migrations.rs

Fixes `try-runtime::on-runtime-upgrade` warning: `⚠️ Gear declares internal migrations (which *might* execute). On-chain 'StorageVersion(1)' vs current storage version 'StorageVersion(1)'`

chore(migrations): Fix migrations warning

---

core/src/message/common.rs
core/src/message/stored.rs
core/src/message/user.rs
gtest/src/manager.rs
pallets/gear/src/internal.rs

Resolves #2849  - payload is already created from a string in error replies.
https://github.com/gear-tech/gear/blob/eb526152014e69443bdcd4ceac9cd441ad87fe49/core-processor/src/processing.rs#L224-L251

refactor(core): Remove useless string conversion (`with_string_payload()`)

---

pallets/gear/src/manager/journal.rs

Resolves #3707.
Truly not an error. Similar to waking some random message id.

fix(pallet-gear): Remove incorrect `log::error`

---

utils/runtime-fuzzer/src/runtime/block.rs

Resolves #2307
After some discussions came to a conclusion, that it's enough to make it close to real block pallets execution. Fortunately, it was configured right: all the skipped pallets aren't needed (governance or staking related) or do nothing in their `Hooks` implementation.

feat(runtime-fuzzer): Add `TransactionPayment::on_finalize` hook call

---

common/src/paused_program_storage.rs
core-processor/src/executor.rs
core-processor/src/precharge.rs
core/Cargo.toml
core/src/code/errors.rs
core/src/code/mod.rs
core/src/code/utils.rs
pallets/gear/src/lib.rs
pallets/gear/src/schedule.rs
pallets/gear/src/tests.rs
utils/wasm-builder/src/builder_error.rs
utils/wasm-instrument/Cargo.toml

Add checking that data section lies inside static memory (or inside wasm min memory pages).
After runtime upgrade codes with incorrect data sections cannot be re-instrumented or uploaded. 
Insignificant:
1) rename `MAX_WASM_PAGE_COUNT` -> `MAX_WASM_PAGE_AMOUNT`
2) forward `std` feature to `wasmparser` deps.
3) refactoring for `CodeError`: now it contains new internal errors from other crates in order to log full information about code errors in one place: see `try_new_code` in `pallets/gear/src/lib.rs`.
4) remove `InitializationError` and add `DataSectionError`

feat!(gear-core): check data section for uploading codes

---

gsdk/tests/rpc.rs

Demonstrate how to query various program counters from the program storage. The test is ignored by default in order not to increase overall testing time.
@gear-tech/dev

chore(test, gsdk): Add a test case showing how to query a storage

---

pallets/gear-builtin/src/lib.rs

An issue appeared due to improper merging of #3475 with builtins pallet
Incorrect merging produced the following error:
```
--- STDERR:              pallet-gear-builtin tests::basic::invoking_builtin_from_program_works ---
thread 'tests::basic::invoking_builtin_from_program_works' panicked at /Users/runner/work/gear/gear/pallets/gear/src/internal.rs:920:37:
internal error: entered unreachable code: GasTree corrupted! Module(ModuleError { index: 9, error: [1, 0, 0, 0], message: Some("NodeAlreadyExists") })
stack backtrace:
0: rust_begin_unwind
at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/std/src/panicking.rs:647:5
1: core::panicking::panic_fmt
at /rustc/7ffc697ce10f19447c0ce338428ae4b9bc0c041c/library/core/src/panicking.rs:72:14
2: pallet_gear::internal::<impl …
```

fix(pallet-gear-builtin): Fix the issue of bi-replying

---

core-errors/src/simple.rs
gcore/src/exec.rs
gcore/src/lib.rs
gstd/src/exec/async.rs
gstd/src/lib.rs

now you can do:
```rust
use gstd::{exec, EnvVars};
let EnvVars {
existential_deposit,
..
} = exec::env_vars();
```
@gear-tech/dev

fix(gcore, gstd): improve docs & re-export `EnvVars` from gsys

---

pallets/gear/src/schedule.rs
pallets/gear/src/tests.rs

Resolves #3754
This PR provides a testing program filled by empty functions to reach the indexes limit and the code length limit to confirm we are not affected by the deserialization problem of parity-wasm
From my point of view I prefer not cherry picking the fix from `casper-wasm` at the moment:
1. we have the code size limit `512 * 1024 (512kb)`,  and the deserializing logic slows down significantly on my 16GM memory machine when the indexes reaches `268_435_441`, at least code size `1024 * 1024 * 1024 (1gb)`
1. I can dig the specific result of the cost between `Vec` and `BTreeMap` as the `IndexMap` of `parity-wasm`, if anybody like to see it.
3. the stability of `parity-wasm` has been verified by the whole industry for years, picking the update may lead us to new problems since …

feat(pallet-gear): test program with large indexes

---

examples/constructor/src/scheme/mod.rs
pallets/gear/src/runtime_api.rs
pallets/gear/src/tests.rs

By repr case of @LouiseMedova.
Release, included the bug: v1.1.0
PR, created the bug: #3609 
Ref comment: https://github.com/gear-tech/gear/pull/3609#discussion_r1436070409

fix(rpc-call): Return known value in case of finite waits

---

.github/workflows/comparison-table.yml
.maintain/frame-weight-template.hbs
common/src/benchmarking.rs
pallets/gear/src/weights.rs
runtime/vara/src/weights/pallet_gear.rs

Does not cause some real changes in benchmark weights
| name                    | master  | weights/patch-efc32551 | diff    |
|-------------------------|---------|------------------------|---------|
| i64const                | 155 ps  | 180 ps                 | +13.89% |
| i64load                 | 9.5 ns  | 9.7 ns                 | +2.39%  |
| i32load                 | 9.2 ns  | 9.2 ns                 | +0.89%  |
| i64store                | 23.7 ns | 19.7 ns                | -19.89% |
| i32store                | 14.2 ns | 23.8 ns                | +40.30% |
| select                  | 7.3 ns  | 7.2 ns                 | -0.98%  |
| if                      | 6.3 ns  | 6.2 ns                 | -2.19%  |
| br                      | 3.2 ns  | 3.2 ns                 | -0.38%  |
| br_if …

refactor(benchmarks): remove garbage from benchmarks 

---

core/src/message/context.rs
core/src/message/handle.rs
core/src/message/reply.rs

fix(core): set taken payload back in case of errors in `MessageContext`

---

core-backend/src/env.rs
core-backend/src/tests.rs
core/src/code/mod.rs
core/src/program.rs
gtest/src/manager.rs
gtest/src/program.rs
pallets/gear/src/schedule.rs
pallets/gear/src/tests.rs
utils/wasm-gen/src/config/syscalls/injection.rs
utils/wasm-gen/src/tests.rs
utils/wasm-instrument/src/lib.rs
utils/wasm-instrument/src/rules.rs
utils/wasm-instrument/src/syscalls.rs
utils/wasm-instrument/src/tests.rs

Changes:
```diff
impl SyscallName {
// removed in favour of `SyscallName::{all, instrumentable}().count()`
-    pub fn count() -> usize { ... }
// with some code refactoring
-    pub fn instrumentable() -> BTreeSet<Self> { ... }
+    pub fn instrumentable() -> impl Iterator<Item = Self> { ... }
// not used since wasmi was removed?
-    pub fn to_wgas(self) -> Option<Self> { ... }
}
```
@gear-tech/dev

refactor(wasm-instrument): add docs, simplify code

---

Cargo.lock
Cargo.toml
gcli/tests/cmd/claim.rs
gtest/src/lib.rs
pallets/gear-bank/src/mock.rs
pallets/gear-bank/src/tests.rs
pallets/gear/src/schedule.rs
runtime/common/src/lib.rs
runtime/vara/src/lib.rs
runtime/vara/src/migrations.rs

Schedule version bump is required to force reinstrumentation due to changes from #3733

chore!(workspace): Bump versions and dump gas price

---

examples/async-tester/src/lib.rs
examples/async-tester/src/wasm.rs
examples/ping/src/wasm.rs
pallets/gear/Cargo.toml
pallets/gear/src/tests.rs

Resolves #3797 
met no problem in this test, everything works
for cases that never continue execution after the lock, imo the reason could be
- invalid arguments
- wrong code id or the target program failed to reply the the creator program
@gear-tech/dev

chore(examples): introduce program creation test in async-tester

---

Cargo.lock
Cargo.toml
sandbox/host/Cargo.toml
sandbox/host/src/lib.rs
sandbox/host/src/sandbox/wasmer_backend.rs

```rust
type CachedModule = (Vec<u8>, Arc<Module>);
static CACHED_MODULES: OnceLock<Mutex<LRUCache<CachedModule, 1024>>> =
OnceLock::new();
```
In-memory cache reduces wasmer module access latency by up to 50%.
It also has a small memory footprint (I will do more testing on the testnet) that can be moved to the swap if something goes wrong.
We don't need to rely on the filesystem, now a new temporary directory is created every time, so there is no point in serializing modules to the filesystem, temp сache lifetime is the same as that of the node.
I would remove file caching if in-memory approach doesn't cause any problems.
- LRU cache with 1024 cap.
- BLAKE3 Hash only on cache miss (to store to temp file cache).
`module <- LRU <- file cache <- compile`
benches:
```bash
./gear-master …
```

feat(sandbox): Implement LRU cache for Wasmer modules

---

Cargo.lock
utils/wasm-builder/Cargo.toml
utils/wasm-builder/src/lib.rs
utils/wasm-builder/test-program/Cargo.toml
utils/wasm-builder/test-program/src/lib.rs
utils/wasm-builder/tests/smoke.rs

Also skip WASM compilation during Intellij project sync because Intellij itself cannot yet.
Actually this was attempt to get rid of constant build script re-run :/
Idea was to use `CARGO_FEATURE_*` environment variables listing (`cargo_metadata`) and tracking (`cargo:rerun-if-env-changed`) [but](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-env-changed):
> Note that the environment variables here are intended for global environment variables like CC and such, it is not possible to use this for environment variables like TARGET that [Cargo sets for build scripts](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts). The environment variables in use are those received by cargo invocations, not those …

chore(wasm-builder): Test features tracking

---

utils/wasm-builder/src/lib.rs

Accepting the env variable produces a tiny regression in benchmarks:
1. https://github.com/gear-tech/gear/actions/runs/8376284584/job/22935648871
2. https://github.com/gear-tech/gear/actions/runs/8368060285/job/22911543652
3. https://github.com/gear-tech/gear/actions/runs/8381856918/job/22954349120
@gear-tech/dev

fix(node): Do not take SKIP_WASM_BUILD into account

---

Cargo.lock
gtest/Cargo.toml
gtest/src/manager.rs
gtest/src/program.rs
gtest/src/system.rs

fix(gtest): allow zero balance for `exec::exit()`

---

runtime/common/src/weights.rs
runtime/vara/src/tests.rs

Resolves #3839 .
Add heuristic tests for memory weights and syscalls of vara runtime.

test(runtime):  append `MemoryWeights` and syscalls heuristic tests #3839

---

.github/workflows/check.yml
.github/workflows/crates-io.yml
.github/workflows/time-consuming-tests.yml
common/numerated/Cargo.toml
scripts/src/test.sh
utils/crates-io/src/lib.rs
utils/crates-io/src/manifest.rs
utils/wasm-builder/tests/smoke.rs

Resolves #3899 by migrating the ecosystem and publishing packages to stable toolchain. 
We still have problems with the nightly version, since `stdsimd` was split into `stdarch_x86_avx512` and we have many old versions of crates (polkadot-sdk, wasmer) that work on our version of the compiler, but are broken on the newer one.

fix(ci): use stable toolchain for ecosystem

---

Cargo.lock
Cargo.toml
gstd/Cargo.toml
gstd/codegen/Cargo.toml
gstd/codegen/src/lib.rs
gstd/src/common/primitives.rs
gstd/src/lib.rs
utils/crates-io/src/lib.rs
utils/gring/Cargo.toml
utils/gring/src/lib.rs
utils/ss58/Cargo.toml
utils/ss58/src/lib.rs

Resolves #3912
This macro can be useful for interacting with known programs/built-in actors using gstd.
```diff
- ActorId::from_bs58(address)
+ actor_id!(address)
```

 feat(gstd): add `actor_id!` macro

---

Cargo.lock
Cargo.toml
utils/wasm-builder/Cargo.toml
utils/wasm-builder/src/crate_info.rs

cargo-metadata output for target names changes with Rust 1.79 due to PR https://github.com/rust-lang/cargo/pull/12783 fixing issue https://github.com/rust-lang/cargo/issues/12780. (TLDR: dashes in target names are replaced with underscores starting with Rust 1.79)
Currently, if a user tries to build a program where the package name contains a dash, they will receive an error message:
```bash
error: failed to run custom build command for `gear-guessing-game v0.1.0 (/projects/gear-guessing-game)`
Caused by:
process didn't exit successfully: `/projects/gear-guessing-game/target/release/build/gear-guessing-game-f6620258e346ef1d/build-script-build` (exit status: 1)
--- stderr
error: please add "rlib" to [lib.crate-type]
```
@gear-tech/dev

fix(gear-wasm-builder): Support 1.79.0 nightly

---

pallets/gear-program/src/lib.rs
pallets/gear-program/src/migration.rs
pallets/gear/src/migrations.rs

Without this changes migration for waiting init list is not applied in `try-runtime` tests. Even more we need to increase storage version, so that this migration can be applied in future.
```bash
[2024-04-18T12:01:32Z INFO  pallet_gear_program::migration] 🚚 Running migration with current storage version StorageVersion(4) / onchain StorageVersion(3)                      
[2024-04-18T12:01:33Z INFO  pallet_gear_program::migration] Successfully migrated storage. 1862 codes has been migrated                                                          
[2024-04-18T12:01:33Z INFO  pallet_gear::migrations] 🚚 Running migration with current storage version StorageVersion(4) / onchain StorageVersion(4)                             
[2024-04-18T12:01:33Z INFO  pallet_gear::migrations] ❌ Migration did …
```

fix(pallet-gear-program): Migrations version

---

.github/workflows/build.yml

When on-chain runtime is updated, the try-runtime job fails with an error, but the development cycle does not have to depend on the on-chain.
related to https://github.com/gear-tech/gear/actions/runs/8900419011/job/24441943523?pr=3921
@gear-tech/dev

chore(ci): Disable spec_version check in try-runtime

---

pallets/gear/src/lib.rs

`CustomConstantCostRules::default()` will add some extra overhead in benchmarks
https://github.com/gear-tech/gear/blob/8ba3c6996be2c4fd060f2d9f16b292c72b201f2c/core/src/code/mod.rs#L274-L280

fix(pallet-gear): don't charge gas in benchmarks

---

.github/workflows/build.yml

Because now default is not 0, so increase running time. 
https://github.com/gear-tech/polkadot-sdk/blob/bab0348372b58d5106333faa597423242e831a31/substrate/utils/frame/benchmarking-cli/src/pallet/mod.rs#L57-L59
Default steps also `50` now. But steps are not taken in account for `--extra` benchmarks without steps.

chore(ci): set `--repeat=0` for all testing benchmarks run

---

core/src/code/errors.rs
core/src/code/mod.rs
core/src/code/utils.rs
core/src/program.rs
gsdk/src/metadata/generated.rs
gtest/src/manager.rs
gtest/src/program.rs
pallets/gear/src/benchmarking/utils.rs
pallets/gear/src/lib.rs
pallets/gear/src/schedule.rs
pallets/gear/src/tests.rs
utils/calc-stack-height/src/main.rs
utils/wasm-builder/src/code_validator.rs
utils/wasm-gen/src/tests.rs
utils/wasm-instrument/src/gas_metering/schedule.rs

Relates #3907 .
Add data segment amount limit check. The limit is set to 1024 data segments.

feat(core,pallets): add data segments amount limit checks

---

pallets/gear/src/migrations.rs

Wrong storage version check in the `pre_upgrade` hook. Affects only `try-runtime` runs.

fix(pallet-gear): unable to run migration `MigrateWaitingInitList` with try-runtime

---

scripts/src/check.sh

Substrate (since v1.3.0) no longer triggers optimisers on debug builds

fix(scripts): Use non-compact debug wasm runtime for imports checking

---

utils/cargo-gbuild/test-program/rust-toolchain.toml

Resolves # .
introduce a soft link for the root rust-toolchain in the smoke tests of `cargo-gbuild`
@techraed

chore(cargo-gbuild): soft link rust-toolchain from the root workspace

---

pallets/gear/src/schedule.rs

Resolves #3943.
Replace `cost-*` helper macros with functions.

Replace cost-* helper macros with functions.

---

Cargo.lock
gsdk/api-gen/Cargo.toml
gsdk/api-gen/src/main.rs

Add `PRINT_SCALE` env var.
Useful for updating backend/frontend before the upgrade. Publish `metadata.scale` to release artifacts.
Usage:
```bash
RUNTIME_WASM=production_vara_runtime_v1400.wasm PRINT_SCALE=1 cargo run -p gsdk-api-gen --release > meta.txt
```
@gear-tech/dev

feat(gsdk): Print SCALE metadata

---

pallets/gear/src/benchmarking/code.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/weights.rs
runtime/vara/src/weights/pallet_gear.rs

Resolves #3992 .
Update `reinstrument_per_kb` bench (and corresponding weight).
Now, when generating the input module code for this benchmark, table and element sections are used (previously, only the code section was used) because they are heaviest weight-wise.

 fix(benchmarks): update reinstrument bench

---

gtest/src/gas_tree.rs
gtest/src/log.rs
gtest/src/manager.rs

Resolves #3977
- Introduce _block_ concept: gas for all generated dispatches are counted not in one single counter, but in the map `block number -> gas used`.
- If processing stopped because of the gas allowance exceed error, the block number is incremented and dispatches execution continues as if it is a new block with updated gas allowance.

feat(gtest): Introduce gas allowance to `gtest`

---

utils/cargo-gbuild/src/metadata.rs

Resolves #4006 
@gear-tech/dev

fix(cargo-gbuild): optional metadata field

---

.github/workflows/check.yml
utils/cargo-gbuild/tests/smoke.rs

https://github.com/gear-tech/gear/actions/runs/9512048719/job/26219320973
The stable toolchain is not installed correctly every time, specify to `toolchain installation`
similar implementations: 
- [the smoke tests in wasm-builder](https://github.com/gear-tech/gear/blob/master/utils/wasm-builder/tests/smoke.rs#L52)
- [stable checks in our ci](https://github.com/gear-tech/gear/blob/master/.github/workflows/check.yml#L61)
@gear-tech/dev

chore(gbuild): specify stable toolchain installation

---

gclient/src/api/calls.rs
gsdk/src/signer/calls.rs
gsdk/src/signer/utils.rs

transfer_keep_alive was fixed to use keep_alive extrinsic.
Added transfer_all, transfer_allow_death

feat(gsdk,gclient): Add transfer_all, transfer_allow_death

---

gstd/src/macros/debug.rs

fix(gstd): make sure `dbg!` macro always expand to valid expression

---

Cargo.lock
Cargo.toml
common/src/pallet_tests.rs
examples/staking-broker/Cargo.toml
examples/staking-broker/build.rs
examples/staking-broker/src/lib.rs
examples/staking-broker/src/wasm.rs
gbuiltins/staking/Cargo.toml
gbuiltins/staking/src/lib.rs
pallets/gear-builtin/Cargo.toml
pallets/gear-builtin/src/benchmarking.rs
pallets/gear-builtin/src/lib.rs
pallets/gear-builtin/src/mock.rs
pallets/gear-builtin/src/staking.rs
pallets/gear-builtin/src/tests/bad_builtin_ids.rs
pallets/gear-builtin/src/tests/staking.rs
pallets/gear-builtin/src/weights.rs
pallets/staking-rewards/Cargo.toml
pallets/staking-rewards/src/mock.rs
runtime/vara/Cargo.toml
runtime/vara/src/lib.rs

The change includes:
- another builtin actor added to the Runtime to enable staking-related logic in programs (e.g. liquid staking etc.). The actor converts incoming messages into dispatchable calls and relays the latter to the `Staking` pallet;
- a set of types facilitating interaction with the staking builtin actor collected in a crate called `gbuiltin-staking`;
- a simple example of how contracts could interact with the builtin in question - for demo purpose only as real life scenarios would require more attention to details.

feat(runtime): Add a builtin actor for staking operations

---

Makefile
_typos.toml
utils/crates-io/src/handler.rs

chore(crates-io): skip not tracked substrate dependencies

---

ethexe/cli/src/args.rs
ethexe/cli/src/main.rs

```console
foo@bar:~$ ethexe generate-key --ethereum
0x78a361a3947f647c525dd109c7d73d04a5f4e1f2
```

feat(ethexe): Option to print only 1 key format after generation

---

Cargo.lock
utils/runtime-fuzzer/src/generator/upload_program.rs
utils/wasm-gen/Cargo.toml
utils/wasm-gen/src/config/syscalls.rs
utils/wasm-gen/src/config/syscalls/param.rs
utils/wasm-gen/src/generator/syscalls.rs
utils/wasm-gen/src/generator/syscalls/invocator.rs
utils/wasm-gen/src/tests.rs
utils/wasm-gen/src/wasm.rs

In the runtime fuzzer:
- When generating a syscall from wait-family, it stores the current message ID in the specified Wasm memory storage for later use.
- When `wake` syscall is called, this previously stored/waited message ID is used as a parameter for the wake syscall.

feat(runtime-fuzzer): use previously waited message id as wake syscall param

---

.github/workflows/check.yml
.github/workflows/crates-io.yml
Cargo.lock
Cargo.toml
gcore/Cargo.toml
utils/crates-io/Cargo.toml
utils/crates-io/src/handler.rs
utils/crates-io/src/lib.rs
utils/crates-io/src/main.rs
utils/crates-io/src/manifest.rs
utils/crates-io/src/publisher.rs
utils/crates-io/src/simulator.rs
utils/crates-io/src/version.rs

Resolves #4142
This PR is aimed at simplifying debugging of package publishing. Package publishing will be checked on temporary cargo registry, which will allow make additional check on CI.
TODO:

feat(crates-io): simulate packages publishing

---

Cargo.lock
ethexe/ethereum/Cargo.toml
ethexe/ethereum/src/abi.rs

> Limbs are least significant first.
```rust
/// Convert to a array of limbs.
///
/// Limbs are least significant first.
#[inline(always)]
#[must_use]
pub const fn into_limbs(self) -> [u64; LIMBS] {
self.limbs
}
```

fix(ethexe): correct numeric cast function

---

common/src/auxiliary/mod.rs
common/src/auxiliary/waitlist.rs
gtest/src/blocks.rs
gtest/src/gas_tree.rs
gtest/src/lib.rs
gtest/src/mailbox/manager.rs
gtest/src/task_pool.rs
gtest/src/waitlist.rs

Defines auxiliary waitlist in `common` crate and ports full implementation of the auxiliary waitlist to `gtest`, without actually using it (next PR).

feat(gtest): Introduce auxiliary waitlist impl to `gtest`

---

.github/workflows/check.yml
scripts/check-lazy-pages-fuzzer.sh

Resolves # .
Output the lazy pages fuzzer's smoke test result and seed in case of failure.

fix(lazy-pages-fuzzer, ci): add error output on lazy pages fuzzer's smoke test fail

---

gstd/src/common/handlers.rs

rust 1.79.0 - 1.80.1 has different panic format and our parser does not work: https://github.com/rust-lang/rust/commit/fc257fae3c6d4adc6effb2535fb9130d8c15e3ff

fix(gstd): parse panic message correctly

---

gtest/src/log.rs
gtest/src/manager/block_exec.rs
gtest/src/manager/task.rs
gtest/src/program.rs

Resolves #4120, #4121, #4122 and #4146

chore(gtest): Resolve multiple small issues in `gtest`

---

gtest/src/manager/journal.rs
gtest/src/state/gas_tree.rs

Fixing issue submitted by @MedovTimur https://github.com/MedovTimur/send-value

fix(gtest): Fix gas tree ops to avoid `split`/`split_with_value` when both reply is sent and reply deposit exists

---

Makefile
gstd/Cargo.toml

This PR fixes missing functions (send with reservations, etc.) in gstd documentation. Rendered: https://docs.gear.rs/pr-4278/gstd/index.html

chore(docs): disable `ethexe` feature on docs.rs, improve docs.gear.rs

---

node/res/vara_testnet.json

rotate keys after migrate to gcloud
synchronization is working:
2024-10-13 12:09:02 ⚙️  Syncing, target=#11008097 (14 peers), best: #8705 (0x8d9f…d6bd), finalized #8704 (0x7fc3…9c27), ⬇ 294.3kiB/s ⬆ 10.6kiB/s

testnet: rotate bootnodes keys

---

utils/gear-replay-cli/src/cmd/replay_block.rs
utils/gear-replay-cli/src/lib.rs

Resolves #4296 
@gear-tech/dev

feat(gear-reply-cli): Check that the snapshot is for the previous block

---

Cargo.lock
gbuiltins/staking/Cargo.toml
gbuiltins/staking/src/lib.rs
utils/crates-io/src/lib.rs

in order to fix https://github.com/gear-tech/gear-bridges/blob/af7c3476aee42844b5b31cabd9c8818517d3c2db/Cargo.toml#L161
for new crates we need:
```
cd path/to/crate
cargo owner --add github:gear-tech:dev
```

feat(crates-io): publish gbuiltins

---

Cargo.lock
Cargo.toml
ethexe/cli/src/tests.rs
ethexe/signer/Cargo.toml
ethexe/signer/src/lib.rs

Resolves #4197
This PR removes a lot of unnecessary dependencies from Cargo.lock

chore(deps): remove ethers in favor of alloy

---

.github/workflows/crates-io.yml
Cargo.lock
docker/runtime-fuzzer/scripts/fuzzer.sh
gbuiltins/proxy/Cargo.toml
gbuiltins/proxy/src/lib.rs
scripts/pin-rust-nightly.sh
utils/crates-io/Cargo.toml
utils/crates-io/src/handler.rs
utils/crates-io/src/lib.rs
utils/crates-io/src/main.rs
utils/crates-io/src/manifest.rs
utils/crates-io/src/publisher.rs
utils/crates-io/src/version.rs
utils/runtime-fuzzer/README.md
utils/wasm-builder/test-program/src/lib.rs
utils/wasm-builder/tests/smoke.rs

feat(crates-io): check owners before publishing

---

gclient/src/api/calls.rs
gclient/tests/memory_dump.rs

refactor(gclient): removed filtering static pages while creating memory dump

---

.github/workflows/check.yml

at least this should help debug `npx @openzeppelin/upgrades-core@^1.32.3`. if it fails, it won't happen during `forge test`.

chore(ci): clear npm cache, install `@openzeppelin/upgrades-core`

---

.github/workflows/test-measurements.yaml
scripts/benchmarking/run_all_benchmarks.sh

to avoid an errors like `Error: Input("Could not get absolute path for: \"./scripts/benchmarking/weights-output/frame_system.rs\". Error: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }")`
@gear-tech/dev

fix(benchmarks): Create files with weights beforehand

---

gcore/src/utils.rs

```bash
cargo build --release -p demo-out-of-memory
cargo build --release -p demo-out-of-memory -F debug
```

fix(gcore): add proper conditional compilation for stack_debug macro

---

node/service/src/chain_spec/vara.rs
runtime/common/src/constants.rs
runtime/vara/build.rs
runtime/vara/src/lib.rs

- Change token symbol injected into merkleized metadata for testnet
- Change spec name of testnet runtime from 'vara' to 'vara-testnet'
- Dev modes now use configuration of testnet runtime (since client always compiled with it)
- Removed some of dead code

fix(runtime): Vara Network Testnet metadata

---

Cargo.lock
Cargo.toml
ethexe/ethereum/src/lib.rs
ethexe/observer/src/blobs.rs
ethexe/observer/src/observer.rs
ethexe/signer/src/lib.rs

`multiple_validators` test is unstable again with `cargo test` and `cargo nextest` on my machine

chore(ethexe): bump alloy to 0.8.0

---

README.md

WAMV can be interpreted as radio station or C++ wasm executor https://github.com/WAVM/WAVM

chore: rename WAMV to Wasm VM

---

ethexe/ethereum/src/mirror/mod.rs
ethexe/ethereum/src/router/mod.rs
ethexe/ethereum/src/wvara/mod.rs

chore(ethexe): add getters for `*.sol` contract interfaces on Rust side

---

Cargo.lock
Cargo.toml

Relates #4341.
Only for Windows:
There was observed what undefined behavior (UB) don't occurs when we pre-commit `corosensei`
stack (pre-commited stack size 1MiB). 

fix(sandbox, lazy-pages): Increase corosensei precommited stack size to 1MiB (windows)

---

.github/workflows/CI.yaml
.github/workflows/PR.yml
.github/workflows/build-macos.yml
.github/workflows/build-win-native.yml
.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/crates-io.yml

In order to append additional information if tests uses anyhow for errors (tokio::tests mainly)
https://docs.rs/anyhow/latest/anyhow/#:~:text=If%20you%20want%20only%20errors%20to%20have%20backtraces%2C%20set%20RUST_LIB_BACKTRACE%3D1%3B

chore(tests): enable RUST_LIB_BACKTRACE=1 for CI and other

---

core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core/src/message/context.rs
lazy-pages/src/common.rs
pallets/gear-builtin/src/lib.rs
pallets/gear/src/tests.rs
utils/wasm-gen/src/tests.rs

fix #3751 
It can be removed now because of this #4304

chore(core-processor): remove ActorExecutionError::UnsupportedMessage

---

core-errors/src/simple.rs

Resolves #3715 
- adding tests for `ReplyCode` and `SignalCode` enums
@grishasobol

chore: add testing encode/decode for ReplyCode and SignalCode

---

ethexe/rpc/src/lib.rs
ethexe/service/src/lib.rs

This implementation is crucial for the further tx-pool proper implementation

feat(ethexe): Introduce stream returning events from the `ethexe-rpc`

---

scripts/src/init.sh
utils/crates-io/src/handler.rs
utils/crates-io/src/manifest.rs
utils/crates-io/src/publisher.rs

Changes:
* Manifest.is_actualized is bool field defining if current version is already published
* rustup toolchain adds wasm target for stable toolchain on `make init`

fix(crates-io): fix late partial publishing 

---

Cargo.lock
gclient/src/api/calls.rs
gclient/src/api/storage/mod.rs
gclient/src/utils.rs
gsdk/src/metadata/generated.rs
gsdk/src/storage.rs
node/testing/src/genesis.rs
pallets/gear-bank/Cargo.toml
pallets/gear-bank/src/lib.rs
pallets/gear-bank/src/migrations.rs
pallets/gear-bank/src/mock.rs
pallets/gear-bank/src/tests.rs
pallets/gear-builtin/src/mock.rs
pallets/gear-builtin/src/tests/bad_builtin_ids.rs
pallets/gear-builtin/src/tests/staking.rs
pallets/gear-debug/src/mock.rs
pallets/gear-eth-bridge/src/mock.rs
pallets/gear-scheduler/src/mock.rs
pallets/gear/src/mock.rs
pallets/payment/src/mock.rs
runtime/common/src/constants.rs
runtime/vara/src/genesis_config_presets.rs
runtime/vara/src/integration_tests.rs
runtime/vara/src/lib.rs
runtime/vara/src/migrations.rs
utils/runtime-fuzzer/src/runtime/mod.rs

Transfers to gear bank can occur multiple times at each block (with every message sent).
Currently for an external observer these transfers look as transfers to an unknown address (which might look weird if not suspicious).
This change links the gear bank account id to the pallet id the same way it is done for other pallets (treasury, staking rewards pool etc.).
The bank account id is stored in the pallet storage which spares the address recalculation each time it is needed (potentially, many times in a single block); on the contrary, it should be fetched from storage only once per block and be kept in overlay across all extrinsics.
Changes:

refactor(gear-bank): Derive gear bank account id from the pallet id

---

.github/workflows/release.yml

Regression after parity-wasm removal. To be reimplemented

fix(release): remove check for dev runtime

---

ethexe/processor/src/host/mod.rs

Disabled caching was the reason of CPU load spikes during `ethexe-service` tests

fix(ethexe-processor): Enable wasmtime cache

---

examples/proxy-broker/src/wasm.rs
pallets/gear-builtin/src/mock.rs

Proxy id was generated using `ID: u64 = 3`, instead of `4`.

fix(gbuiltin-proxy): Fix proxy builtin actor id

---

scripts/src/clippy.sh
utils/wasm-builder/src/lib.rs
utils/wasm-builder/src/wasm_project.rs

This reverts commit 776dd5e0e048d01fb347e7077753a9f7670d9d4b.
Don't actually work because demo and runtime build scripts can be finished in any order, so runtime will wait for not existing WASM file

revert: Don't build WASMs inside Substrate runtime

---

ethexe/consensus/src/lib.rs
ethexe/consensus/src/mock.rs
ethexe/consensus/src/utils.rs
ethexe/consensus/src/validator/coordinator.rs
ethexe/consensus/src/validator/core.rs
ethexe/consensus/src/validator/initial.rs
ethexe/consensus/src/validator/mock.rs
ethexe/consensus/src/validator/mod.rs
ethexe/consensus/src/validator/participant.rs
ethexe/consensus/src/validator/producer.rs
ethexe/consensus/src/validator/submitter.rs
ethexe/consensus/src/validator/subordinate.rs
ethexe/ethereum/src/deploy.rs
ethexe/ethereum/src/lib.rs

The problem was in ValidatorState Stream implementation, where we call poll_next_state only once. This can cause problems if some state would wait for a new future finish after poll_next_state calling and if no events generated. Because there were no situation like this in present consensus implementation - we do not observe tests hang on.
Additionally prepare consensus for more async logic inside, in order to use it for rewards and validators in nearest future.
Bug was found by @ecol-master

fix(ethexe): fix potential problem in consensus implementation
