examples/async/src/lib.rs
rpc-tests/.eslintrc.js
rpc-tests/index.js
rpc-tests/package-lock.json
rpc-tests/package.json
test/code/test_chat.yaml
test/code/test_collector.yaml
test/code/test_condensator.yaml
test/code/test_i32.yaml
test/code/test_mem.yaml
test/code/test_trap.yaml
test/code/test_vec.yaml
test/code/test_wait.yaml

Use `gas_limit` and `value` defined in `.yaml`.
Default:
```
gas_limit = 100_000_000
value = 0
```
@gear-tech/dev

Use gas_limit and value for messages in rpc-tests

---

core-backend/src/funcs.rs
core/src/env.rs
core/src/program.rs

Wrap ext.with() in result.
@gear-tech/dev

ext.with() return result

---

common/src/lib.rs
common/src/native.rs
core-runner/src/runner.rs
core/src/storage.rs
examples/mem/src/lib.rs
node-rti/src/ext.rs
node-rti/src/runner.rs
test/src/check.rs
test/src/main.rs
test/src/runner.rs
utils/gear-test-cli/src/command.rs

- Add `WaitList` trait to gear-core's storage.  
- Implement in-memory and ext wait lists.
- Minor refactoring for being more Rust way.
@gear-tech/dev

Add waiting messages list

---

.github/workflows/master.yml
core-backend/src/funcs.rs
core-backend/src/wasmtime/env.rs

- Fix `send_push` function. 
- Call gear-core-backend's tests for wasmi backend in CI.
@gear-tech/dev

Run tests for wasmi backend

---

core-runner/src/runner.rs
node-rti/src/lib.rs
test/src/runner.rs

To make all arguments explicit

Refactor queue_message/queue_reply in the runner

---

Cargo.lock
common/src/lib.rs
core-runner/src/runner.rs
gtest/src/runner.rs
node-rti/src/lib.rs
pallets/gear/Cargo.toml
pallets/gear/src/lib.rs
pallets/gear/src/tests.rs
tests/btree/src/lib.rs
tests/common/src/lib.rs

Log message processing events

---

core-runner/src/runner.rs
pallets/gear/src/tests.rs

Fix master

---

rpc-tests/index.js

Step to solve #71.
@gear-tech/dev

Check memory pages in rpc-tests

---

common/src/lib.rs

Fixes #126.
- Reference counter introduced for each piece of code.
- If reference counter becomes 0 after a program removal, the code is also cleared from storage.

Remove unused code from storage

---

Cargo.toml
gstd/Cargo.toml
gtest/Cargo.toml

Remove boring warnings when compiling.

Fix cargo profile settings

---

pallets/gear/src/lib.rs
runtime/src/lib.rs

Fix pallet-gear

---

examples/Cargo.toml
examples/guestbook/Cargo.toml
examples/guestbook/src/lib.rs
gtest/spec/test_guesbook.yaml

New program for check how works meta types
Tests https://github.com/gear-tech/gear-js-lib/pull/7

Guestbook program

---

examples/guestbook/Cargo.toml
examples/guestbook/src/lib.rs

Use gstd_meta in guestbook program

---

pallets/gear/src/lib.rs
pallets/gear/src/tests.rs

Display program origin in InitSuccess event

---

.github/workflows/win.yml
Cargo.lock
gtest/Cargo.toml
gtest/src/check.rs
utils/gear-test-cli/Cargo.toml

- Remove unused `termion` crate from `gear-test-cli`.
- Replace `termion` with `colored` in `gear-test`.

Fix build on Windows

---

pallets/gear/src/lib.rs
pallets/gear/src/tests.rs

Fix bug in remove_stale_program extrinsic

---

.github/workflows/CD.yml
docker/Dockerfile

Fixes # .
use new docker image for node 

Update docker image for deploy

---

Cargo.lock
README.md

README.md: [Rendered](https://github.com/gear-tech/gear/blob/AndPa-edits/README.md)

[skip ci] Update README

---

core-runner/src/ext.rs
core/src/env.rs
core/src/message.rs
examples/async/Cargo.toml
examples/capacitor/Cargo.toml
examples/capacitor/src/lib.rs
examples/collector/Cargo.toml
examples/collector/src/lib.rs
examples/panicker/Cargo.toml
examples/wait/src/lib.rs
gcore/src/lib.rs
gcore/src/msg.rs
gcore/tests/smoke.rs
gstd-async/src/msg.rs
gstd/src/msg.rs

Refactor send sys call processing under the hood

---

Cargo.lock
examples/sync_duplicate/Cargo.toml
gstd-async/Cargo.toml
gstd-async/macro/src/lib.rs
gstd-async/src/lib.rs
gstd-async/src/msg.rs
gtest/spec/test_sync_dont_duplicate.yaml
gtest/spec/test_sync_duplicate.yaml
tests/distributor/src/lib.rs

Fix async loop in gstd-async

---

utils/wasm-proc/src/main.rs

add `handle_reply` to optimised wasm exports
@gear-tech/dev

Fix wasm-proc

---

Makefile

[skip ci] Fix `make test-release`

---

core-backend/common/src/funcs.rs
core-backend/sandbox/src/env.rs
core-runner/src/ext.rs
core-runner/src/runner.rs
core/src/env.rs
tests/gas_limit/src/lib.rs

Fixes #371 .
- add memory grow gas charging in the start
- create test for the case in gas_limit

add memory grow gas charging in the start

---

core-backend/common/src/funcs.rs
core-backend/sandbox/src/env.rs
core-backend/wasmtime/src/env.rs
core-runner/src/runner.rs
examples/Cargo.lock
examples/Cargo.toml
examples/exit-code/Cargo.toml
examples/exit-code/src/lib.rs
examples/panicker/src/lib.rs
gcore/src/msg.rs
gstd/src/msg.rs
gtest/spec/test_exit_code.yaml

Add `exit_code` syscall and prevent runner error handling loop

---

core-runner/src/ext.rs
core-runner/src/runner.rs
core/src/gas.rs
gtest/src/js/package-lock.json
gtest/src/js/package.json

Close #383 
- Bump *gear-js/api* version. Some tests were failing because of old the version.   
- Remove GasCounterUnlimited. Not used.
- Replace `Box<dyn GasCounter>` with a concrete implementation (`GasCounterLimited`). 
@gear-tech/dev

Remove `GasCounter` dyn dispatch

---

.github/workflows/CI.yaml
scripts/gear.sh
scripts/src/build.sh

This will force Cargo.lock to be updated

Use locked cargo build on CI

---

Makefile
utils/gear-test-cli/src/command.rs

Check messages on node's `runtests`

---

core-backend/sandbox/src/env.rs

Return the `Instance` error if it occurs as a result of execution.
@gear-tech/dev

Remove Instance unwrap in sandbox

---

.github/workflows/docs.yml

Fix docs deployment: remove gstd-async

---

pallets/gear/src/lib.rs

Fix: Insert to mailbox init program log

---

core-runner/src/builder.rs
core-runner/src/ext.rs
core-runner/src/runner.rs
core/src/message.rs
core/src/storage.rs
gtest/src/check.rs
gtest/src/runner.rs
node-runner/src/ext.rs
node-runner/src/lib.rs
tests/common/src/lib.rs
utils/gear-test-cli/src/command.rs

- Make the message's way to the waiting list shorter.
@gear-tech/dev

Refactor message way to waiting list

---

.github/workflows/Purge.yml
ansible/purge-chain.yaml
ansible/tasks/docker/docker-compose-purge.yaml.j2
ansible/tasks/docker/docker-compose.yaml.j2
ansible/tasks/docker/docker-purge.yaml

Added ansible script and github action to trigger manually to purge chain

Add ansible script for purging existing chain on testnet

---

node/README.md

Modify typo error in `node/README.md `

[skip ci] Fix typo in gear-node README 

---

examples/Cargo.lock
examples/Cargo.toml
examples/futures-unordered/Cargo.toml
examples/futures-unordered/src/lib.rs
gstd/src/async_runtime/futures.rs
gstd/src/async_runtime/mod.rs
gstd/src/async_runtime/signals.rs
gstd/src/async_runtime/waker.rs
gstd/src/msg/async.rs
gtest/spec/test_futures_unordered.yaml

Notify task's wakers on receiving reply

---

core-runner/src/runner.rs
gtest/src/check.rs
gtest/src/runner.rs
gtest/src/sample.rs
node-runner/src/lib.rs
pallets/gear/src/tests.rs
tests/common/src/lib.rs
tests/messages/src/lib.rs
utils/gear-test-cli/src/command.rs

- Add `Message` argument to `run_next` function.
⚠️ TODO:
@gear-tech/dev

Pass handling message directly to runner

---

common/src/lib.rs
common/src/value_tree.rs

**Release notes**: This is step to self-consistent gas economy where gas associated with message is always preserved.

Value tree structures for (future) gas spending algo

---

core-runner/src/builder.rs
core-runner/src/runner.rs
core/src/storage.rs
gtest/spec/test_chat.yaml
gtest/spec/test_gui.yaml
gtest/spec/test_meta.yaml
gtest/src/check.rs
gtest/src/runner.rs
node-runner/src/ext.rs
node-runner/src/lib.rs
tests/common/src/lib.rs
utils/gear-test-cli/src/command.rs

- Remove obsolete `MessageQueue` abstraction from the `Storage` struct.
@gear-tech/dev

Remove `MessageQueue` abstraction from `Storage`

---

common/src/native.rs
core-runner/src/runner.rs
core/src/storage.rs
gtest/src/runner.rs
node-runner/src/lib.rs
pallets/gear-debug/src/tests.rs
pallets/gear/src/lib.rs
pallets/gear/src/tests.rs
tests/common/src/lib.rs

- Remove much of the unused code.
@gear-tech/dev

Remove `handled` field from `ExecutionReport`

---

gtest/spec/test_ping.yaml
gtest/src/check.rs
gtest/src/runner.rs

Resolves #463 .
@gear-tech/dev

gtest: use VecDeque instead of Vec for queue of messages

---

node-runner/src/lib.rs

`node-runner`: add messages from init

---

examples/block-info/test_block_info.yaml
examples/gui-test/src/lib.rs
examples/meta/src/lib.rs
gtest/spec/test_async.yaml
gtest/spec/test_capacitor.yaml
gtest/spec/test_collector.yaml
gtest/spec/test_decoder.yaml
gtest/spec/test_guestbook.yaml
gtest/spec/test_gui.yaml
gtest/spec/test_incomplete_async_payloads.yaml
gtest/spec/test_meta.yaml
gtest/spec/test_multiping.yaml
gtest/spec/test_ping.yaml
gtest/spec/test_rwlock.yaml
gtest/spec/test_sync_dont_duplicate.yaml
gtest/spec/test_trap.yaml
gtest/spec/test_wait.yaml
gtest/src/runner.rs
node-runner/src/lib.rs

- put replies from init to the log
- fix gtest
- send messages  from fixed user
@gear-tech/dev

Fix messages processing

---

common/src/value_tree.rs

Fixes issue with clippy check on CI.

Fix build on CI

---

utils/wasm-proc/metadata-js/index.js

now gr_debug in index js prints msg text (not msg mem pointer)

---

pallets/gear/src/lib.rs
pallets/usage/src/lib.rs
rpc-tests/src/index.ts

Don't put log if nothing happened

Reduce number of log records

---

.github/workflows/CI.yaml

CI: work with cache in local storage

---

runtime/src/lib.rs

bump spec version

---

.github/workflows/CI.yaml

CI: store archive for each job

---

common/src/native.rs
gtest/src/runner.rs
node-runner/src/ext.rs
node-runner/src/lib.rs
pallets/gear-debug/src/tests.rs
pallets/gear/src/benchmarking.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs

Refactor pallet tests

---

.github/workflows/Runtime-upgrade.yaml

Runtime upgrade action

---

.github/workflows/Runtime-upgrade.yaml

[skip ci] tar xz, use compact compressed wasm

---

.github/workflows/CI.yaml

CI: copy cache to tmp

---

.github/workflows/CI.yaml

Cancel previous CI runs

---

Cargo.lock
gstd/README.md
gstd/codegen/src/lib.rs
gstd/src/async_runtime/futures.rs
gstd/src/common/errors.rs
gstd/src/common/handlers.rs
gstd/src/common/mod.rs
gstd/src/common/primitives.rs
gstd/src/exec.rs
gstd/src/lib.rs
gstd/src/lock/mutex.rs
gstd/src/macros/debug.rs
gstd/src/macros/export.rs
gstd/src/macros/metadata.rs
gstd/src/msg/async.rs
gstd/src/msg/basic.rs
gstd/src/msg/encoded.rs
gstd/src/prelude.rs

Please review, provide your edits if necessary (by meaning), after I will proofread it.

gstd documentation

---

.github/workflows/CI.yaml
.github/workflows/Runtime-upgrade.yaml
common/src/lib.rs
pallets/gear/src/lib.rs

- reset storage prefixes defined in `gear_common`
- reset storage values defined in `pallet_gear`
todo:
@gear-tech/dev

`pallet_gear`: add reset extrinsic

---

pallets/gear/src/lib.rs
pallets/gear/src/manager.rs
utils/gear-test-cli/src/manager.rs

So that gas handling is optional and won't be used when not needed

Add gas handler for pallet

---

.github/workflows/Runtime-upgrade.yaml

Runtime-upgrade: checkout repo

---

core-processor/src/executor.rs
core-processor/src/handler.rs
core-processor/src/processor.rs
gtest/src/manager.rs

- `Option` is not `#[must_use]` so no need to `let _ = ...`
- Add copyright preamble in `gtest/manager.rs`
- Other minor fixes and improvements

Minor refactoring

---

core-processor/src/executor.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs
tests/init-wait/src/code.rs
tests/init-wait/src/lib.rs

Load dynamic memory pages for consequent `init` calls

---

README.md

Update README.md logo

---

core-processor/src/common.rs
core-processor/src/processor.rs
pallets/gear/src/manager.rs
tests/common/src/lib.rs

Resolves #397.
- Log the trap reason.
@gear-tech/dev

Add trap reason to runtime log

---

Cargo.lock
tests/btree/Cargo.toml
tests/distributor/Cargo.toml
tests/distributor/src/lib.rs
tests/init-wait/Cargo.toml
tests/messages/Cargo.toml
tests/messages/src/lib.rs
tests/node/Cargo.toml
tests/wait_wake/Cargo.toml

Fix build with rustc 1.60.0-nightly (5e57faa78 2022-01-19)

---

core-backend/common/src/funcs.rs
core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/wasmtime/src/env.rs
core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core-processor/src/processor.rs
core/src/env.rs
examples/Cargo.lock
examples/Cargo.toml
examples/state_rollback/Cargo.toml
examples/state_rollback/src/lib.rs
gcore/src/exec.rs
gear-test/spec/test_mem.yaml
gear-test/spec/test_state_rollback.yaml
gstd/src/exec.rs
runtime/src/lib.rs
tests/common/src/lib.rs

Resolves #80.
Resolves #108.
Provides under-the-hood logic for #614, making that issue useless.
Release notes: _to be written..._
@gear-tech/dev

Rollback state mechanism

---

runtime/src/lib.rs

Bump spec version to apply new RPC calls

---

.github/workflows/CD.yml

Revert "CD self-hosted"

---

.github/workflows/CD.yml

CD self-hosted

---

.github/workflows/Runtime-upgrade-reset.yaml

Fix action name

---

common/src/lib.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager.rs
pallets/gear/src/tests.rs
runtime/src/lib.rs

Temporary solution until we implement critical features affecting program lifecycle. Later we can optimize program code storage.

Store code permanently

---

core-backend/common/src/funcs.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/wasmtime/src/env.rs
core-processor/src/common.rs
core-processor/src/configs.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core-processor/src/processor.rs
core/src/env.rs
core/src/gas.rs
core/src/message.rs
examples/async-init/src/lib.rs
gcore/src/exec.rs
gear-test/src/check.rs
gear-test/src/manager.rs
gear-test/src/proc.rs
gstd/src/exec.rs
gtest/src/lib.rs
gtest/src/manager.rs
gtest/src/program.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs
runtime/src/lib.rs
tests/common/src/lib.rs

Resolves #644 and partially #649.
Left todo-s in code, related to 644 issue now will be covered in #695 to prevent making this pr so huge.
**Release notes**: _to be written..._
@gear-tech/dev

Value management in programs

---

gstd/src/async_runtime/signals.rs
gstd/src/common/handlers.rs
gstd/src/macros/debug.rs

`gstd`: Don't panic if signal not found

---

.github/workflows/CI.yaml

CI: rm types and store cache only on push

---

ansible/tasks/docker/docker-compose.yaml.j2

add telemetry url

---

Cargo.lock
common/src/lib.rs
common/src/native.rs
core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core-processor/src/handler.rs
core-processor/src/lib.rs
core-processor/src/processor.rs
core/src/message.rs
core/src/program.rs
gear-test/src/manager.rs
gtest/src/manager.rs
pallets/gear-debug/src/tests.rs
pallets/gear/Cargo.toml
pallets/gear/src/benchmarking.rs
pallets/gear/src/ext.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs
runtime/src/lib.rs
tests/common/src/lib.rs
tests/program-factory/Cargo.toml
tests/program-factory/build.rs
tests/program-factory/src/lib.rs
utils/gear-runtime-test-cli/src/command.rs

Resolves: #245 
Creating program from program implementation is on st-create-program-from-program-iter1 branch and quite big. To make it easy for review, I decided to divide it to separate PRs.
This is the second one.
@gear-tech/dev

Patch 2 for program from program creation

---

scripts/gear.sh
scripts/src/init.sh
scripts/src/test.sh

New beautiful utility implemented (see https://nexte.st)
@gear-tech/dev

Use cargo nextest utility

---

.github/workflows/CD.yml

add telegram notify

---

Cargo.lock
core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/sandbox/src/memory.rs
core-backend/wasmtime/src/env.rs
core-backend/wasmtime/src/memory.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core/src/memory.rs
pallets/gear/src/ext.rs
runtime/src/lib.rs

Some simple refactoring:
1) rename memory_context to allocations_context
2) remove program_id from allocations_context
3) comments

rename memory_context to allocations_context

---

Cargo.lock
common/src/lazy_pages.rs
core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/wasmtime/src/env.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core/src/gas.rs
lazy-pages/src/lib.rs
lazy-pages/src/unix.rs
pallets/gear/src/ext.rs
runtime-interface/Cargo.toml
runtime-interface/src/lib.rs
runtime/src/lib.rs

Reverts gear-tech/gear#773
Broke production

Revert "Remove panics from lazy pages"

---

.gitattributes

Fixes images are treated as text by Git

Fix Git thinks images are text

---

core-backend/wasmtime/src/env.rs
core-backend/wasmtime/src/funcs.rs
core-backend/wasmtime/src/memory.rs
runtime/src/lib.rs

Get rid of unsafe SyncLaterExt

---

Cargo.lock
Cargo.toml

Relates to https://github.com/briansmith/ring/issues/1469
@gear-tech/dev

Use patched ring

---

Cargo.lock
gear-test/Cargo.toml
gear-test/spec/test_async_sign.yaml
gear-test/spec/test_create_program.yaml
gear-test/src/address.rs
gear-test/src/check.rs
gear-test/src/main.rs
gear-test/src/proc.rs

Lighten `gear-test` crate

---

.github/workflows/CI.yaml

Forgot to add cache unpacking condition to other jobs
@gear-tech/dev

CI: Fix cache

---

README.md

Resolves #730
- Readme social images fix
- Add telegram link

[skip ci] Fix image urls in readme

---

common/src/lib.rs
common/src/storage_queue.rs
core-backend/common/src/funcs.rs
core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/wasmtime/src/env.rs
core-backend/wasmtime/src/funcs.rs
core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core-processor/src/handler.rs
core-processor/src/processor.rs
core/src/gas.rs
gear-test/src/manager.rs
gear-test/src/proc.rs
gtest/src/manager.rs
pallets/gear-debug/src/tests.rs
pallets/gear/src/ext.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs
runtime/src/lib.rs

Don't skip messages, which exceeds gas allowance

---

core-processor/src/executor.rs
core-processor/src/processor.rs
core/src/message/common.rs
core/src/message/handle.rs
core/src/message/incoming.rs
core/src/message/reply.rs
core/src/message/stored.rs
gear-test/src/check.rs
gear-test/src/manager.rs
gtest/src/manager.rs
pallets/gear-program/src/tests.rs
pallets/gear/src/manager.rs
pallets/usage/src/tests.rs
runtime/src/lib.rs
utils/gear-runtime-test-cli/src/command.rs

By the review of @gshep on already merged PR.
@gear-tech/dev

Fix `core-processor` misprint and provide compact `From`'s for core

---

.github/workflows/CI.yaml

fixes (un)packing cache
@gear-tech/dev

CI: use another expression for cache

---

runtime/src/lib.rs

This fixes the problem with incorrect transaction fees calculation due to the trivial implementation of the `pallet_transaction_payment::MultiplierUpdate` trait which resulted into the `NextFeeMultiplier` storage value in transaction payment pallet zeroed out. This essentially cancelled the part of the fee that depended on transactions weight leaving only the part for a tx size and some base fee.
A custom implementation of the `MultiplierUpdate` - the `ConstantFeeMultiplier` struct, is used in place of the Substrate's built-in `pallet_transaction_payment::TargetedFeeAdjustment` just for the sake of efficiency: less computations is run at the end of each block to update the multiplier (which is, in our case, a constant equal to 1.0). However, if we want an elastic multiplier update based …

Provide non-trivial fee multiplier

---

core-processor/src/ext.rs
core/src/gas.rs
core/src/memory.rs
pallets/gas/src/lib.rs
pallets/gear/src/ext.rs
pallets/gear/src/lib.rs
runtime-interface/src/lib.rs
runtime/src/lib.rs

Resolve #828.
- Some functions have been refactored.
- Some operations have been replaced with saturating alternatives.
- Dead code was removed.
@gear-tech/dev

Review arithmetic operations to be safe and sound

---

pallets/gear-program/src/lib.rs
pallets/gear-program/src/migration.rs
pallets/gear/src/lib.rs
pallets/gear/src/migration.rs
pallets/usage/src/lib.rs
pallets/usage/src/migration.rs
runtime/src/lib.rs

Resolves #833.
- add `StorageVersion` in pallets.
- add `migration.rs` templates for future migrations.
@gear-tech/dev

Introduce StorageVersion

---

scripts/src/init.sh

To avoid nightly compiler regressions

Install prebuilt cargo-{hack, nextest} in CI

---

pallets/gear/src/lib.rs
runtime/src/lib.rs

Made submit_program and submit_code transactional

---

Cargo.lock
common/src/benchmarking.rs
common/src/lib.rs
pallets/gear-program/Cargo.toml
pallets/gear-program/src/lib.rs
pallets/gear-program/src/pause.rs
pallets/gear-program/src/tests.rs
pallets/gear/src/manager.rs
pallets/usage/src/mock.rs
runtime/src/lib.rs
utils/gear-runtime-test-cli/src/command.rs

remove panic from set_program_and_pages_data in common

---

Cargo.lock
examples/binaries/exit-init/Cargo.toml
examples/binaries/exit-init/src/lib.rs
pallets/gear/src/lib.rs
pallets/gear/src/tests.rs
runtime/src/lib.rs

Bug fix from audit repo.
@gear-tech/dev

Fix of the bug with sending reply to terminated destination

---

common/src/lazy_pages.rs
gear-test/src/check.rs
lazy-pages/src/unix.rs
pallets/gear/src/ext.rs
pallets/gear/src/tests.rs
runtime/src/lib.rs

Found a bug with twice released lazy pages. So restrict twice releasing and make test which check that all goes well.

fix lazy pages bug

---

core/src/memory.rs
pallets/gear-debug/Cargo.toml
pallets/gear-debug/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs

This pallet had broken test due to different logic, depend on features. Now it's adapted.

Introduce `lazy-pages` feature for `pallet-gear-debug`

---

Cargo.lock
core-processor/src/processor.rs
examples/binaries/waiting-proxy/Cargo.toml
examples/binaries/waiting-proxy/build.rs
examples/binaries/waiting-proxy/src/lib.rs
pallets/gear/Cargo.toml
pallets/gear/src/tests.rs
runtime/src/lib.rs

Resolves #974.
See `core-processor/src/processor.rs`
Thanks to @ekovalev for bug revealing and providing test for it.
- Bug fixed.
- Docs provided.
- Test updated (previous values asserted with inversion).
@gear-tech/dev

Fix value sending in async scenarios

---

Makefile
examples/ping-gas/src/lib.rs
scripts/gear.sh
scripts/src/build.sh
scripts/src/common.sh
scripts/src/test.sh

fix deps in Makefile
add ability to run special yamls in rtest
fix issue #915

fix problems in Makefile and scripts

---

utils/wasm-proc/src/main.rs

Show the descriptive message in wasm-proc

---

utils/wasm-builder/src/cargo_command.rs

Resolves #1003 
@gear-tech/dev

Remove environment variables in wasm-builder

---

Cargo.lock

Substrate changes: https://github.com/gear-tech/substrate/commit/278f3bc029d46102523dda0879ba8d0aef887946

update substrate deps in order to fix problems with wasmer unsupported CPUs

---

runtime-interface/src/deprecated.rs
runtime-interface/src/lib.rs
runtime/src/lib.rs

Fixes https://github.com/gear-tech/builds/runs/6784840579

Fix `runtime-interface` cannot be built on Windows

---

examples/Cargo.lock
examples/Cargo.toml
examples/async-recursion/Cargo.toml
examples/async-recursion/src/lib.rs
gear-test/spec/test_async_recursion.yaml

add example which recursively uses async send and reply

add async recursion test and example

---

gcore/src/msg.rs
gstd/src/msg/async.rs
gstd/src/msg/basic.rs

Resolves #1029 .
Remove duplicates.
@gear-tech/dev

Make `gcore` and `gstd` docs lighten

---

scripts/src/format.sh

Adjust to rustfmt 1.5.0 - https://github.com/rust-lang/rustfmt/blob/master/CHANGELOG.md#removed
@gear-tech/dev

rustfmt: don't specify removed option

---

utils/economic-checks/src/targets.rs

Added another legit error that should be ignored by the fuzzer while testing targets.

Fix fuzzer

---

Cargo.lock
Cargo.toml

https://github.com/gear-tech/substrate/pull/12
@gear-tech/dev

Switch to `wasmi 0.11.0`

---

pallets/gear/rpc/runtime-api/src/lib.rs
pallets/gear/rpc/src/lib.rs
pallets/gear/src/lib.rs
runtime/src/lib.rs

Resolves #1090 
@gear-tech/dev

Repeat calculate_gas_info logic on gear/rpc side

---

examples/chat/Cargo.toml
utils/wasm-builder/src/builder_error.rs
utils/wasm-builder/src/lib.rs
utils/wasm-builder/src/optimize.rs
utils/wasm-builder/src/wasm_project.rs
utils/wasm-proc/src/main.rs

Resolves #1100 .
@gear-tech/dev

Check for required export functions in `wasm-proc` and `wasm-builder`

---

.github/workflows/CI.yaml

Resolves #1153 
@gear-tech/dev

Add ability to pin nightly toolchain

---

gear-test/spec/test_async_recursion.yaml
gear-test/spec/test_chat.yaml
gear-test/spec/test_exit_code.yaml
gear-test/spec/test_program_generator.yaml
gear-test/spec/test_vec.yaml

Change spec titles to render its test's logic

---

core-processor/src/common.rs
core-processor/src/configs.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core-processor/src/lib.rs
core-processor/src/processor.rs
core/src/costs.rs
gear-test/src/check.rs
gear-test/src/main.rs
gear-test/src/manager.rs
gear-test/src/proc.rs
gtest/src/manager.rs
gtest/src/program.rs
gtest/src/wasm_executor.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/ext.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager.rs
pallets/payment/src/lib.rs
runtime/src/lib.rs
utils/gear-runtime-test-cli/src/command.rs

Introduce common configs for processor

---

scripts/performance-boxplot.py
scripts/performance-check.sh

Resolves #1168 
- edit performance-check.sh: perform the same count of running for both branches
- render results with boxplots
@gear-tech/dev

Update script and add boxploting

---

common/src/lazy_pages.rs
common/src/lib.rs
runtime/src/lib.rs

change errors to panics

---

core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/wasmi/src/env.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
pallets/gear/src/ext.rs
runtime/src/lib.rs

Resolves #1204 
@gear-tech/dev

Don't process data for stack pages

---

Cargo.lock
common/Cargo.toml
common/src/gas_provider/property_tests/utils.rs
core-backend/sandbox/Cargo.toml
core-backend/wasmi/Cargo.toml
core-backend/wasmi/src/env.rs
core/Cargo.toml
gear-test/Cargo.toml
gtest/Cargo.toml
node/src/benchmarking.rs
node/src/command.rs
node/src/main.rs
node/src/service.rs
pallets/gas/Cargo.toml
pallets/gear-program/Cargo.toml
pallets/gear/Cargo.toml
pallets/gear/src/benchmarking/code.rs
pallets/gear/src/internal.rs
pallets/payment/Cargo.toml
runtime/src/lib.rs
utils/economic-checks/Cargo.toml

update to this commit https://github.com/gear-tech/substrate/commit/afd2e78fc4a6e7d61497815505329015d7507eef
@gear-tech/dev

update substrate, wasmi, parity-wasm, wasm-instrument

---

.github/workflows/CI-drop-cache.yml
.github/workflows/CI.yaml

- save cache to dir with PR number
- unpack if exists or use master cache
- delete cache dir on close event
- don't cancel run on push event
@gear-tech/dev

CI: save temp cache in PR

---

node/res/staging.json

[skip-ci] update bootnodes id

---

common/src/gas_provider/error.rs
common/src/gas_provider/internal.rs
common/src/gas_provider/mod.rs
common/src/gas_provider/node.rs
common/src/gas_provider/property_tests/assertions.rs
common/src/gas_provider/property_tests/mod.rs
pallets/gas/src/lib.rs
pallets/gas/src/tests.rs
runtime/src/lib.rs

Gas locking ability

---

.github/workflows/CD-insert-keys.yml
ansible/insert-node-keys.yaml
ansible/tasks/docker/docker-compose-insert-keys.yaml.j2
ansible/tasks/docker/docker-insert-keys.yaml

Insert keys to our nodes with defined seed
@gear-tech/dev

CD: Insert node keys workflow

---

core-backend/sandbox/src/funcs.rs
core-backend/wasmi/src/funcs.rs
core-processor/src/ext.rs
core/src/env.rs
pallets/gear/src/ext.rs
runtime/src/lib.rs

Resolves #1199 .
@gear-tech/dev

Charge correctly in exit_code context

---

Cargo.lock
common/src/lazy_pages.rs
core-backend/common/src/lib.rs
core-backend/common/src/utils.rs
core-backend/sandbox/src/env.rs
core-backend/wasmi/src/env.rs
core-processor/Cargo.toml
core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core/src/ids.rs
gear-test/src/check.rs
gtest/Cargo.toml
lazy-pages/src/lib.rs
lazy-pages/src/sys.rs
node/cli/Cargo.toml
node/cli/src/benchmarking.rs
pallets/gear-debug/src/tests.rs
pallets/gear/src/ext.rs
pallets/gear/src/lib.rs
pallets/gear/src/tests.rs
runtime-interface/src/deprecated.rs
runtime-interface/src/lib.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs
utils/gear-runtime-test-cli/Cargo.toml
utils/wasm-builder/Cargo.toml

Rebasing `vara-stage-1` branch on top of `master` to contain restored custom transaction fees

Rebase vara stage 1

---

.github/workflows/CD-vara.yml
ansible/tasks/docker/docker-compose-vara.yaml.j2
ansible/tasks/docker/docker-vara.yaml
ansible/vara.yaml
docker/Vara-Dockerfile

add vara CD

---

.github/workflows/vara-deploy-only.yml

add cd only for deploy vara

---

.github/workflows/CI.yaml
scripts/check-spec.sh

Fix `check-spec` on CI

---

pallets/gear/src/tests.rs

Adjust pallet gear tests

---

.github/workflows/CD.yml

Add git files when building node for CD

---

.github/workflows/CD.yml

[skip ci] add git hash

---

pallets/gear/src/lib.rs
pallets/gear/src/tests.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Recently we have merged PR with some fix of the logic for mailbox and PR that contains test, relying on this logic. There were no merge conflicts and PR-CI passed well independent, but failed on master merge.
This PR fixes the test and restores CI on master.

Fix test on CI

---

.github/workflows/CI.yaml
Makefile
examples/Cargo.lock
examples/Cargo.toml
examples/loop/Cargo.toml
examples/loop/src/lib.rs
scripts/gear.sh
scripts/src/test.sh
scripts/test-utils/infiniteLoop.js
scripts/test-utils/package.json
scripts/test-utils/processingMessageWithRuntimeUpgrade.js
scripts/test-utils/util.js

Resolves #573.
In general, issue solved by a lot of PRs, fixes and optimisations.
This PR includes test on real client, which checks that the message with inf loop and maximal gas limit for block works (successfully fails) and don't executes twice.
Thanks @osipov-mit for the most of js code, but it had some bugs which were fixed by me, so it should be properly reviewed.

Test for weight on loop on client

---

gcore/src/msg.rs
gstd/src/msg/basic.rs

Skip `gr_read` on empty

---

ansible/tasks/docker/docker-compose-insert-keys.yaml.j2
core-processor/src/executor.rs
core/src/message/common.rs
core/src/message/stored.rs
gstd/codegen/src/lib.rs
gtest/src/mailbox.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs
utils/economic-checks/src/targets.rs

CD: use doubleqoutes in jinja template

---

.github/workflows/CI.yaml

CI: get correct branch name

---

.github/workflows/CI.yaml

[skip ci] Move build cache to host

---

ansible/tasks/docker/docker-compose-insert-keys.yaml.j2

[skip ci] fix keys scheme

---

.github/workflows/CI.yaml

[skip ci] Fix upload job

---

scripts/check-spec.sh

`check-spec.sh` skips Vara version check if Gear have an inactual version

Fix script sometimes skips spec check

---

examples/Cargo.lock
examples/async-multisig/Cargo.toml
examples/async-sign/Cargo.toml

Resolves #1425 
@gear-tech/dev

Set only sr25519 for sp-core

---

examples/Cargo.lock
examples/async-multisig/Cargo.toml
examples/async-multisig/src/lib.rs
examples/async-sign/Cargo.toml
examples/async-sign/src/lib.rs
examples/light_sr25519/Cargo.toml
examples/light_sr25519/src/lib.rs

Resolves #1437 
@gear-tech/dev

Remove sp-core dependency from multisig and async-sign

---

.github/workflows/CI.yaml
Makefile
scripts/gear.sh
scripts/src/test.sh
scripts/test-utils/harmlessUploadDemos.js
scripts/test-utils/infiniteLoop.js
scripts/test-utils/package.json
scripts/test-utils/processingMessageWithRuntimeUpgrade.js
scripts/test-utils/util.js

Resolves #1378.
`./scripts/gear.sh test uploads "any" "amount" "of" "demos"` to check that their upload doesn't stop the node, independently from program init status

Separate client upload tests

---

.github/workflows/CI.yaml

Resolves #1445 
@gear-tech/dev

Remove notifications with performance results

---

gstd/src/common/primitives.rs
gstd/src/msg/basic.rs

- Add `ActorId::is_zero` function to `gstd` for checking whether `ActorId` is the zero address.
- Cover the new function with test.
- Fix doc tests in `gstd`.
@gear-tech/dev

gstd: Add `ActorId::is_zero` utility function

---

ansible/tasks/docker/docker-compose.yaml.j2

add network selector for logs

---

.github/workflows/CI.yaml
Cargo.lock
examples/wat-examples/inf_recursion.wat
lazy-pages/Cargo.toml
lazy-pages/src/lib.rs
lazy-pages/src/sys/unix.rs
scripts/src/build.sh
scripts/test-utils/util.js

fix problem with wasmer fault when lazy pages set sigaction

---

Cargo.lock
node/service/Cargo.toml
node/service/src/chain_spec/mod.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Vara: Add ChainSpec extensions (#1424)

---

core-processor/src/configs.rs
core/src/code.rs
gear-test/src/proc.rs
pallets/gear/src/lib.rs
pallets/gear/src/schedule.rs
pallets/gear/src/tests.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Resolves #1500 
@gear-tech/dev

Add check for static memory pages in Code

---

core/src/code.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

While they are not desirable, there is nothing wrong if somebody wants to add wasm with custom section(s)

Remove restrictions on custom section

---

pallets/gear-scheduler/src/lib.rs
pallets/gear/src/mock.rs
pallets/gear/src/tests.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Resolves #1512 
@gear-tech/dev

Set non-zero DbWeight in tests

---

.github/workflows/CI.yaml
scripts/src/build.sh
scripts/src/init.sh

Run JS tests in Windows CI

---

scripts/src/init.sh

Use `$RUNNER_OS` instead of `$OSTYPE`

---

node/res/vara.json
node/service/src/chain_spec/vara.rs

Vara: Fix spec

---

gtest/src/program.rs

Fix tests on Windows

---

.github/workflows/test-measurements.yaml
pallets/gear-program/src/tests.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Install required build dependency (protoc)

---

Cargo.lock
core/src/message/mod.rs
gclient/src/api/calls.rs
gclient/src/api/listener/mod.rs
program/scripts/generate-api.sh
program/src/api/generated/metadata.rs
program/src/api/generated/mod.rs
program/src/cmd/info.rs
program/tests/cmd/reply.rs
program/tests/cmd/send.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs
utils/node-loader/src/batch_pool.rs
utils/node-loader/src/batch_pool/batch.rs
utils/node-loader/src/batch_pool/batch/create_program.rs
utils/node-loader/src/batch_pool/batch/send_message.rs
utils/node-loader/src/batch_pool/batch/upload_code.rs
utils/node-loader/src/batch_pool/batch/upload_program.rs
utils/node-loader/src/batch_pool/context.rs
utils/node-loader/src/batch_pool/generators.rs
utils/node-loader/src/batch_pool/report.rs
utils/node-loader/src/utils.rs
utils/regression-analysis/Cargo.toml
utils/regression-analysis/src/main.rs
utils/regression-analysis/src/output.rs

Partially resolved #1449 .
- Implements send_message test task
- Implements upload_code test task
- Implements create_program test task
The functionality can be considered as an MVP version of the `gear-node-loader`.

Introduce more calls to `gear-node-loader` (loader MVP-version)

---

.github/workflows/CI.yaml
lazy-pages/src/sys/windows.rs
program/src/keystore/key.rs

- Pin Rust in Windows CI
- Fix gclient tests on Windows
- Don't pin rustup anymore

Windows fixes

---

.github/workflows/Runtime-upgrade-reset.yaml
.github/workflows/Runtime-upgrade.yaml

- Build and test runtime directly in the correspondent workflow.
@gear-tech/dev

[skip ci] Improve runtime upgrade workflows

---

.github/workflows/CD-gear-loader-network.yml
ansible/gear-loader.yaml

add wf for test gear-loader-network

Sf gear loader network

---

core-processor/src/configs.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core-processor/src/processor.rs
core/src/message/context.rs
gear-test/src/proc.rs
gtest/src/lib.rs
gtest/src/manager.rs
gtest/src/wasm_executor.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager/journal.rs
pallets/gear/src/tests.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Sending message fee

---

node/cli/Cargo.toml

`node/cli`: default `lazy-pages` feature

---

Cargo.lock
common/Cargo.toml
examples/Cargo.lock
examples/fungible-token/Cargo.toml
examples/token-vendor/Cargo.toml
gear-test/Cargo.toml
gstd/Cargo.toml
pallets/gas/Cargo.toml
pallets/gear-debug/Cargo.toml
pallets/gear-messenger/Cargo.toml
pallets/gear-program/Cargo.toml
pallets/gear-scheduler/Cargo.toml
pallets/gear/Cargo.toml
pallets/payment/Cargo.toml
pallets/payment/src/lib.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs
utils/economic-checks/Cargo.toml
utils/test-runtime/Cargo.toml
utils/test-runtime/src/lib.rs

Update substrate and dependencies

---

.github/workflows/CI.yaml

Fix rust-covfix

---

Cargo.lock
core-processor/src/ext.rs
gclient/Cargo.toml
gclient/tests/upload.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

fix alloc overflow when 0 pages allocated 

---

runtime/vara/src/lib.rs
runtime/vara/src/migrations.rs

`vara-stage-2` SessionKeys migration

---

Cargo.lock

Fix wrong Cargo.lock on Windows

---

Cargo.lock
core-processor/Cargo.toml
core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/processor.rs
core/src/program.rs
gtest/src/manager.rs
gtest/src/wasm_executor.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Refactor `gear-core-processor` crate and cover by tests

---

.github/workflows/CD-gear-loader-network.yml
ansible/gear-loader.yaml

Sf add load

---

.github/workflows/CD.yml
.github/workflows/rollback-testnet.yml

Sf remove issue

---

.github/workflows/CI-gear-loader-network.yml
docker/gear-loader/Dockerfile

ci loader 1st version

---

Cargo.lock

Manually brought the Substrate version for newly added pallets up to date.

Align substrate version across pallets

---

core-backend/sandbox/src/runtime.rs
core-backend/wasmi/src/funcs/mod.rs
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Resolves #1821 
-
-
-
@gear-tech/dev

Don't overwrite the last error

---

node/res/stable.json

Fix bootnode peer ids

---

Cargo.lock
Makefile
examples/ping/src/lib.rs
gcore/Cargo.toml
gcore/src/error.rs
gcore/src/exec.rs
gcore/src/general.rs
gcore/src/lib.rs
gcore/src/msg.rs
gcore/src/prog.rs
gcore/src/utils.rs
gstd/src/msg/basic.rs
scripts/gear.sh
scripts/src/test.sh

- Part of #196
Rendered: https://docs.gear.rs/pr-1867/gcore/

Improve `gcore` crate documentation

---

.github/workflows/CI.yaml

Add new CI runners

---

pallets/payment/src/mock.rs
pallets/payment/src/tests.rs

Adjust payment tests

---

pallets/gear/src/benchmarking/mod.rs

Fix kb benches

---

.github/workflows/CI.yaml

CI: download cachepot

---

.github/workflows/test-measurements.yaml

Use different directory for test data

---

.github/workflows/test-measurements.yaml

Fix generate report step in test-measurements.yaml

---

ansible/tasks/docker/docker-compose.yaml.j2

remove log level

---

Cargo.lock

update substrate commit number

---

.github/workflows/CI.yaml
.github/workflows/docs.yml
Makefile
examples/binaries/signal-entry/src/lib.rs
gcore/src/exec.rs
scripts/gear.sh
scripts/src/test.sh

- Added doc tests to CI that allows keeping examples in docs up-to-date.
@gear-tech/dev

Add doc tests to CI

---

.github/workflows/CI.yaml

https://github.com/actions/runner/issues/491

Fix GH Actions conditional `needs`

---

gear-test/src/js/mod.rs

Resolves #1957 
@gear-tech/dev

Use CARGO_MANIFEST_DIR to get root of the repo

---

utils/node-loader/src/CHANGELOG.md
utils/node-loader/src/batch_pool/generators/batch.rs
utils/node-loader/src/batch_pool/generators/seed.rs

Need this changes for better bugs inspecting experience.

Make deterministic generation of seed for code seed generator

---

node/authorship/src/authorship.rs

Set log target for gear-authorship

---

node/res/staging.json
node/service/src/chain_spec/gear.rs

[skip ci] Rename staging testnet

---

Cargo.lock
Cargo.toml

Fix `wasmtime-runtime` build on Windows

---

utils/junit-common/src/lib.rs

Adjust junit-common to the new quick-xml

---

pallets/gear/Cargo.toml

- Resolves #2064
@gear-tech/dev

Fix bug with extra Wasms generated by `gclient`

---

.github/workflows/test-measurements.yaml

Install wget, bzip2 for measurements CI

---

Cargo.lock
gclient/Cargo.toml
gclient/src/api/calls.rs
gclient/src/api/error.rs
gclient/src/api/listener/iterator.rs
gclient/src/api/listener/mod.rs
gclient/src/api/mod.rs
gclient/src/api/rpc.rs
gclient/src/api/storage/block.rs
gclient/src/api/storage/mod.rs
gclient/src/lib.rs
gclient/src/node/ws.rs
gclient/src/utils.rs
gclient/tests/keyhasher.rs
gclient/tests/loop.rs
gclient/tests/state.rs
gclient/tests/upload.rs
gtest/src/mailbox.rs
gtest/src/system.rs
gtest/src/wasm_executor.rs
scripts/src/format.sh

Add more docs to `gclient` crate

---

core-backend/common/src/mock.rs
core-backend/sandbox/src/funcs.rs
core-backend/wasmi/src/funcs/mod.rs
core-processor/src/ext.rs
core/src/env.rs
pallets/gear/src/ext.rs

Signed-off-by: Mikita Stryzhak <mikita.stryzhak@gmail.com>
Resolves #1652

safety refactor for read ext

---

common/src/gas_provider/internal.rs
common/src/gas_provider/mod.rs
common/src/gas_provider/negative_imbalance.rs
common/src/gas_provider/positive_imbalance.rs
common/src/gas_provider/property_tests/mod.rs
pallets/gas/src/lib.rs
pallets/gas/src/tests.rs
pallets/gear/src/internal.rs

Reflect imbalance on the total supply as soon as imbalance gets created

Refactor gas tree imbalances

---

pallets/gear/src/tests.rs

extrinsic send to unitialized program

---

common/src/benchmarking.rs
common/src/program_storage.rs
pallets/gear-debug/src/lib.rs
pallets/gear-program/src/lib.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/benchmarking/syscalls.rs
pallets/gear/src/benchmarking/utils.rs
pallets/gear/src/lib.rs
pallets/gear/src/manager/journal.rs
pallets/gear/src/manager/mod.rs
pallets/gear/src/queue.rs
pallets/gear/src/runtime_api.rs
pallets/gear/src/tests.rs
program/src/api/storage.rs
utils/gear-runtime-test-cli/src/command.rs

Signed-off-by: MikitaS <mikita.stryzhak@gmail.com>
Resolves #2003

implement block_number for ActiveProgram, terminated and exited program

---

Cargo.lock
core-processor/src/executor.rs
examples/binaries/new-meta/Cargo.toml
examples/binaries/new-meta/state-v3/Cargo.toml
examples/binaries/new-meta/state-v3/build.rs
examples/binaries/new-meta/state-v3/src/lib.rs
examples/binaries/new-meta/state-v3/src/wasm.rs
pallets/gear/src/runtime_api.rs
pallets/gear/src/tests.rs

Fix bn and timestamp query in state fns

---

Cargo.lock
node/cli/src/command.rs
node/service/src/chain_spec/vara.rs
runtime/vara/Cargo.toml
runtime/vara/src/lib.rs

Also remove unused chain config

Add vesting pallet to vara runtime

---

.github/workflows/CI.yaml
Cargo.lock
examples/Cargo.lock
scripts/src/build.sh

Check whether `Cargo.lock` need to be updated et early stages: https://github.com/gear-tech/gear/actions/runs/4117599630/jobs/7109093163

Revert check for `--locked` in CI

---

Cargo.lock
gclient/src/api/storage/account_id.rs
gclient/src/api/storage/into_account_id.rs
gclient/src/api/storage/mod.rs

Get rid of using Borrow in gclient

---

program/build.rs

Fix the build in the `production` profile.
See: 
- https://github.com/gear-tech/gear/actions/runs/4105904728/jobs/7083419986
- https://github.com/gear-tech/builds/actions/runs/4119467304/jobs/7113164656

Fix build in `production` profile

---

utils/wasm-gen/src/lib.rs

Resolves #2155 
-
-
-
@gear-tech/dev

Use msg::source for send-calls in some cases

---

node/res/staging.json

Update peer id in spec

---

.github/workflows/CD.yml
ansible/tasks/docker/docker-compose.yaml.j2

Sergeyfilyanin patch 1

---

core-processor/src/ext.rs
pallets/gear/src/tests.rs

Resolves https://github.com/gear-tech/core-audit/issues/22
It's temporary solution just to remove possibility of runtime to panic. Proper one, that doesn't brake or add new invariants will be applied soon.

Resolve of runtime panic in msgs sendings.

---

core-backend/common/src/lib.rs
core-backend/common/src/memory.rs
core-backend/sandbox/src/env.rs
core-backend/sandbox/src/funcs.rs
core-backend/sandbox/src/memory.rs
core-backend/sandbox/src/runtime.rs
core-backend/wasmi/src/env.rs
core-backend/wasmi/src/funcs/internal.rs
core-backend/wasmi/src/funcs/mod.rs
core-backend/wasmi/src/memory.rs
core-backend/wasmi/src/state.rs
core-errors/src/lib.rs
core-processor/src/common.rs
core-processor/src/executor.rs
core-processor/src/ext.rs
core/src/env.rs
core/src/memory.rs
core/src/message/context.rs
gtest/src/program.rs
pallets/gear/src/tests.rs
utils/wasm-instrument/src/tests.rs

backend errors refactoring

---

core-backend/common/src/lib.rs
core-backend/sandbox/src/env.rs
core-backend/wasmi/src/env.rs
core-processor/src/common.rs
core-processor/src/executor.rs
pallets/gear/src/tests.rs

Validate actor backend errors

---

core-backend/sandbox/src/funcs.rs
core-backend/wasmi/src/funcs/internal.rs
core-backend/wasmi/src/funcs/mod.rs
gcore/src/msg.rs
gsys/src/lib.rs

Use u32::MAX as special ptr on backend

---

.github/workflows/CI.yaml
.github/workflows/release.yml

- Added vara-runtime artifacts
- Added CI workflow for release

Add CI workflow for release

---

ansible/tasks/docker/docker-compose-vara.yaml.j2
ansible/tasks/docker/docker-compose.yaml.j2

fix connect to loki

---

.github/workflows/release.yml
utils/wasm-proc/src/main.rs

- Added new allowed imports for Vara runtime.
- Added a runtime check for allowed imports before release.
@gear-tech/dev

Test runtime imports before release

---

core-backend/common/src/mock.rs
core-processor/src/common.rs
core-processor/src/context.rs
core-processor/src/ext.rs
core-processor/src/lib.rs
core-processor/src/precharge.rs
core/src/gas.rs
pallets/gear/src/benchmarking/mod.rs
pallets/gear/src/benchmarking/tests/lazy_pages.rs
pallets/gear/src/ext.rs
pallets/gear/src/runtime_api.rs

Remove Clone derive for GasCounter

---

Cargo.lock
Cargo.toml

Unpin wasmtime

---

Cargo.lock
node/cli/Cargo.toml

update to substrate with new cli param: default_heap_pages

---

gcli/tests/rpc/mod.rs
gsdk/src/metadata/impls.rs
gsdk/src/metadata/mod.rs

Support of dynamic call to system::set_storage and turning IDs into copyable

Support dynamic call of system::set_storage via gsdk

---

Cargo.lock
gcli/Cargo.toml
gcli/src/cmd/program.rs
gcli/tests/cmd/upload.rs
gcli/tests/common/mod.rs
gcli/tests/rpc/mod.rs
gclient/Cargo.toml
gclient/src/api/calls.rs
gclient/src/api/error.rs
gclient/src/api/storage/mod.rs
gclient/src/lib.rs
gclient/tests/node.rs
gsdk/src/result.rs
gsdk/src/signer/calls.rs
gsdk/src/storage.rs

Add program migration functionality

---

gclient/src/node/mod.rs

- Made it possible to spawn a Vara node in the dev-mode.
@gear-tech/dev

gclient: Add dev Vara node spawning

---

core-backend/common/src/mock.rs
core-backend/sandbox/src/funcs.rs
core-backend/wasmi/src/funcs/mod.rs
core-processor/src/ext.rs
core/src/env.rs
pallets/gear/src/ext.rs

Remove redundant `Ext` methods

---

.github/workflows/CI.yaml

Remove target and cargo registry archives.
I will try to setup sccache server to avoid copying files.
@gear-tech/dev

use sccache instead of cachepot

---

.github/workflows/CI.yaml
utils/node-loader/src/batch_pool/api/mod.rs

pack cargo registry and set env

---

core/src/code.rs
pallets/gear/src/tests.rs

Add checking that gear stack end pointer does not overlap

---

.github/workflows/CI.yaml

Stabilize CI

---

utils/wasm-gen/src/lib.rs

Resolves #2156
The same way as for `handle` method.
@gear-tech/dev

Generate handle_reply method

---

runtime/vara/src/constants.rs
runtime/vara/src/lib.rs

Resolves # .
-
-
-
@gear-tech/dev

[vara] 3 sec per block

---

.github/workflows/vara-reset-network.yml
ansible/vara-reset.yaml

Temporary reset

---

runtime/vara/src/lib.rs

[vara] Add ImOnline event handler to gear authorship

---

.github/workflows/release.yml

Pin nightly version in release workflow

---

.github/workflows/release.yml

[skip ci] set rustup home explicitly

---

core-backend/sandbox/src/memory.rs
core-backend/wasmi/src/memory.rs
core-processor/src/ext.rs
core/src/gas.rs
core/src/memory.rs

Move gas charging inside alloc

---

common/src/gas_provider/error.rs
common/src/gas_provider/internal.rs
common/src/gas_provider/mod.rs
common/src/gas_provider/negative_imbalance.rs
common/src/gas_provider/positive_imbalance.rs
common/src/gas_provider/property_tests/mod.rs
gclient/src/api/calls.rs
gsdk/src/signer/calls.rs
gsdk/src/storage.rs
pallets/gas/src/lib.rs

gear-common: Return error in case of imbalance application leads to overflow

---

utils/call-gen/src/claim_value.rs
utils/call-gen/src/create_program.rs
utils/call-gen/src/lib.rs
utils/call-gen/src/send_message.rs
utils/call-gen/src/send_reply.rs
utils/call-gen/src/upload_code.rs
utils/call-gen/src/upload_program.rs

refactor(call-gen): add `impl_convert_traits!` macro to reduce boilerplate code

---

Cargo.lock
Cargo.toml
gclient/Cargo.toml
gclient/tests/upload.rs

chore(gclient): use tokio directly instead of async-std

---

Cargo.lock
Cargo.toml
examples/binaries/async-tester/src/lib.rs
examples/binaries/exit-handle-sender/src/lib.rs
examples/binaries/exit-handle/src/lib.rs
examples/binaries/exit-init/src/lib.rs
examples/binaries/gas-burned/src/lib.rs
examples/binaries/init-fail-sender/src/lib.rs
examples/binaries/init-wait-reply-exit/src/lib.rs
examples/binaries/init-wait/src/lib.rs
examples/binaries/node/src/lib.rs
examples/ping/src/lib.rs
gcli/res/messager/src/lib.rs
gcore/src/lib.rs
gcore/src/utils.rs
gstd/src/common/handlers.rs
gstd/src/lib.rs
gstd/src/prelude.rs

fix(rust): Support new alloc panic handling

---

ansible/tasks/docker/docker-compose.yaml.j2

ci: Update docker-compose.yaml.j2

---

node/res/staging.json

chore(chain-spec): add rpc node in boot nodes section

---

.github/workflows/Update-testnet.yml
docker/Dockerfile

Sf docker toolchain

---

.github/workflows/CI.yaml
scripts/gear.sh
scripts/src/build.sh

Gear build task on test-measurements workflow ends up with an error due to defining additional features for the build, but there could not be present no such feature for fuzzer crates.
Fixing this: https://github.com/gear-tech/gear/actions/runs/4813444421/jobs/8569982679

ci: stabilize test-measurements workflow

---

.github/workflows/release.yml

chore(cd): fix release workflow

---

node/res/vara.json

Resolves # .
-
-
-
@gear-tech/dev

chore(vara): change boot nodes to connect nodes

---

Cargo.lock
utils/wasm-builder/Cargo.toml
utils/wasm-builder/src/optimize.rs
utils/wasm-builder/src/stack_end.rs

- test case for sample binary produced by AssemblyScript
-
-
@gear-tech/dev

feat(wasm-builder, wasm-proc): use actual index of __stack_pointer global

---

gstd/src/async_runtime/locks.rs

docs(gstd): explain message locks removing

---

Cargo.lock
runtime/gear/Cargo.toml
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

Resolves #2021.
@gear-tech/dev

refactor(runtime): change saturating to checked in `MAXIMUM_BLOCK_WEIGHT`

---

.github/workflows/build-node-fuzzer.yaml
docker/runtime-fuzzer/Dockerfile
docker/runtime-fuzzer/scripts/fuzzer.service
docker/runtime-fuzzer/scripts/fuzzer.sh

ci(node-fuzzer): Script to run node-fuzzer in background and small fixes

---

.github/workflows/CI.yaml

ci: Try to fix `build-win-native` job launch

---

.github/workflows/CI.yaml
pallets/gas/src/migrations.rs
pallets/gas/src/mock.rs
pallets/gas/src/tests.rs
pallets/gear-program/src/migration.rs
pallets/gear-scheduler/src/migration.rs
pallets/gear/rpc/src/lib.rs

Note that summary migrations weight exceeds `max_block` parameter

test(ci): Run runtime upgrade check

---

README.md
scripts/install.sh

Resolves # .
```
Install a binary release of gear hosted on get.gear.rs
USAGE:
install [options]
FLAGS:
-h, --help      Display this message
-f, --force     Force overwriting an existing binary
OPTIONS:
--tag TAG       Tag (version) of the crate to install, defaults to latest release
--to LOCATION   Where to install the binary [default: /usr/local/bin]
--target TARGET
```
@gear-tech/dev

feat(script): Add install script for *nix

---

core-backend/common/src/mock.rs
core-processor/src/ext.rs
core/src/env.rs
pallets/gear/src/ext.rs

refactor(core): revert `self` mutability for `Ext` trait

---

common/src/paused_program_storage.rs

chore(core): Hash the data of pausing program in two steps

---

.github/workflows/CI.yaml
.github/workflows/release.yml

chore(ci): bump sccache v0.5.1

---

Cargo.lock
runtime/common/Cargo.toml
runtime/common/src/lib.rs
runtime/common/src/migration.rs
runtime/gear/src/migrations.rs
runtime/vara/src/migrations.rs

fix(weights): Fix `SessionValidatorSetMigration` weight

---

core-backend/sandbox/src/funcs.rs
core-backend/wasmi/src/funcs/mod.rs
core-processor/src/ext.rs

fix(core-backend): backend vague errors

---

core-backend/codegen/src/host.rs

Resolves #2704 
[expanded_wasmi_backend.rs.txt](https://github.com/gear-tech/gear/files/11620417/expanded_wasmi_backend.rs.txt)
@gear-tech/dev

fix(backend-codegen): appending WGas to gasful host calls

---

Cargo.lock
core/src/code.rs
pallets/gear/src/schedule.rs
scripts/src/build.sh
utils/wasm-builder/Cargo.toml
utils/wasm-builder/src/builder_error.rs
utils/wasm-builder/src/optimize.rs
utils/wasm-builder/src/wasm_project.rs
utils/wasm-instrument/src/lib.rs
utils/wasm-instrument/src/rules.rs
utils/wasm-instrument/src/tests.rs

fix(wasm-builder): detect incorrect code at early stage

---

.github/workflows/benchmarks.yml
scripts/unpack-weights.sh

Changes:
- if `run_all_benchmarks.sh` fails for some reason, `benchmarking_errors.txt` will be uploaded as an artifact
test build with failed assertion: https://github.com/gear-tech/gear/actions/runs/5220070797
- the "Summary" tab will now show tip on how to apply the weight changes to your branch
- fixed undefined functions in `unpack-weights.sh`
- `cargo clean` will remove target folder
successful build: https://github.com/gear-tech/gear/actions/runs/5220175080

ci(benchmarks): add error handling and other improvements

---

.github/workflows/Build-gear-loader-network.yml
.github/workflows/CI.yaml
.github/workflows/Update-Vara-Prod.yml
.github/workflows/Update-testnet.yml
.github/workflows/benchmarks.yml
.github/workflows/build-node-fuzzer.yaml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/rollback-testnet.yml
.github/workflows/test-measurements.yaml
docker/gear-loader/Dockerfile
rust-toolchain.toml

Changes:
- `Build-gear-loader-network.yml` and `gear-loader/Dockerfile`
- fixed typos
- now `gear-node-loader` uses `release` profile instead of `debug`
- other yaml files
- completely removed `NIGHTLY_TOOLCHAIN_VERSION` and solved problems with `build-win-cross`
- `rust-toolchain.toml` contains all required dependencies
- `dsherret/rust-toolchain-file@v1` is used to install rust toolchain from this file
- `SCCACHE_VERSION` is extracted into a variable in all yaml files
- `BINARYEN_VERSION` is extracted into a variable

ci: code cleanup

---

.github/workflows/CI.yaml
.github/workflows/release.yml

chore(ci): Remove sccache

---

core/src/reservation.rs
examples/binaries/reserve-gas/src/lib.rs
pallets/gear/src/tests.rs

Resolves gear-tech/core-audit#24

fix(core): Fix reserve-use-unreserve panic

---

.github/workflows/test-measurements.yaml

chore(tests): Correct cache path in test measurements CI

---

gcore/src/msg.rs

Safe way to load some partial payload!

feat (gstd): add 'read_at' in gcore

---

.github/workflows/CI.yaml
gcli/src/template.rs

Resolves #2802 
@gear-tech/dev

feat(gcli): introduce gh token env for gh requests

---

examples/binaries/btree/src/lib.rs
examples/binaries/out-of-memory/src/lib.rs
gtest/src/program.rs
scripts/src/build.sh
utils/wasm-builder/src/optimize.rs
utils/wasm-builder/src/wasm_project.rs

See my comments below in conversations

refactor(wasm-builder): wasm builder refactoring and some logic improvements 

---

Cargo.lock
examples/binaries/fungible-token/Cargo.toml
examples/binaries/fungible-token/io/src/lib.rs
examples/binaries/fungible-token/src/contract.rs
examples/binaries/fungible-token/src/lib.rs
examples/binaries/fungible-token/tests/benchmarks.rs
gclient/src/api/storage/mod.rs
gsdk/src/storage.rs

The most often operation in FT is transfer. Also better to check it cost when balances table is filled with many users.
Current cost is:
```
===================
Gas burned for one transfer operation = 1.3763630811190306 * 10^9. Calculated as geometric mean from 100 transfer operations.
```

test: ft transfer bench

---

utils/node-loader/src/batch_pool.rs

fix(node-loader): Fix Duration::from_millis

---

Cargo.toml
gtest/Cargo.toml
gtest/src/lib.rs
gtest/src/manager.rs
gtest/src/program.rs

also remove stupid duplicate dep

feat(gtest): add some gtest logging

---

Cargo.lock
galloc/Cargo.toml
gcore/Cargo.toml
gmeta/Cargo.toml
gstd/Cargo.toml
gsys/Cargo.toml

Update user-space libraries to 0.2.0 as well

---

.github/workflows/CI.yaml

feat(ci): Run build job only for A0 or A2 labels

---

Cargo.lock
runtime/gear/src/lib.rs
runtime/vara/src/lib.rs

fix(build): Fix runtime blob version embedding

---

.github/workflows/CI.yaml

ci: run build job on push event

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
galloc/Cargo.toml
gcli/Cargo.toml
gcore/Cargo.toml
gmeta/Cargo.toml
gstd/Cargo.toml
gsys/Cargo.toml
node/cli/Cargo.toml

Resolves #2448 
@gear-tech/dev

chore: inherit version from workspace and bump to v0.2.1

---

gclient/Cargo.toml

fix(gclient): Resolve feature gate issue

---

examples/binaries/new-meta/Cargo.toml
examples/binaries/new-meta/io/Cargo.toml
examples/binaries/new-meta/io/src/lib.rs
examples/binaries/new-meta/state-v1/Cargo.toml
examples/binaries/new-meta/state-v2/Cargo.toml
examples/binaries/new-meta/state-v3/Cargo.toml

Resolves #2882
`cargo install --git` stopped working for some reason. This PR fixes that.
@gear-tech/dev

fix(new-meta): add root workspace

---

.github/workflows/test-measurements.yaml

This should reduce total execution time
@gear-tech/dev

chore(test): Disable path remap in measurements CI

---

.github/workflows/test-measurements.yaml

adjustments after gear-test was removed
@gear-tech/dev

chore(ci): Remove deploy step of runtime tests

---

examples/binaries/waiter/src/code.rs
examples/binaries/waiter/src/lib.rs
gstd/src/lock/access.rs
gstd/src/lock/mutex.rs
gstd/src/lock/rwlock.rs
pallets/gear/src/tests.rs

fix(gstd): Fix deadlocks in mutex/rw-lock

---

gcli/src/template.rs

chore(gcli): Change gh url

---

gstd/Cargo.toml
gstd/src/common/handlers.rs
gstd/src/common/mod.rs
gstd/src/macros/bail.rs
gstd/src/macros/debug.rs

Resolves #2816
Changes:
- conditional compilation has been simplified using De Morgan's laws
- added feature `panic-handler` to the gstd

feat(gstd): add feature `panic-handler`

---

gclient/tests/state.rs

Resolves #2945
We already have this implemented and it makes sense to rewrite tests like this

chore(gclient): improve `get_state` test

---

core-backend/sandbox/Cargo.toml
lazy-pages/Cargo.toml
runtime-interface/Cargo.toml
runtime-interface/src/gear_sandbox/detail.rs
sandbox/host/Cargo.toml
sandbox/host/src/sandbox.rs
sandbox/sandbox/Cargo.toml
sandbox/sandbox/src/lib.rs

refactor(sandbox-host): Remove unnecessary 'host-sandbox' feature

---

.github/workflows/CI.yaml

fix(ci): Disable cachepot in win build

---

utils/wasm-instrument/Cargo.toml
utils/wasm-instrument/src/tests.rs

Now this command works well 
```
cargo test -p gear-wasm-instrument -- test_sys_calls_table
```

fix std feature in gear-wasm-instrument

---

.github/workflows/ignored-tests.yml
.github/workflows/time-consuming-tests.yml
scripts/gear.sh
scripts/src/test.sh

Resolves #2811
Successful build: https://github.com/gear-tech/gear/actions/runs/5706348278

feat(ci): run time consuming tests using github action

---

pallets/gear/src/tests.rs

We had same test for exited program, but not for terminated. So now introducing simple test for that.
@gear-tech/dev

test(pallet-gear): Test pause program task removed for terminated program

---

.github/workflows/build.yml

Resolves #3042
-
-
-
@gear-tech/dev

ci(build): remove sccache status in win-cross

---

Cargo.lock
Cargo.toml
utils/wasm-instrument/Cargo.toml
utils/wasm-instrument/src/lib.rs
utils/wasm-instrument/src/rules.rs

Resolves #3053
part of https://github.com/gear-tech/gear/issues/2923
split from https://github.com/gear-tech/gear/pull/2924
please review 
- https://github.com/gear-tech/wasm-instrument/pull/4
- https://github.com/gear-tech/parity-wasm/pull/1
first
@gear-tech/dev

chore(wasm-instrument): replace wasm-instrument with gwasm-instrument

---

.github/workflows/build.yml

Resolves #3048 
-
-
@gear-tech/dev

ci(build): make workflow build dispatchable

---

sandbox/host/src/sandbox/wasmer_backend.rs

Resolves #3067 
@gear-tech/dev

refactor(sandbox): Extract dispatch_common function in wasmer backend

---

.github/workflows/check.yml
Cargo.lock
scripts/gear.sh
scripts/src/test.sh
utils/call-gen/src/claim_value.rs
utils/call-gen/src/create_program.rs
utils/call-gen/src/lib.rs
utils/call-gen/src/send_message.rs
utils/call-gen/src/send_reply.rs
utils/call-gen/src/upload_code.rs
utils/call-gen/src/upload_program.rs
utils/runtime-fuzzer/Cargo.toml
utils/runtime-fuzzer/src/arbitrary_call.rs
utils/runtime-fuzzer/src/lib.rs
utils/runtime-fuzzer/src/tests.rs

Resolves #3095  .
Also tests that fuzzer is deterministic.
@gear-tech/dev

test(runtime-fuzzer): Test that `GearCalls` generation is deterministic

---

Makefile
scripts/gear.sh
scripts/src/check.sh

feat: check runtime imports in `make pre-commit`

---

gsdk/tests/rpc.rs

- Fixes CI after upgrading Vara Network nodes.
@gear-tech/dev

fix(gsdk): update test after the node upgrade

---

gcli/src/cmd/program.rs
gclient/src/api/rpc.rs
gclient/tests/state.rs
gsdk/src/rpc.rs
pallets/gear/rpc/runtime-api/src/lib.rs
pallets/gear/rpc/src/lib.rs
pallets/gear/src/lib.rs
pallets/gear/src/runtime_api.rs
pallets/gear/src/tests.rs
runtime/common/src/apis.rs

feat(rpc)!: Introduce payload parameter for read_state_using_wasm rpc call

---

scripts/src/test.sh
utils/wasm-builder/tests/smoke.rs

Resolves #3190 
Link to successful build: https://github.com/gear-tech/gear/actions/runs/6009245589

chore(wasm-builder): ignore smoke tests

---

utils/wasm-gen/src/config/syscalls.rs
utils/wasm-gen/src/generator/syscalls.rs
utils/wasm-gen/src/generator/syscalls/invocator.rs
utils/wasm-gen/src/tests.rs

feat(wasm-gen): Implement fallible syscalls error processing setup

---

utils/runtime-fuzzer/README.md

[Rendered](https://github.com/gear-tech/gear/blob/av/runtime-fuzzer-docs/utils/runtime-fuzzer/README.md)

docs(runtime-fuzzer): add documentation for `runtime-fuzzer` crate

---

.github/workflows/test-measurements.yaml

chore: Change runner for measurements CI

---

Cargo.lock
Cargo.toml
examples/autoreply/Cargo.toml
examples/autoreply/build.rs
examples/autoreply/src/lib.rs
examples/autoreply/src/wasm.rs
gtest/src/manager.rs

feat(gtest): Support reply deposit in `gtest`

---

docker/runtime-fuzzer/scripts/fuzzer.sh

Resolves # .
- add new functionality to fuzzer  runner script

chore(scripts): Update `fuzzer.sh`

---

runtime/vara/src/lib.rs

fix(vara): Bump MaxAuthorities to 100_000

---

Makefile
scripts/check-fuzzer.sh
scripts/gear.sh
scripts/src/test.sh

Logs are very heavy and can be obtained from re-running corpus dir files locally.
@gear-tech/dev

feat(runtime-fuzzer): Optionally enable fuzzer logs

---

utils/wasm-gen/src/config/syscalls.rs
utils/wasm-gen/src/generator/syscalls.rs
utils/wasm-gen/src/generator/syscalls/additional_data.rs
utils/wasm-gen/src/generator/syscalls/invocator.rs

feat(wasm-gen): make first param of `gr_exit` configurable

---

docker/runtime-fuzzer/Dockerfile

Resolves # .
- update base image to ubuntu:2204
-
-

update base image for dockerfile fuzzer

---

.github/workflows/check.yml
Makefile
scripts/gear.sh

- help message: https://github.com/gear-tech/gear/blob/master/scripts/src/test.sh#L26
- test command: https://github.com/gear-tech/gear/blob/master/scripts/gear.sh#L312
@gear-tech/dev

chore(scripts): sync doc test command with the help message

---

Cargo.lock
Cargo.toml
galloc/Cargo.toml

update to new dlmalloc revision. See https://github.com/gear-tech/dlmalloc-rust/pull/10

chore(galloc): Update dlmalloc

---

.github/workflows/validation.yml
docker/Dockerfile

Add check for new binary on one of the validator

Add workflow to check changes on validator

---

.github/dependabot.yml

Resolves #3310
not skipping CI in the PRs of depbot
@gear-tech/dev

chore(depbot): not skipping ci

---

.github/workflows/build.yml
gsdk/src/client.rs

Resolves # .
updates the default RPC of gear node, ref #3326 
@gear-tech/dev

chore(gsdk&CI): update RPC endpoints

---

.github/actions/label/skip.js
.github/workflows/PR.yml

support [skip-ci] in commit message
@gear-tech/dev

ci(skip): skip-ci in commit message

---

utils/wasm-gen/src/generator/syscalls.rs
utils/wasm-gen/src/generator/syscalls/invocator.rs

feat(wasm-gen): allow `gr_send_commit*` to receive existing address

---

scripts/benchmarking/run_all_benchmarks.sh

fix(benchmarks): fix benchmarks run on CI runner

---

.github/workflows/PR.yml

not skipping build for `[depbot]` in title
@gear-tech/dev

[depbot] ci(build): not skipping build for depbot

---

.github/workflows/benchmarks.yml
scripts/benchmarking/merge_outputs.sh
scripts/benchmarking/run_all_benchmarks.sh

chore(benchmarks): remove unnecessary output files

---

utils/node-loader/src/utils.rs
utils/runtime-fuzzer/src/gear_calls.rs
utils/wasm-gen/src/config.rs
utils/wasm-gen/src/config/syscalls.rs
utils/wasm-gen/src/config/syscalls/amount.rs
utils/wasm-gen/src/config/syscalls/injection.rs
utils/wasm-gen/src/generator/syscalls.rs
utils/wasm-gen/src/generator/syscalls/imports.rs
utils/wasm-gen/src/tests.rs

feat(wasm-gen): distinguish between importing and inserting functions

---

Cargo.lock
Cargo.toml
runtime/vara/Cargo.toml
runtime/vara/src/lib.rs

- add `pallet-nomination-pools` runtime api calls
- add `pallet-staking` runtime api calls
@gear-tech/dev

feat(vara): Add nomination_pools and staking runtime-api

---

Cargo.lock
Cargo.toml
core/src/memory.rs
core/src/str.rs
examples/signal-entry/src/wasm.rs
gcli/tests/common/args.rs
gcore/src/errors.rs
gcore/src/lib.rs
gcore/src/msg.rs
gcore/src/utils.rs
gstd/src/async_runtime/locks.rs
gstd/src/common/handlers.rs
gstd/src/lib.rs
gstd/src/prelude.rs
gstd/src/sync/mod.rs
gtest/src/system.rs
node/testing/src/client.rs
pallets/gear-bank/src/tests.rs
pallets/gear/src/benchmarking/syscalls.rs
pallets/gear/src/benchmarking/tests/syscalls_integrity.rs
pallets/gear/src/internal.rs
pallets/gear/src/manager/task.rs
pallets/gear/src/tests.rs
rust-toolchain.toml
sandbox/host/src/sandbox/wasmer_backend.rs
utils/wasm-gen/src/config/syscalls/injection.rs
utils/wasm-gen/src/generator/memory.rs
utils/wasm-gen/src/generator/syscalls/additional_data.rs
utils/wasm-gen/src/generator/syscalls/invocator.rs
utils/wasm-gen/src/wasm.rs

Updates rust version to "nightly-2023-10-14"

Update rust version (considering PR)

---

common/src/lib.rs
core-errors/src/lib.rs
core-processor/src/lib.rs
core/src/lib.rs
galloc/src/lib.rs
gclient/src/lib.rs
gcore/src/lib.rs
gmeta/src/lib.rs
gsdk/src/lib.rs
gstd/src/lib.rs
gtest/src/lib.rs
lazy-pages/src/lib.rs
pallets/gas/src/lib.rs
pallets/gear-messenger/src/lib.rs
pallets/gear-program/src/lib.rs
pallets/gear-scheduler/src/lib.rs
pallets/gear/rpc/runtime-api/src/lib.rs
pallets/gear/rpc/src/lib.rs
pallets/gear/src/lib.rs
pallets/payment/src/lib.rs
utils/wasm-builder/src/lib.rs

Resolves #3415
The package list is from https://github.com/gear-tech/gear/blob/master/Makefile#L246
-
-
-

docs(workspace): add favicon url for documented packages

---

.github/workflows/release.yml

rename to `production_vara_runtime_v1000` `testnet_vara_runtime_v1000`

chore(actions): rename wasm runtimes to be more clear. fix changelog

---

Cargo.lock
Cargo.toml
core-errors/src/lib.rs
core-processor/src/ext.rs
core/src/reservation.rs
examples/delayed-reservation-sender/Cargo.toml
examples/delayed-reservation-sender/build.rs
examples/delayed-reservation-sender/src/lib.rs
examples/delayed-reservation-sender/src/wasm.rs
pallets/gear/Cargo.toml
pallets/gear/src/benchmarking/syscalls.rs
pallets/gear/src/internal.rs
pallets/gear/src/tests.rs

Resolves artefacts after #2053

bugfix(runtime): Correct charging on delayed sendings from reservations

---

.github/actions/label/build.js

ci(label): provide precise logs of check runs on skipping build

---

runtime/vara/src/constants.rs

Resolves # .
-
-
-
@gear-tech/dev

chore(vara): Update ECONOMIC_UNIT to 10 UNITS

---

README.md
gclient/src/api/mod.rs
gclient/src/ws.rs
gsdk/src/client.rs
gsdk/tests/rpc.rs
utils/gear-replay-cli/README.md
utils/gear-replay-cli/src/lib.rs

- `vara-network.io` -> `vara.network`
- Removed links to Gear node in `gclient`
- Added Vara Testnet node to `gclient`
@gear-tech/dev

fix: links to Vara network

---

Cargo.lock
Cargo.toml
runtime/vara/src/lib.rs

chore(runtime): Bump versions after `v1.0.4` release

---

Cargo.toml
gsdk/Cargo.toml
gstd/Cargo.toml

This PR is part of #3594 
The modifications in this PR are about to declare these packages in the workspace manifest so there will be no extra work for hacking them
@gear-tech/dev

chore(manifest): complete package alias for code generator libararies

---

pallets/gear/src/runtime_api.rs
pallets/gear/src/tests.rs

fix(rpc-call): Return error on failing init as well as for the traps

---

utils/runtime-fuzzer/src/runtime/block.rs
utils/runtime-fuzzer/src/runtime/mod.rs

Resolves #3291 
All in all problem was with running mandatory `Gear::run` extrinsic. Changes are in accordance to the mock block run in `pallet-gear`.

feat(runtime-fuzzer): Increase processed tasks rate in `runtime-fuzzer`

---

core/src/code/utils.rs
utils/wasm-builder/src/wasm_project.rs

Resolves #3696 and fixes order of export validation
@gear-tech/dev

fix(wasm-builder): improve diagnostics of some errors

---

gcli/src/cmd/create.rs
gcli/src/cmd/reply.rs
gcli/src/cmd/send.rs
gcli/src/cmd/upload.rs

Resolves #3709 
@gear-tech/dev

feat(gcli): make gas limit optional argument

---

node/cli/src/cli.rs
pallets/staking-rewards/src/migrations.rs

If you want, you can cherry pick this changes to your PR and close this PR in order to save runners performance.

fix(workspace): fix some cases for clippy

---

.github/workflows/build-macos.yml

Resolves #3770 .
`wasm-opt optimizations error: wasm-opt not found!`

fix(CI): install wasm-opt for x86 macos

---

core/src/costs.rs

It's part of #3791 , which I wanna to split and commit as smaller parts.

refactor(core): change `PageU32Size` to `PageNumber` in `CostPerPage`

---

Cargo.lock

Relates to  #3669
@gear-tech/dev

chore: Update substrate to use sp-crypto-ec-utils v1.6.0

---

.github/workflows/docs.yml

Forgot to update the docs in master in #3769 
this PR is cherry-picked by #3767 as well, or anybody can include it in ur PR
@gear-tech/dev

ci(docs): fix the parameters of docs in master

---

.github/actions/label/build.js
.github/actions/message/main.js
.github/workflows/build.yml
.github/workflows/label.yml

Resolves https://github.com/gear-tech/gear/actions/runs/8368060285/job/22911543652
- matrix condition for artifacts
- fixes for correcting the checks for check-validator
- workaround for the labeling CI
@gear-tech/dev

ci(build): fix the condition of artifacts

---

.github/workflows/CI.yaml
.github/workflows/PR.yml
.github/workflows/weekly.yml
Cargo.lock
Cargo.toml
Makefile
_typos.toml
common/src/gas_provider/node.rs
gclient/src/api/listener/mod.rs
runtime/vara/src/lib.rs
scripts/gear.sh
scripts/src/test.sh
utils/gear-replay-cli/README.md
utils/wasm-gen/src/config/generator.rs

ci(typos): run typos check weekly

---

.github/workflows/benchmarks.yml
scripts/benchmarking/merge_outputs.sh
scripts/unpack-weights.sh

Resolves #3857
Successful build: https://github.com/gear-tech/gear/actions/runs/8542719395
@gear-tech/dev

fix(benchmarks): improve github workflow, fix regex in merge script

---

.github/workflows/test-measurements.yaml
scripts/gear.sh

To get more details when failed in  a similar cases: https://github.com/gear-tech/gear/actions/runs/8606727144/job/23585737638
@gear-tech/dev

chore: Show error output on failure in measurements

---

gtest/src/manager.rs
gtest/src/system.rs

Introduces reading of code previously submitted into the system

feat(gtest): Intorduce reading of previously submitted code by its id

---

.github/workflows/benchmarks.yml
pallets/gear/src/lib.rs
scripts/unpack-weights.sh

Resolves #3872
Actual benchmarks: https://github.com/gear-tech/gear/actions/runs/8621237788

fix(benchmarks): auto-trigger CI, produce correct output

---

core-processor/src/ext.rs

test: add showcases of some internal bugs

---

core/src/code/errors.rs
core/src/code/mod.rs
core/src/code/utils.rs
pallets/gear/src/tests.rs
utils/wasm-builder/src/code_validator.rs

Resolves #3736.
Add additional import checks to `check_imports`.
Added checks:
* There are no global or table imports in the module.

feat(core): restrict global and table imports in program code

---

utils/gring/src/cmd.rs
utils/gring/src/ss58.rs

Resolves #3914
- `--convert-to-vara` in command <kbd>add</kbd>
- `--force-vara` in command <kbd>list</kbd>
@gear-tech/dev

feat(gring): vara formatter for ss58 addresses

---

.github/actions/message/main.js

Resolves # .
Patch the skip action after https://github.com/gear-tech/gear/pull/3616
@gear-tech/dev

ci(skip): adapt checks with debug profiles

---

core-processor/src/common.rs
gtest/src/manager.rs
pallets/gear/src/manager/mod.rs
pallets/gear/src/queue.rs

chore(core-processor): remove `pages_with_data` from `ExecutableActorData`

---

scripts/benchmarking/run_all_benchmarks.sh

Run the benchmarks `run_all_benchmarks.sh` on an isolated core if it's configured.
(Isolated cores are configured on the bench machine).

test(scripts): run benches on isolated core if configured

---

README.md

fix(readme): remove "gasless" feature description

---

.github/workflows/release.yml

feat: Publish runtime metadata in release

---

Cargo.lock
examples/vec/src/wasm.rs
gclient/src/api/rpc.rs
gsdk/Cargo.toml
gsdk/src/rpc.rs
gsdk/src/signer/rpc.rs
gsdk/tests/rpc.rs

Resolves # https://github.com/gear-tech/gear/issues/3997.

feat(gsdk,gclient): Implement gsdk api for calling gear_calculateReplyForHandle

---

core-processor/src/ext.rs
gsdk/tests/rpc.rs

Bringing back changes after [160c9e4](https://github.com/gear-tech/gear/commit/160c9e462da500fda16af00351fe7b1005e39f34) with a test

fix(core-processor): reduce for mailbox threshold if gasful sent after gasless

---

pallets/gear/src/benchmarking/tests/syscalls_integrity.rs

Append issue to solve this maybe https://github.com/gear-tech/gear/issues/4030

fix: syscalls integrity tests gas_available 

---

gsdk/tests/rpc.rs
gtest/src/program.rs

feat(gtest): Add send_with_gas

---

.github/workflows/check.yml
ethexe/observer/Cargo.toml
ethexe/observer/src/observer.rs

feat(ci): apply changes from ethexe repository

---

Cargo.lock
ethexe/cli/Cargo.toml
ethexe/cli/src/main.rs
ethexe/cli/src/service.rs
ethexe/cli/src/tests.rs
ethexe/common/src/db.rs
ethexe/ethereum/src/lib.rs
ethexe/observer/src/observer.rs
ethexe/runtime/src/wasm/api/run.rs
ethexe/signer/src/lib.rs

1) Append env for testing
2) Append ping test
3) Some minor fixes

tests(ethexe):  append initial `ethexe-cli` integration testing

---

ethexe/cli/src/tests.rs
ethexe/observer/src/observer.rs

this should fix all problems with unstable tests

tests(ethexe): run anvil node in block mining mode

---

ethexe/cli/src/chain_spec.rs
ethexe/cli/src/config.rs
ethexe/docker/docker-compose.yml
ethexe/docker/ethexe_builder.Dockerfile

chore(ethexe): Add bootnodes, update chain-spec

---

core/src/code/utils.rs
gclient/tests/upload.rs
pallets/gear/src/manager/mod.rs
pallets/gear/src/tests.rs

feat(core): set max memory size 2 GB for gear programs

---

pallets/gear-program/src/migrations/allocations.rs

Due this master falling https://github.com/gear-tech/gear/actions/runs/10306438228/job/28529572081

chore(tests): logging init in allocations migrations test

---

common/src/auxiliary/mailbox.rs
common/src/auxiliary/mod.rs
common/src/auxiliary/taskpool.rs
gtest/src/lib.rs
gtest/src/mailbox/actor.rs
gtest/src/mailbox/manager.rs
gtest/src/taskpool.rs

Implementation of AuxiliaryTaskpool. At the moment not used in code. Once merged into master will work into merging it into [#4119](https://github.com/gear-tech/gear/pull/4119)

feat(common, gtest): add AuxiliaryTaskpool

---

scripts/check-lazy-pages-fuzzer.sh
utils/lazy-pages-fuzzer/src/lib.rs

Resolves # .
Remove lazy pages fuzzer host address check.

fix(lazy-pages-fuzzer): remove host address check

---

common/src/pallet_tests.rs
runtime/vara/src/lib.rs
runtime/vara/src/tests.rs

Migrations are already applied in v1.5.0-1 release and should be executed before merging

fix(runtime): Fix staking payout call weight; impl test

---

ethexe/cli/src/service.rs
ethexe/cli/src/tests.rs

This reverts commit 6b4608a740a1e480f3392c83dc13f80a522d4087

fix(ethexe): revert "feat(ethexe): introduce test-only field status for Service (#4182)"

---

Cargo.lock
Cargo.toml
ethexe/cli/src/tests.rs
ethexe/observer/src/observer.rs

chore(deps): update alloy-sol-type-parser, remove old code

---

Cargo.lock
examples/delayed-sender/src/wasm.rs
gtest/Cargo.toml
gtest/src/program.rs

Relates to #4239 
Add self-sent delayed message test to `gtest`.

feat(gtest): add self-sent delayed message test

---

Cargo.lock
utils/wasm-optimizer/Cargo.toml
utils/wasm-optimizer/src/cargo_command.rs
utils/wasm-optimizer/src/cargo_toolchain.rs

feat(wasm-optimizer): build WASMs with `-Ctarget-cpu=mvp`

---

utils/crates-io/src/manifest.rs

Resolves #4253
Attempt to fix https://wiki.vara.network/docs/getting-started-in-5-minutes

fix(crates-io): pin to specific version

---

Cargo.lock
Makefile
ethexe/cli/Cargo.toml
ethexe/cli/src/tests.rs
ethexe/db/src/database.rs
ethexe/processor/src/lib.rs
ethexe/runtime/common/src/journal.rs
ethexe/runtime/common/src/state.rs
ethexe/runtime/src/wasm/storage.rs

feat(ethexe): impl Mailbox interactions

---

Cargo.lock
Cargo.toml
ethexe/cli/src/tests.rs
ethexe/processor/src/common.rs
ethexe/processor/src/handling/events.rs
ethexe/processor/src/handling/mod.rs
ethexe/processor/src/handling/run.rs
ethexe/processor/src/lib.rs
ethexe/processor/src/tests.rs
ethexe/runtime/common/Cargo.toml
ethexe/runtime/common/src/journal.rs
ethexe/runtime/common/src/lib.rs
ethexe/runtime/common/src/state.rs
utils/gring/Cargo.toml
utils/wasm-optimizer/Cargo.toml

What've been implemented:
* Correctly handle storage complex operations by implementing new storage related primitive fns
* Empty storages now result in MaybeHash::Empty
* Some refactoring of processor instance and related funcs by its nature: common_funcs/event_handling/queue_run
* Code simplification

feat(ethexe): Correctly handle storage complex operations 

---

.github/workflows/check.yml

this PR should fix CI, caused by #4235
@gear-tech/dev

fix(ci): install rust-src component for stable rust

---

Cargo.lock
Cargo.toml
ethexe/ethereum/src/lib.rs
ethexe/signer/Cargo.toml
ethexe/signer/src/signature.rs

feat(ethexe-ethereum): Update alloy to 0.4.2

---

.github/workflows/test-measurements.yaml

to fix test measurements - https://github.com/gear-tech/gear/actions/runs/11805839006/job/32889176906
@gear-tech/dev

fix: Adjust benchmark pallet cli argument

---

.github/workflows/benchmarks.yml

fix(ci): fix benchmarks job paths to commit

---

.github/workflows/release.yml

fix(release): change spec version extraction query

---

.config/nextest.toml
gclient/tests/upload.rs

due to https://github.com/gear-tech/gear/actions/runs/12823489087/job/35758070628

chore(tests): re-run tests for gclient if failed

---

examples/piggy-bank/src/wasm.rs
examples/stack-allocations/src/wasm.rs
gcore/src/msg.rs
gstd/src/msg/encoded.rs
gstd/src/msg/mod.rs

chore(gcore): rename with_read_on_stack -> with_read_on_stack_or_heap

---

utils/wasm-builder/src/code_validator.rs
utils/wasm-builder/src/lib.rs

Resolves #4462. 
- add contants module for CodeValidator working
@grishasobol

chore(wasm-builder): add constants module for CodeValidator

---

ethexe/network/src/db_sync/mod.rs
ethexe/network/src/db_sync/ongoing.rs
ethexe/network/src/lib.rs

chore(ethexe): impl `Clone` for `NetworkEvent`

---

Cargo.lock
Cargo.toml
ethexe/ethereum/src/lib.rs
ethexe/ethereum/src/mirror/mod.rs
ethexe/ethereum/src/router/mod.rs
ethexe/ethereum/src/wvara/mod.rs
ethexe/observer/src/blobs.rs
ethexe/observer/src/lib.rs
ethexe/observer/src/sync.rs
ethexe/observer/src/utils.rs
ethexe/service/src/tests.rs

Resolves # .
-
-
-
@grishasobol

feat(ethexe): update alloy to 0.12

---

ethexe/ethereum/src/lib.rs
ethexe/ethereum/src/mirror/mod.rs
ethexe/ethereum/src/router/mod.rs
ethexe/ethereum/src/wvara/mod.rs
ethexe/observer/src/lib.rs
ethexe/observer/src/sync.rs
ethexe/observer/src/tests.rs
ethexe/observer/src/utils.rs
ethexe/service/src/lib.rs
ethexe/service/src/tests.rs

Additionally remove Arc usage from ethexe-ethereum (alloy already use Arc as inner field inside everywhere)

feat(ethexe): append service identity (block-identity) 

---

ethexe/observer/src/blobs.rs
ethexe/observer/src/tests.rs
ethexe/service/src/lib.rs
ethexe/service/src/tests.rs

chore(ethexe): remove block_time in MockBlobReader

---

ethexe/runtime/build.rs
runtime/vara/build.rs

Because https://youtrack.jetbrains.com/issue/RUST-9752 is still opened

chore: Skip runtime build on Intellij project sync

---

.github/workflows/build.yml

chore(ci): disable weight warnings in try-runtime job

---

ethexe/db/src/database.rs

test(ethexe-db): cover program_ids() & check_within_recent_blocks()

---

gsdk/src/metadata/generated.rs
pallets/gear-eth-bridge/Cargo.toml
pallets/gear-eth-bridge/src/benchmarking.rs
pallets/gear-eth-bridge/src/builtin.rs
pallets/gear-eth-bridge/src/lib.rs
pallets/gear-eth-bridge/src/mock.rs
pallets/gear-eth-bridge/src/tests.rs
pallets/gear-eth-bridge/src/weights.rs
runtime/vara/src/lib.rs
runtime/vara/src/tests/mod.rs
runtime/vara/src/weights/pallet_gear_eth_bridge.rs

feat(pallet-gear-eth-bridge): Add message fee

---

Cargo.lock
Cargo.toml
core-errors/src/simple.rs
core-processor/src/lib.rs
core-processor/src/processing.rs
ethexe/runtime/common/src/lib.rs
ethexe/service/src/tests.rs
examples/inheritor-in-error-reply/Cargo.toml
examples/inheritor-in-error-reply/build.rs
examples/inheritor-in-error-reply/src/lib.rs
examples/inheritor-in-error-reply/src/wasm.rs
gsdk/src/metadata/generated.rs
gstd/src/common/errors.rs
gtest/src/lib.rs
gtest/src/log.rs
gtest/src/manager.rs
gtest/src/manager/block_exec.rs
gtest/src/manager/journal.rs
gtest/src/manager/memory.rs
gtest/src/program.rs
gtest/src/state/actors.rs
pallets/gear/src/queue.rs
pallets/gear/src/tests.rs

feat(core-errors): More descriptive `UnavailableActor` (former `InactiveError`)

---

.github/workflows/build.yml

Reference bug: https://github.com/gear-tech/gear/issues/4615

chore(gear): disable win-cross

---

ethexe/docker/docker-compose.yml
ethexe/service/src/tests.rs

Now we have 2 endpoints:
- `wss://reth-rpc.gear-tech.io/ws`
- `https://reth-rpc.gear-tech.io`

chore(workspace): update holesky wss endpoint

---

.github/workflows/label.yml

fix(ci): on_label workflow

---

ethexe/network/src/lib.rs
ethexe/service/src/tests.rs

fix(ethexe-network): Close listeners on drop

---

pallets/gear-builtin/Cargo.toml
pallets/gear-builtin/src/lib.rs
pallets/gear-builtin/src/migration.rs
pallets/gear-builtin/src/mock.rs
pallets/gear-builtin/src/tests/bad_builtin_ids.rs
pallets/gear-builtin/src/tests/staking.rs
pallets/gear-eth-bridge/src/mock.rs
pallets/gear/src/lib.rs
runtime/vara/src/genesis_config_presets.rs
runtime/vara/src/lib.rs
runtime/vara/src/migrations.rs

- impl storage version for builtin pallet
- impl 0 -> 1 migration that topups builtins balances and locks ed as for programs
- top up basic endowment amount for development genesises

fix(builtins): mint and lock ED for builtins as for programs

---

.envrc
.gitignore
examples/big-data-section/proptest-regressions/lib.txt
flake.lock
flake.nix
utils/cargo-gbuild/tests/smoke.rs
utils/wasm-optimizer/src/cargo_command.rs
utils/wasm-optimizer/src/cargo_toolchain.rs

Added a `flake.nix` development environment setup. This allows to build & develop Gear on virtually any machine that supports nix without installing Rust or any other packages on system itself.

feat(tooling): add nix flake development environment

---

ethexe/common/src/gear.rs
ethexe/consensus/src/utils.rs
ethexe/consensus/src/validator/producer.rs
ethexe/consensus/src/validator/submitter.rs
ethexe/ethereum/src/abi/gear.rs
ethexe/signer/src/digest.rs

Resolves #4650 
-
-
-
@grishasobol  @StackOverflowExcept1on

feat(ethexe): support in rust rewards commitment types

---

Cargo.lock
Cargo.toml

Update to the latest version.
@gear-tech/dev

chore(gear-cli): Update mimalloc to 0.1.46

---

lazy-pages/src/sys/unix.rs

Support linux Aarch64 target. 
To run/build project natively on Asahi linux

feat(lazy-pages): Support linux Aarch64 target

---

ethexe/compute/src/lib.rs
ethexe/network/src/lib.rs
ethexe/observer/src/lib.rs

chore(ethexe): Fix clippy warnings

---

.config/nextest.toml
Cargo.lock
core-backend/src/mock.rs
core-errors/Cargo.toml
core-errors/src/lib.rs
core-errors/src/simple.rs
core-processor/Cargo.toml
core-processor/src/executor.rs
core-processor/src/ext.rs
core/Cargo.toml
core/src/message/common.rs
core/src/message/context.rs
core/src/message/handle.rs
core/src/message/incoming.rs
core/src/message/init.rs
core/src/message/mod.rs
core/src/message/reply.rs
core/src/message/signal.rs
core/src/message/stored.rs
core/src/message/user.rs
ethexe/common/src/events/mirror.rs
ethexe/common/src/events/mod.rs
ethexe/common/src/events/wvara.rs
ethexe/common/src/gear.rs
ethexe/ethereum/src/abi/gear.rs
gtest/Cargo.toml
gtest/src/log.rs
gtest/src/manager/block_exec.rs
pallets/gear/src/tests.rs

refactor: remove useless trait derives

---

ethexe/processor/src/handling/run.rs

fix(ethexe-processor): Fix parallel runner state overwrite bug

---

ethexe/compute/src/prepare.rs
ethexe/compute/src/service.rs
ethexe/contracts/src/Router.sol
ethexe/contracts/test/Router.t.sol
ethexe/db/src/database.rs
ethexe/observer/src/lib.rs

Resolves # .
@grishasobol  @StackOverflowExcept1on

feat(`ethexe`); restriction for empty validator set

---

Cargo.lock
Cargo.toml

fix: Bump codec to resolve performance issue

---

.github/workflows/test-measurements.yaml

chore(test-measurements): Checkout submodules recursively
